// Code generated by "stringer -type=DoltgresTypeBaseID"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoltgresTypeBaseID_Any-8192]
	_ = x[DoltgresTypeBaseID_AnyElement-8193]
	_ = x[DoltgresTypeBaseID_AnyArray-8194]
	_ = x[DoltgresTypeBaseID_AnyNonArray-8195]
	_ = x[DoltgresTypeBaseID_AnyEnum-8196]
	_ = x[DoltgresTypeBaseID_AnyRange-8197]
	_ = x[DoltgresTypeBaseID_AnyMultirange-8198]
	_ = x[DoltgresTypeBaseID_AnyCompatible-8199]
	_ = x[DoltgresTypeBaseID_AnyCompatibleArray-8200]
	_ = x[DoltgresTypeBaseID_AnyCompatibleNonArray-8201]
	_ = x[DoltgresTypeBaseID_AnyCompatibleRange-8202]
	_ = x[DoltgresTypeBaseID_AnyCompatibleMultirange-8203]
	_ = x[DoltgresTypeBaseID_CString-8204]
	_ = x[DoltgresTypeBaseID_Internal-8205]
	_ = x[DoltgresTypeBaseID_Language_Handler-8206]
	_ = x[DoltgresTypeBaseID_FDW_Handler-8207]
	_ = x[DoltgresTypeBaseID_Table_AM_Handler-8208]
	_ = x[DoltgresTypeBaseID_Index_AM_Handler-8209]
	_ = x[DoltgresTypeBaseID_TSM_Handler-8210]
	_ = x[DoltgresTypeBaseID_Record-8211]
	_ = x[DoltgresTypeBaseID_Trigger-8212]
	_ = x[DoltgresTypeBaseID_Event_Trigger-8213]
	_ = x[DoltgresTypeBaseID_PG_DDL_Command-8214]
	_ = x[DoltgresTypeBaseID_Void-8215]
	_ = x[DoltgresTypeBaseID_Unknown-8216]
	_ = x[DoltgresTypeBaseID_Int16Serial-8217]
	_ = x[DoltgresTypeBaseID_Int32Serial-8218]
	_ = x[DoltgresTypeBaseID_Int64Serial-8219]
	_ = x[DoltgresTypeBaseID_Regclass-8220]
	_ = x[DoltgresTypeBaseID_Regcollation-8221]
	_ = x[DoltgresTypeBaseID_Regconfig-8222]
	_ = x[DoltgresTypeBaseID_Regdictionary-8223]
	_ = x[DoltgresTypeBaseID_Regnamespace-8224]
	_ = x[DoltgresTypeBaseID_Regoper-8225]
	_ = x[DoltgresTypeBaseID_Regoperator-8226]
	_ = x[DoltgresTypeBaseID_Regproc-8227]
	_ = x[DoltgresTypeBaseID_Regprocedure-8228]
	_ = x[DoltgresTypeBaseID_Regrole-8229]
	_ = x[DoltgresTypeBaseID_Regtype-8230]
	_ = x[DoltgresTypeBaseID_Bool-3]
	_ = x[DoltgresTypeBaseID_Bytea-7]
	_ = x[DoltgresTypeBaseID_Char-9]
	_ = x[DoltgresTypeBaseID_Date-15]
	_ = x[DoltgresTypeBaseID_Float32-21]
	_ = x[DoltgresTypeBaseID_Float64-23]
	_ = x[DoltgresTypeBaseID_Int16-27]
	_ = x[DoltgresTypeBaseID_Int32-29]
	_ = x[DoltgresTypeBaseID_Int64-33]
	_ = x[DoltgresTypeBaseID_InternalChar-96]
	_ = x[DoltgresTypeBaseID_Interval-37]
	_ = x[DoltgresTypeBaseID_Json-39]
	_ = x[DoltgresTypeBaseID_JsonB-41]
	_ = x[DoltgresTypeBaseID_Name-90]
	_ = x[DoltgresTypeBaseID_Null-53]
	_ = x[DoltgresTypeBaseID_Numeric-54]
	_ = x[DoltgresTypeBaseID_Oid-92]
	_ = x[DoltgresTypeBaseID_Text-64]
	_ = x[DoltgresTypeBaseID_Time-66]
	_ = x[DoltgresTypeBaseID_Timestamp-70]
	_ = x[DoltgresTypeBaseID_TimestampTZ-74]
	_ = x[DoltgresTypeBaseID_TimeTZ-68]
	_ = x[DoltgresTypeBaseID_Uuid-82]
	_ = x[DoltgresTypeBaseID_VarChar-86]
	_ = x[DoltgresTypeBaseID_Xid-94]
	_ = x[DoltgresTypeBaseId_Domain-98]
}

const _DoltgresTypeBaseID_name = "DoltgresTypeBaseID_BoolDoltgresTypeBaseID_ByteaDoltgresTypeBaseID_CharDoltgresTypeBaseID_DateDoltgresTypeBaseID_Float32DoltgresTypeBaseID_Float64DoltgresTypeBaseID_Int16DoltgresTypeBaseID_Int32DoltgresTypeBaseID_Int64DoltgresTypeBaseID_IntervalDoltgresTypeBaseID_JsonDoltgresTypeBaseID_JsonBDoltgresTypeBaseID_NullDoltgresTypeBaseID_NumericDoltgresTypeBaseID_TextDoltgresTypeBaseID_TimeDoltgresTypeBaseID_TimeTZDoltgresTypeBaseID_TimestampDoltgresTypeBaseID_TimestampTZDoltgresTypeBaseID_UuidDoltgresTypeBaseID_VarCharDoltgresTypeBaseID_NameDoltgresTypeBaseID_OidDoltgresTypeBaseID_XidDoltgresTypeBaseID_InternalCharDoltgresTypeBaseId_DomainDoltgresTypeBaseID_AnyDoltgresTypeBaseID_AnyElementDoltgresTypeBaseID_AnyArrayDoltgresTypeBaseID_AnyNonArrayDoltgresTypeBaseID_AnyEnumDoltgresTypeBaseID_AnyRangeDoltgresTypeBaseID_AnyMultirangeDoltgresTypeBaseID_AnyCompatibleDoltgresTypeBaseID_AnyCompatibleArrayDoltgresTypeBaseID_AnyCompatibleNonArrayDoltgresTypeBaseID_AnyCompatibleRangeDoltgresTypeBaseID_AnyCompatibleMultirangeDoltgresTypeBaseID_CStringDoltgresTypeBaseID_InternalDoltgresTypeBaseID_Language_HandlerDoltgresTypeBaseID_FDW_HandlerDoltgresTypeBaseID_Table_AM_HandlerDoltgresTypeBaseID_Index_AM_HandlerDoltgresTypeBaseID_TSM_HandlerDoltgresTypeBaseID_RecordDoltgresTypeBaseID_TriggerDoltgresTypeBaseID_Event_TriggerDoltgresTypeBaseID_PG_DDL_CommandDoltgresTypeBaseID_VoidDoltgresTypeBaseID_UnknownDoltgresTypeBaseID_Int16SerialDoltgresTypeBaseID_Int32SerialDoltgresTypeBaseID_Int64SerialDoltgresTypeBaseID_RegclassDoltgresTypeBaseID_RegcollationDoltgresTypeBaseID_RegconfigDoltgresTypeBaseID_RegdictionaryDoltgresTypeBaseID_RegnamespaceDoltgresTypeBaseID_RegoperDoltgresTypeBaseID_RegoperatorDoltgresTypeBaseID_RegprocDoltgresTypeBaseID_RegprocedureDoltgresTypeBaseID_RegroleDoltgresTypeBaseID_Regtype"

var _DoltgresTypeBaseID_map = map[DoltgresTypeBaseID]string{
	3:    _DoltgresTypeBaseID_name[0:23],
	7:    _DoltgresTypeBaseID_name[23:47],
	9:    _DoltgresTypeBaseID_name[47:70],
	15:   _DoltgresTypeBaseID_name[70:93],
	21:   _DoltgresTypeBaseID_name[93:119],
	23:   _DoltgresTypeBaseID_name[119:145],
	27:   _DoltgresTypeBaseID_name[145:169],
	29:   _DoltgresTypeBaseID_name[169:193],
	33:   _DoltgresTypeBaseID_name[193:217],
	37:   _DoltgresTypeBaseID_name[217:244],
	39:   _DoltgresTypeBaseID_name[244:267],
	41:   _DoltgresTypeBaseID_name[267:291],
	53:   _DoltgresTypeBaseID_name[291:314],
	54:   _DoltgresTypeBaseID_name[314:340],
	64:   _DoltgresTypeBaseID_name[340:363],
	66:   _DoltgresTypeBaseID_name[363:386],
	68:   _DoltgresTypeBaseID_name[386:411],
	70:   _DoltgresTypeBaseID_name[411:439],
	74:   _DoltgresTypeBaseID_name[439:469],
	82:   _DoltgresTypeBaseID_name[469:492],
	86:   _DoltgresTypeBaseID_name[492:518],
	90:   _DoltgresTypeBaseID_name[518:541],
	92:   _DoltgresTypeBaseID_name[541:563],
	94:   _DoltgresTypeBaseID_name[563:585],
	96:   _DoltgresTypeBaseID_name[585:616],
	98:   _DoltgresTypeBaseID_name[616:641],
	8192: _DoltgresTypeBaseID_name[641:663],
	8193: _DoltgresTypeBaseID_name[663:692],
	8194: _DoltgresTypeBaseID_name[692:719],
	8195: _DoltgresTypeBaseID_name[719:749],
	8196: _DoltgresTypeBaseID_name[749:775],
	8197: _DoltgresTypeBaseID_name[775:802],
	8198: _DoltgresTypeBaseID_name[802:834],
	8199: _DoltgresTypeBaseID_name[834:866],
	8200: _DoltgresTypeBaseID_name[866:903],
	8201: _DoltgresTypeBaseID_name[903:943],
	8202: _DoltgresTypeBaseID_name[943:980],
	8203: _DoltgresTypeBaseID_name[980:1022],
	8204: _DoltgresTypeBaseID_name[1022:1048],
	8205: _DoltgresTypeBaseID_name[1048:1075],
	8206: _DoltgresTypeBaseID_name[1075:1110],
	8207: _DoltgresTypeBaseID_name[1110:1140],
	8208: _DoltgresTypeBaseID_name[1140:1175],
	8209: _DoltgresTypeBaseID_name[1175:1210],
	8210: _DoltgresTypeBaseID_name[1210:1240],
	8211: _DoltgresTypeBaseID_name[1240:1265],
	8212: _DoltgresTypeBaseID_name[1265:1291],
	8213: _DoltgresTypeBaseID_name[1291:1323],
	8214: _DoltgresTypeBaseID_name[1323:1356],
	8215: _DoltgresTypeBaseID_name[1356:1379],
	8216: _DoltgresTypeBaseID_name[1379:1405],
	8217: _DoltgresTypeBaseID_name[1405:1435],
	8218: _DoltgresTypeBaseID_name[1435:1465],
	8219: _DoltgresTypeBaseID_name[1465:1495],
	8220: _DoltgresTypeBaseID_name[1495:1522],
	8221: _DoltgresTypeBaseID_name[1522:1553],
	8222: _DoltgresTypeBaseID_name[1553:1581],
	8223: _DoltgresTypeBaseID_name[1581:1613],
	8224: _DoltgresTypeBaseID_name[1613:1644],
	8225: _DoltgresTypeBaseID_name[1644:1670],
	8226: _DoltgresTypeBaseID_name[1670:1700],
	8227: _DoltgresTypeBaseID_name[1700:1726],
	8228: _DoltgresTypeBaseID_name[1726:1757],
	8229: _DoltgresTypeBaseID_name[1757:1783],
	8230: _DoltgresTypeBaseID_name[1783:1809],
}

func (i DoltgresTypeBaseID) String() string {
	if str, ok := _DoltgresTypeBaseID_map[i]; ok {
		return str
	}
	return "DoltgresTypeBaseID(" + strconv.FormatInt(int64(i), 10) + ")"
}
