// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package privilege

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALL-1]
	_ = x[SELECT-2]
	_ = x[INSERT-3]
	_ = x[UPDATE-4]
	_ = x[DELETE-5]
	_ = x[TRUNCATE-6]
	_ = x[REFERENCES-7]
	_ = x[TRIGGER-8]
	_ = x[CREATE-9]
	_ = x[CONNECT-10]
	_ = x[TEMPORARY-11]
	_ = x[EXECUTE-12]
	_ = x[USAGE-13]
	_ = x[SET-14]
	_ = x[ALTERSYSTEM-15]
	_ = x[DROP-16]
}

const _Kind_name = "ALLSELECTINSERTUPDATEDELETETRUNCATEREFERENCESTRIGGERCREATECONNECTTEMPORARYEXECUTEUSAGESETALTERSYSTEMDROP"

var _Kind_index = [...]uint8{0, 3, 9, 15, 21, 27, 35, 45, 52, 58, 65, 74, 81, 86, 89, 100, 104}

func (i Kind) String() string {
	i -= 1
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
