// This file is @generated by prost-build.
/// RepoId is how repositories are represented on dolthub, for example
/// `dolthub/us-housing-prices-v2` has org = dolthub, repo_name =
/// us-housing-prices-v2.
///
/// All methods of ChunkStoreService targeting a repository take a RepoId. Many
/// will also take a `repo_token`, which can be provided in addition to a
/// RepoId. `repo_token`s can be returned from repository-accessing RPCs on
/// ChunkStoreService, and providing them instead of RepoId for future calls to
/// ChunkStoreService can be more efficient than providing RepoId itself.
/// `repo_token`s are fully opaque to the client.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepoId {
    #[prost(string, tag = "1")]
    pub org: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub repo_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HasChunksRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "3")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HasChunksResponse {
    #[prost(int32, repeated, tag = "1")]
    pub absent: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpGetChunk {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RangeChunk {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint32, tag = "3")]
    pub length: u32,
    /// Archive zStd dictionary spans are indicated with these fields. On the consumer side, the existence
    /// of a non-zero dictionary length indicates that the chunk is compressed using zStd. This implies that
    /// the chunkSource is an archive source. If the dictionary length is zero, the chunk is compressed using snappy
    /// compression (classic NOMS table file or journal chunk use snappy compression).
    #[prost(uint64, tag = "4")]
    pub dictionary_offset: u64,
    #[prost(uint32, tag = "5")]
    pub dictionary_length: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpGetRange {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub ranges: ::prost::alloc::vec::Vec<RangeChunk>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadLoc {
    #[prost(message, optional, tag = "3")]
    pub refresh_after: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub refresh_request: ::core::option::Option<RefreshTableFileUrlRequest>,
    #[prost(oneof = "download_loc::Location", tags = "1, 2")]
    pub location: ::core::option::Option<download_loc::Location>,
}
/// Nested message and enum types in `DownloadLoc`.
pub mod download_loc {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Location {
        #[prost(message, tag = "1")]
        HttpGet(super::HttpGetChunk),
        #[prost(message, tag = "2")]
        HttpGetRange(super::HttpGetRange),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpPostTableFile {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadLoc {
    #[prost(bytes = "vec", tag = "1")]
    pub table_file_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "upload_loc::Location", tags = "2")]
    pub location: ::core::option::Option<upload_loc::Location>,
}
/// Nested message and enum types in `UploadLoc`.
pub mod upload_loc {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Location {
        #[prost(message, tag = "2")]
        HttpPost(super::HttpPostTableFile),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDownloadLocsRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub chunk_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "3")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo_path: ::prost::alloc::string::String,
    /// Capabilities the calling client declares about itself. See the
    /// ClientCapability enum. Populated by the client on every outbound
    /// request; absent means "not capable."
    #[prost(enumeration = "ClientCapability", repeated, tag = "5")]
    pub client_capabilities: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDownloadLocsResponse {
    #[prost(message, repeated, tag = "1")]
    pub locs: ::prost::alloc::vec::Vec<DownloadLoc>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamChunkLocationsRequest {
    /// Every request must populate RepoId/repo_token/repo_path on the
    /// wire. This matches what the current StreamDownloadLocations
    /// client already does and is load-bearing for retry correctness:
    /// the reliable-RPC layer may tear down the underlying gRPC stream
    /// and replay any unacked requests against a freshly opened stream,
    /// so the server must never need prior in-stream state to interpret
    /// a request.
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_path: ::prost::alloc::string::String,
    /// Flat, packed buffer of 20-byte chunk hashes: hash N occupies
    /// bytes \[N*20 : (N+1)*20\]. Not a |repeated bytes| because every
    /// element is exactly 20 bytes and the 2-byte per-element
    /// tag/length overhead of |repeated bytes| is ~10% of the whole
    /// request in a 512-hash batch. Servers MUST reject requests
    /// where len(chunk_hashes) is not a multiple of 20.
    #[prost(bytes = "vec", tag = "4")]
    pub chunk_hashes: ::prost::alloc::vec::Vec<u8>,
    /// Stream-scoped. The client's capability set does not change
    /// within a single server-side stream. Today every request on
    /// the stream MUST carry the full set (same rule as
    /// repo_id/token/path above); the reliable-RPC layer relies on
    /// this for replay correctness. A future protocol revision may
    /// allow omitting it after the first message; servers MUST
    /// continue to accept it on every message.
    #[prost(enumeration = "ClientCapability", repeated, tag = "5")]
    pub client_capabilities: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamChunkLocationsResponse {
    /// If non-empty, advertises a new repo_token that the client should
    /// use on future requests on this service.
    #[prost(string, tag = "1")]
    pub repo_token: ::prost::alloc::string::String,
    /// Zero or more table-file records introduced by this response.
    /// Valid for the remainder of this server-side stream. Clients MUST
    /// integrate these into their table_file_id map (inserting or
    /// overwriting) before resolving any |locations| in this same
    /// response.
    #[prost(message, repeated, tag = "2")]
    pub table_files: ::prost::alloc::vec::Vec<
        stream_chunk_locations_response::TableFileRecord,
    >,
    /// Chunk locations for the hashes in the corresponding request.
    /// Response ordering is 1:1 with requests.
    #[prost(message, repeated, tag = "3")]
    pub locations: ::prost::alloc::vec::Vec<
        stream_chunk_locations_response::ChunkLocation,
    >,
    /// Hash indices into the corresponding request's chunk_hashes
    /// buffer that the server could not find: a value of N here means
    /// the N'th 20-byte hash (bytes \[N*20 : (N+1)*20\]) was not found.
    /// Not a byte offset. Sent explicitly so the client does not have
    /// to diff requested vs. returned.
    #[prost(uint32, repeated, tag = "4")]
    pub missing_indexes: ::prost::alloc::vec::Vec<u32>,
}
/// Nested message and enum types in `StreamChunkLocationsResponse`.
pub mod stream_chunk_locations_response {
    /// TableFileRecord and ChunkLocation are nested inside the response
    /// rather than free-standing at package level. Their invariants
    /// (table_file_id is stream-scoped; request_index is scoped to one
    /// request's chunk_hashes) only hold in the context of this
    /// response.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TableFileRecord {
        /// Opaque id assigned by the server, scoped to the current
        /// server-side stream. The server MUST emit a TableFileRecord
        /// for any id on its first use within a given server-side
        /// stream, before (or in the same response as) any
        /// ChunkLocation that references the id. Clients MUST overwrite
        /// any prior entry for the same id when a new TableFileRecord
        /// arrives.
        #[prost(uint32, tag = "1")]
        pub table_file_id: u32,
        /// Signed URL the client should issue byte-range requests
        /// against.
        #[prost(string, tag = "2")]
        pub url: ::prost::alloc::string::String,
        /// When the client should consider |url| stale and call
        /// RefreshTableFileUrl.
        #[prost(message, optional, tag = "3")]
        pub refresh_after: ::core::option::Option<::prost_types::Timestamp>,
        /// The file_id to use when calling RefreshTableFileUrl. All the
        /// other fields of RefreshTableFileUrlRequest (repo_id,
        /// repo_token, repo_path) are already known to the client.
        #[prost(string, tag = "4")]
        pub file_id: ::prost::alloc::string::String,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct ChunkLocation {
        /// Refers to a TableFileRecord.table_file_id introduced in the
        /// current server-side stream -- either in an earlier response
        /// message on this same stream, or in the same response message
        /// as this ChunkLocation.
        #[prost(uint32, tag = "1")]
        pub table_file_id: u32,
        /// Hash index into the corresponding request's chunk_hashes
        /// buffer: a value of N refers to the N'th 20-byte hash, i.e.
        /// bytes \[N*20 : (N+1)*20\]. Not a byte offset. Avoids
        /// re-transmitting the 20-byte hash on the wire.
        #[prost(uint32, tag = "2")]
        pub request_index: u32,
        #[prost(uint64, tag = "3")]
        pub offset: u64,
        #[prost(uint32, tag = "4")]
        pub length: u32,
        /// zStd dictionary span within the same table file. Same
        /// semantics as the existing RangeChunk.dictionary_{offset,length}.
        #[prost(uint64, tag = "5")]
        pub dictionary_offset: u64,
        #[prost(uint32, tag = "6")]
        pub dictionary_length: u32,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableFileDetails {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub content_length: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub content_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub num_chunks: u64,
    #[prost(string, tag = "5")]
    pub suffix: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub split_offset: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUploadLocsRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[deprecated]
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub table_file_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "3")]
    pub table_file_details: ::prost::alloc::vec::Vec<TableFileDetails>,
    #[prost(string, tag = "4")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUploadLocsResponse {
    #[prost(message, repeated, tag = "1")]
    pub locs: ::prost::alloc::vec::Vec<UploadLoc>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RebaseRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RebaseResponse {
    #[prost(string, tag = "1")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RootRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RootResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChunkTableInfo {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub chunk_count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(bytes = "vec", tag = "2")]
    pub current: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub last: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "4")]
    pub chunk_table_info: ::prost::alloc::vec::Vec<ChunkTableInfo>,
    #[prost(message, optional, tag = "14")]
    pub client_repo_format: ::core::option::Option<ClientRepoFormat>,
    #[prost(string, tag = "5")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CommitResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRepoMetadataRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(message, optional, tag = "14")]
    pub client_repo_format: ::core::option::Option<ClientRepoFormat>,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRepoMetadataResponse {
    /// Version string of the noms binary format for this repository.
    /// See types.NomsBinFormat.
    #[prost(string, tag = "1")]
    pub nbf_version: ::prost::alloc::string::String,
    /// Version string of the nbs format of this repository.
    /// See nbs.StorageVersion.
    #[prost(string, tag = "2")]
    pub nbs_version: ::prost::alloc::string::String,
    /// Approximate number of bytes required for storage of all
    /// currently-referenced repository table files.
    #[prost(uint64, tag = "3")]
    pub storage_size: u64,
    #[prost(string, tag = "4")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(enumeration = "PushConcurrencyControl", tag = "5")]
    pub push_concurrency_control: i32,
    /// Optional capability flags advertised by the server. See the
    /// Feature enum above. Order is not significant; duplicates
    /// should be treated the same as a single occurrence.
    #[prost(enumeration = "Feature", repeated, tag = "6")]
    pub features: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientRepoFormat {
    #[prost(string, tag = "1")]
    pub nbf_version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub nbs_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTableFilesRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[deprecated]
    #[prost(bool, tag = "2")]
    pub appendix_only: bool,
    #[prost(string, tag = "3")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo_path: ::prost::alloc::string::String,
    /// Capabilities the calling client declares about itself. See the
    /// ClientCapability enum. Populated by the client on every outbound
    /// request; absent means "not capable."
    #[prost(enumeration = "ClientCapability", repeated, tag = "5")]
    pub client_capabilities: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableFileInfo {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub num_chunks: u32,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub refresh_after: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub refresh_request: ::core::option::Option<RefreshTableFileUrlRequest>,
    #[prost(uint64, tag = "6")]
    pub split_offset: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTableFileUrlRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(string, tag = "2")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo_path: ::prost::alloc::string::String,
    /// Capabilities the calling client declares about itself. See the
    /// ClientCapability enum. The client stamps this field at send
    /// time on every outbound request, including when it is sending
    /// a RefreshTableFileUrlRequest that the server previously
    /// prebuilt and embedded in a response (see TableFileInfo and
    /// DownloadLoc). Servers constructing prebuilt refresh requests
    /// SHOULD leave this field unset; the client overwrites it.
    #[prost(enumeration = "ClientCapability", repeated, tag = "5")]
    pub client_capabilities: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTableFileUrlResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub refresh_after: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "3")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTableFilesResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "2")]
    pub table_file_info: ::prost::alloc::vec::Vec<TableFileInfo>,
    #[prost(message, repeated, tag = "3")]
    pub appendix_table_file_info: ::prost::alloc::vec::Vec<TableFileInfo>,
    #[prost(string, tag = "4")]
    pub repo_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddTableFilesRequest {
    #[prost(message, optional, tag = "1")]
    pub repo_id: ::core::option::Option<RepoId>,
    #[prost(message, optional, tag = "2")]
    pub client_repo_format: ::core::option::Option<ClientRepoFormat>,
    #[prost(message, repeated, tag = "3")]
    pub chunk_table_info: ::prost::alloc::vec::Vec<ChunkTableInfo>,
    /// If set, this is a write for the manifest appendix, not just the manifest table file specs.
    /// The table files appearing in `chunk_table_info` are added to `specs` and are also set
    /// in the manifest appendix. If `appendix_option` is `SET`, then the value of the appendix
    /// becomes the full list provided in `chunk_table_info` and any prior specs in the appendix
    /// are removed from the manifest specs. If `append_option` is `APPEND`, then the
    /// supplied table files are added to the appendix and to specs.
    #[prost(enumeration = "ManifestAppendixOption", tag = "4")]
    pub appendix_option: i32,
    #[prost(string, tag = "5")]
    pub repo_token: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub repo_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddTableFilesResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub repo_token: ::prost::alloc::string::String,
}
/// A ChunkStore can request a client to implement a specific concurrency
/// control mechanism when updating a branch HEAD.
///
/// This exists because passive remotes, like DoltHub, typically do not have
/// meaningful workingSets. When a client requests to push a branch HEAD to a
/// DoltHub remote, they have no visibility into the workingSet/ value for the
/// corresponding branch. It has historically been the case that clients ignore
/// it and just push the branch HEAD.
///
/// On the other hand, when pushing to a running sql-server, not stomping
/// concurrent transaction is important, and the remote endpoint will want the
/// pushing client to ensure that it both checks that the branch's working set
/// is clean and that it updates the branch's working set appropriately if the
/// push is successful.
///
/// Servers advertise which concurrency control mechanism they want in their
/// GetRepoMetadataResponse.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PushConcurrencyControl {
    Unspecified = 0,
    IgnoreWorkingSet = 1,
    AssertWorkingSet = 2,
}
impl PushConcurrencyControl {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PUSH_CONCURRENCY_CONTROL_UNSPECIFIED",
            Self::IgnoreWorkingSet => "PUSH_CONCURRENCY_CONTROL_IGNORE_WORKING_SET",
            Self::AssertWorkingSet => "PUSH_CONCURRENCY_CONTROL_ASSERT_WORKING_SET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PUSH_CONCURRENCY_CONTROL_UNSPECIFIED" => Some(Self::Unspecified),
            "PUSH_CONCURRENCY_CONTROL_IGNORE_WORKING_SET" => Some(Self::IgnoreWorkingSet),
            "PUSH_CONCURRENCY_CONTROL_ASSERT_WORKING_SET" => Some(Self::AssertWorkingSet),
            _ => None,
        }
    }
}
/// Optional, additive capability flags advertised by the server in
/// GetRepoMetadataResponse.features. Use this for pure "does the
/// server implement X?" booleans. Mode selectors with more than two
/// states (such as the existing PushConcurrencyControl) keep their
/// own typed fields; this list is only for flag-shaped capabilities.
///
/// Guidelines for growth:
/// - Add new values at the end; never reuse a removed value's
///    number. If a feature is retired, reserve its number rather
///    than re-purposing it.
/// - FEATURE_UNSPECIFIED = 0 is never sent; presence of the zero
///    value in a received list should be ignored by the client.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Feature {
    Unspecified = 0,
    /// Server implements the StreamChunkLocations RPC. Clients should
    /// prefer it to StreamDownloadLocations when this feature is
    /// present.
    StreamChunkLocations = 1,
}
impl Feature {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FEATURE_UNSPECIFIED",
            Self::StreamChunkLocations => "FEATURE_STREAM_CHUNK_LOCATIONS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FEATURE_UNSPECIFIED" => Some(Self::Unspecified),
            "FEATURE_STREAM_CHUNK_LOCATIONS" => Some(Self::StreamChunkLocations),
            _ => None,
        }
    }
}
/// Capabilities the client declares about itself on every request
/// that the server may use to select alternative URL endpoints,
/// wire encodings, or response shapes. Missing value => not capable.
/// Servers SHOULD continue to serve clients that send no
/// capabilities; capability-gated behaviors are intended as
/// optional upgrades, not correctness boundaries.
///
/// Populated by the client at send time. Servers that construct
/// prebuilt RefreshTableFileUrlRequest messages for echo-style
/// responses (see ListTableFiles, GetDownloadLocations) SHOULD
/// leave this field unset; the sending client overwrites it.
///
/// Guidelines for growth:
/// - Add new values at the end; never reuse a removed value's
///    number. Reserve retired numbers rather than repurposing them.
/// - CLIENT_CAPABILITY_UNSPECIFIED = 0 is never sent; presence of
///    the zero value in a received list should be ignored.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClientCapability {
    Unspecified = 0,
    /// The client's HTTP fetcher correctly handles HTTP/2 response
    /// bodies for chunk and table-file downloads. Servers MAY return
    /// signed URLs that resolve to HTTP/2 endpoints (e.g. CDN-fronted
    /// hosts) when this is set. When this is not set, servers SHOULD
    /// prefer URLs that resolve to HTTP/1.1 endpoints if such a
    /// choice is available. Servers without a separate HTTP/1.1
    /// option may return whatever URL they have; old clients
    /// generally succeed against HTTP/2 URLs but can see degraded
    /// performance under certain network conditions.
    Http2Download = 1,
}
impl ClientCapability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CLIENT_CAPABILITY_UNSPECIFIED",
            Self::Http2Download => "CLIENT_CAPABILITY_HTTP2_DOWNLOAD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CLIENT_CAPABILITY_UNSPECIFIED" => Some(Self::Unspecified),
            "CLIENT_CAPABILITY_HTTP2_DOWNLOAD" => Some(Self::Http2Download),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ManifestAppendixOption {
    Unspecified = 0,
    Set = 1,
    Append = 2,
}
impl ManifestAppendixOption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MANIFEST_APPENDIX_OPTION_UNSPECIFIED",
            Self::Set => "MANIFEST_APPENDIX_OPTION_SET",
            Self::Append => "MANIFEST_APPENDIX_OPTION_APPEND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MANIFEST_APPENDIX_OPTION_UNSPECIFIED" => Some(Self::Unspecified),
            "MANIFEST_APPENDIX_OPTION_SET" => Some(Self::Set),
            "MANIFEST_APPENDIX_OPTION_APPEND" => Some(Self::Append),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod chunk_store_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ChunkStoreServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ChunkStoreServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ChunkStoreServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ChunkStoreServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ChunkStoreServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_repo_metadata(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRepoMetadataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRepoMetadataResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/GetRepoMetadata",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "GetRepoMetadata",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn has_chunks(
            &mut self,
            request: impl tonic::IntoRequest<super::HasChunksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasChunksResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/HasChunks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "HasChunks",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get the download locations for a list of chunk hashes.
        /// Deprecated. Use StreamDownloadLocations.
        pub async fn get_download_locations(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDownloadLocsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDownloadLocsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/GetDownloadLocations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "GetDownloadLocations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get the download locations for a list of chunk hashes. Streaming to
        /// support large and incrementally available payloads. Results are generated
        /// as requests come in.
        ///
        /// Deprecated: prefer StreamChunkLocations, which deduplicates
        /// table-file metadata across the stream. Kept on the wire
        /// indefinitely so old clients continue to work.
        pub async fn stream_download_locations(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::GetDownloadLocsRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GetDownloadLocsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/StreamDownloadLocations",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "StreamDownloadLocations",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Get the download locations for a list of chunk hashes. Streaming
        /// variant that deduplicates table-file metadata across the stream.
        /// Preferred over StreamDownloadLocations when the server advertises
        /// FEATURE_STREAM_CHUNK_LOCATIONS in GetRepoMetadataResponse.features.
        pub async fn stream_chunk_locations(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::StreamChunkLocationsRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<super::StreamChunkLocationsResponse>,
            >,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/StreamChunkLocations",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "StreamChunkLocations",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Get upload locations for a list of table file hashes.
        /// NOTE: We upload full table files but download individual chunks.
        pub async fn get_upload_locations(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUploadLocsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUploadLocsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/GetUploadLocations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "GetUploadLocations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn rebase(
            &mut self,
            request: impl tonic::IntoRequest<super::RebaseRequest>,
        ) -> std::result::Result<tonic::Response<super::RebaseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/Rebase",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "Rebase",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn root(
            &mut self,
            request: impl tonic::IntoRequest<super::RootRequest>,
        ) -> std::result::Result<tonic::Response<super::RootResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/Root",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "Root",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn commit(
            &mut self,
            request: impl tonic::IntoRequest<super::CommitRequest>,
        ) -> std::result::Result<tonic::Response<super::CommitResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/Commit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "Commit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_table_files(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTableFilesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTableFilesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/ListTableFiles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "ListTableFiles",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn refresh_table_file_url(
            &mut self,
            request: impl tonic::IntoRequest<super::RefreshTableFileUrlRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshTableFileUrlResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/RefreshTableFileUrl",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "RefreshTableFileUrl",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_table_files(
            &mut self,
            request: impl tonic::IntoRequest<super::AddTableFilesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddTableFilesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/AddTableFiles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.ChunkStoreService",
                        "AddTableFiles",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod chunk_store_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ChunkStoreServiceServer.
    #[async_trait]
    pub trait ChunkStoreService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_repo_metadata(
            &self,
            request: tonic::Request<super::GetRepoMetadataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRepoMetadataResponse>,
            tonic::Status,
        >;
        async fn has_chunks(
            &self,
            request: tonic::Request<super::HasChunksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasChunksResponse>,
            tonic::Status,
        >;
        /// Get the download locations for a list of chunk hashes.
        /// Deprecated. Use StreamDownloadLocations.
        async fn get_download_locations(
            &self,
            request: tonic::Request<super::GetDownloadLocsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDownloadLocsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamDownloadLocations method.
        type StreamDownloadLocationsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::GetDownloadLocsResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Get the download locations for a list of chunk hashes. Streaming to
        /// support large and incrementally available payloads. Results are generated
        /// as requests come in.
        ///
        /// Deprecated: prefer StreamChunkLocations, which deduplicates
        /// table-file metadata across the stream. Kept on the wire
        /// indefinitely so old clients continue to work.
        async fn stream_download_locations(
            &self,
            request: tonic::Request<tonic::Streaming<super::GetDownloadLocsRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamDownloadLocationsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamChunkLocations method.
        type StreamChunkLocationsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::StreamChunkLocationsResponse,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        /// Get the download locations for a list of chunk hashes. Streaming
        /// variant that deduplicates table-file metadata across the stream.
        /// Preferred over StreamDownloadLocations when the server advertises
        /// FEATURE_STREAM_CHUNK_LOCATIONS in GetRepoMetadataResponse.features.
        async fn stream_chunk_locations(
            &self,
            request: tonic::Request<tonic::Streaming<super::StreamChunkLocationsRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamChunkLocationsStream>,
            tonic::Status,
        >;
        /// Get upload locations for a list of table file hashes.
        /// NOTE: We upload full table files but download individual chunks.
        async fn get_upload_locations(
            &self,
            request: tonic::Request<super::GetUploadLocsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUploadLocsResponse>,
            tonic::Status,
        >;
        async fn rebase(
            &self,
            request: tonic::Request<super::RebaseRequest>,
        ) -> std::result::Result<tonic::Response<super::RebaseResponse>, tonic::Status>;
        async fn root(
            &self,
            request: tonic::Request<super::RootRequest>,
        ) -> std::result::Result<tonic::Response<super::RootResponse>, tonic::Status>;
        async fn commit(
            &self,
            request: tonic::Request<super::CommitRequest>,
        ) -> std::result::Result<tonic::Response<super::CommitResponse>, tonic::Status>;
        async fn list_table_files(
            &self,
            request: tonic::Request<super::ListTableFilesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTableFilesResponse>,
            tonic::Status,
        >;
        async fn refresh_table_file_url(
            &self,
            request: tonic::Request<super::RefreshTableFileUrlRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshTableFileUrlResponse>,
            tonic::Status,
        >;
        async fn add_table_files(
            &self,
            request: tonic::Request<super::AddTableFilesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddTableFilesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ChunkStoreServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ChunkStoreServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ChunkStoreServiceServer<T>
    where
        T: ChunkStoreService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/GetRepoMetadata" => {
                    #[allow(non_camel_case_types)]
                    struct GetRepoMetadataSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::GetRepoMetadataRequest>
                    for GetRepoMetadataSvc<T> {
                        type Response = super::GetRepoMetadataResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRepoMetadataRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::get_repo_metadata(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRepoMetadataSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/HasChunks" => {
                    #[allow(non_camel_case_types)]
                    struct HasChunksSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::HasChunksRequest>
                    for HasChunksSvc<T> {
                        type Response = super::HasChunksResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HasChunksRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::has_chunks(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HasChunksSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/GetDownloadLocations" => {
                    #[allow(non_camel_case_types)]
                    struct GetDownloadLocationsSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::GetDownloadLocsRequest>
                    for GetDownloadLocationsSvc<T> {
                        type Response = super::GetDownloadLocsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetDownloadLocsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::get_download_locations(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDownloadLocationsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/StreamDownloadLocations" => {
                    #[allow(non_camel_case_types)]
                    struct StreamDownloadLocationsSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::StreamingService<super::GetDownloadLocsRequest>
                    for StreamDownloadLocationsSvc<T> {
                        type Response = super::GetDownloadLocsResponse;
                        type ResponseStream = T::StreamDownloadLocationsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::GetDownloadLocsRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::stream_download_locations(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamDownloadLocationsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/StreamChunkLocations" => {
                    #[allow(non_camel_case_types)]
                    struct StreamChunkLocationsSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::StreamingService<super::StreamChunkLocationsRequest>
                    for StreamChunkLocationsSvc<T> {
                        type Response = super::StreamChunkLocationsResponse;
                        type ResponseStream = T::StreamChunkLocationsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::StreamChunkLocationsRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::stream_chunk_locations(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamChunkLocationsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/GetUploadLocations" => {
                    #[allow(non_camel_case_types)]
                    struct GetUploadLocationsSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::GetUploadLocsRequest>
                    for GetUploadLocationsSvc<T> {
                        type Response = super::GetUploadLocsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUploadLocsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::get_upload_locations(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUploadLocationsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/Rebase" => {
                    #[allow(non_camel_case_types)]
                    struct RebaseSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::RebaseRequest>
                    for RebaseSvc<T> {
                        type Response = super::RebaseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RebaseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::rebase(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RebaseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/Root" => {
                    #[allow(non_camel_case_types)]
                    struct RootSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::RootRequest> for RootSvc<T> {
                        type Response = super::RootResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RootRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::root(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RootSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/Commit" => {
                    #[allow(non_camel_case_types)]
                    struct CommitSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::CommitRequest>
                    for CommitSvc<T> {
                        type Response = super::CommitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CommitRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::commit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CommitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/ListTableFiles" => {
                    #[allow(non_camel_case_types)]
                    struct ListTableFilesSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::ListTableFilesRequest>
                    for ListTableFilesSvc<T> {
                        type Response = super::ListTableFilesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListTableFilesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::list_table_files(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListTableFilesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/RefreshTableFileUrl" => {
                    #[allow(non_camel_case_types)]
                    struct RefreshTableFileUrlSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::RefreshTableFileUrlRequest>
                    for RefreshTableFileUrlSvc<T> {
                        type Response = super::RefreshTableFileUrlResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RefreshTableFileUrlRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::refresh_table_file_url(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RefreshTableFileUrlSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dolt.services.remotesapi.v1alpha1.ChunkStoreService/AddTableFiles" => {
                    #[allow(non_camel_case_types)]
                    struct AddTableFilesSvc<T: ChunkStoreService>(pub Arc<T>);
                    impl<
                        T: ChunkStoreService,
                    > tonic::server::UnaryService<super::AddTableFilesRequest>
                    for AddTableFilesSvc<T> {
                        type Response = super::AddTableFilesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddTableFilesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChunkStoreService>::add_table_files(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddTableFilesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ChunkStoreServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "dolt.services.remotesapi.v1alpha1.ChunkStoreService";
    impl<T> tonic::server::NamedService for ChunkStoreServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WhoAmIRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhoAmIResponse {
    /// Ex: "bheni"
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// Ex: "Brian Hendriks"
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    /// Ex: "brian@liquidata.co"
    #[prost(string, tag = "3")]
    pub email_address: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod credentials_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CredentialsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CredentialsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CredentialsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CredentialsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CredentialsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn who_am_i(
            &mut self,
            request: impl tonic::IntoRequest<super::WhoAmIRequest>,
        ) -> std::result::Result<tonic::Response<super::WhoAmIResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dolt.services.remotesapi.v1alpha1.CredentialsService/WhoAmI",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dolt.services.remotesapi.v1alpha1.CredentialsService",
                        "WhoAmI",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod credentials_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CredentialsServiceServer.
    #[async_trait]
    pub trait CredentialsService: std::marker::Send + std::marker::Sync + 'static {
        async fn who_am_i(
            &self,
            request: tonic::Request<super::WhoAmIRequest>,
        ) -> std::result::Result<tonic::Response<super::WhoAmIResponse>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct CredentialsServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CredentialsServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CredentialsServiceServer<T>
    where
        T: CredentialsService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/dolt.services.remotesapi.v1alpha1.CredentialsService/WhoAmI" => {
                    #[allow(non_camel_case_types)]
                    struct WhoAmISvc<T: CredentialsService>(pub Arc<T>);
                    impl<
                        T: CredentialsService,
                    > tonic::server::UnaryService<super::WhoAmIRequest>
                    for WhoAmISvc<T> {
                        type Response = super::WhoAmIResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WhoAmIRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CredentialsService>::who_am_i(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WhoAmISvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CredentialsServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "dolt.services.remotesapi.v1alpha1.CredentialsService";
    impl<T> tonic::server::NamedService for CredentialsServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
