// Copyright 2026 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

mod common;

use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

use common::*;
use driver::client::Db;
use driver::model::Server;
use rand::Rng;

const TABLES: [&str; 10] = ["t0", "t1", "t2", "t3", "t4", "t5", "t6", "t7", "t8", "t9"];
const COLUMNS: [&str; 10] = ["c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9"];

/// create_table_sql returns a CREATE TABLE with an identity key and ten unique bigint columns.
fn create_table_sql(table: &str) -> String {
    let defs: Vec<String> = COLUMNS.iter().map(|col| format!("{col} bigint unique")).collect();
    [
        format!("CREATE TABLE {table} ("),
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,".to_string(),
        defs.join(",\n"),
        ");".to_string(),
    ]
    .join("\n")
}

/// t0_values_str returns a row of eleven random values below 2^48.
fn t0_values_str() -> String {
    let mut rng = rand::thread_rng();
    let values: Vec<String> = (0..11).map(|_| rng.gen_range(0..1i64 << 48).to_string()).collect();
    format!("({})", values.join(", "))
}

/// t0_values_strs returns n random rows.
fn t0_values_strs(n: usize) -> String {
    (0..n).map(|_| t0_values_str()).collect::<Vec<_>>().join(",")
}

/// run_queries checks out a random branch and reads a join of two random tables.
fn run_queries(conn: &mut Db, branches: &[String]) -> Result<(), String> {
    let mut rng = rand::thread_rng();
    let branch = &branches[rng.gen_range(0..branches.len())];
    conn.exec(&format!("select dolt_checkout('{branch}')"), &[])?;
    let t1 = TABLES[rng.gen_range(0..TABLES.len())];
    let mut t2 = TABLES[rng.gen_range(0..TABLES.len())];
    while t2 == t1 {
        t2 = TABLES[rng.gen_range(0..TABLES.len())];
    }
    let c1 = COLUMNS[rng.gen_range(0..COLUMNS.len())];
    let c2 = COLUMNS[rng.gen_range(0..COLUMNS.len())];
    conn.query_values(&format!("select * from {t1} join {t2} on {t1}.{c1} = {t2}.{c2}"), &[])?;
    Ok(())
}

#[test]
#[ignore = "dolt_stats_gc() is unsupported in Doltgres (statistics provider does not implement ExtendedStatsProvider)"]
fn test_stats_gc_concurrency() {
    let mut env = env();
    start_server(
        &mut env,
        "stats_gc_concurrency_test",
        Server { dynamic_port: "server".into(), ..Server::default() },
        None,
    );
    let mut db = db(&mut env);
    let mut branches = vec!["main".to_string()];
    branches.extend((0..3).map(|_| uuid::Uuid::new_v4().to_string()));
    for table in TABLES {
        exec(&mut db, &create_table_sql(table), &[]);
    }
    exec(&mut db, "select dolt_commit('-Am', 'initial commit')", &[]);
    for branch in &branches[1..] {
        exec(&mut db, &format!("select dolt_checkout('-b', '{branch}')"), &[]);
        for table in TABLES {
            exec(&mut db, &format!("insert into {table} values {}", t0_values_str()), &[]);
        }
    }
    exec(&mut db, "select dolt_checkout('main')", &[]);
    for table in TABLES {
        exec(&mut db, &format!("insert into {table} values {}", t0_values_str()), &[]);
    }

    const NUM_THREADS: usize = 10;
    let mut workers: Vec<Db> = (0..NUM_THREADS).map(|_| common::db(&mut env)).collect();
    let mut gc_conn = common::db(&mut env);
    let stop = AtomicBool::new(false);
    let mut gc_duration = Duration::ZERO;
    let results: Vec<Result<Duration, String>> = std::thread::scope(|scope| {
        let handles: Vec<_> = workers
            .iter_mut()
            .map(|conn| {
                let (stop, branches) = (&stop, &branches);
                scope.spawn(move || -> Result<Duration, String> {
                    let mut max_query = Duration::ZERO;
                    while !stop.load(Ordering::SeqCst) {
                        let start = Instant::now();
                        let result = run_queries(conn, branches);
                        max_query = max_query.max(start.elapsed());
                        if let Err(e) = result {
                            stop.store(true, Ordering::SeqCst);
                            return Err(e);
                        }
                    }
                    Ok(max_query)
                })
            })
            .collect();
        let start = Instant::now();
        let gc = gc_conn.exec("select dolt_stats_gc()", &[]);
        gc_duration = start.elapsed();
        stop.store(true, Ordering::SeqCst);
        let mut results: Vec<Result<Duration, String>> = handles.into_iter().map(|h| h.join().unwrap()).collect();
        results.push(gc.map(|_| Duration::ZERO));
        results
    });
    let max_queries: Vec<Duration> = results.into_iter().map(Result::unwrap).collect();
    let failures: Vec<String> = max_queries[..NUM_THREADS]
        .iter()
        .filter(|d| **d >= Duration::from_secs(3) || **d >= gc_duration)
        .map(|d| format!("query took {d:?} with a stats GC of {gc_duration:?}"))
        .collect();
    assert!(failures.is_empty(), "{}", failures.join("\n"));
    drop(workers);
    finish(env);
}

#[test]
#[ignore = "dolt_stats_timers() is unsupported in Doltgres"]
fn test_stats_analyze_table_speed() {
    let mut env = env();
    start_server(
        &mut env,
        "stats_analyze_table_test",
        Server { dynamic_port: "server".into(), ..Server::default() },
        None,
    );
    let mut db = db(&mut env);
    exec(&mut db, "select dolt_stats_timers(60000000000, 60000000000)", &[]);
    exec(&mut db, &create_table_sql("t0"), &[]);
    exec(&mut db, "select dolt_commit('-Am', 'initial commit')", &[]);
    exec(&mut db, "select dolt_checkout('main')", &[]);
    exec(&mut db, &format!("insert into t0 values {}", t0_values_strs(65536)), &[]);
    let start = Instant::now();
    exec(&mut db, "ANALYZE t0", &[]);
    assert!(start.elapsed() < Duration::from_secs(30), "ANALYZE took {:?}", start.elapsed());
    finish(env);
}
