// Copyright 2023 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ast

import (
	"fmt"

	vitess "github.com/dolthub/vitess/go/vt/sqlparser"

	"github.com/dolthub/doltgresql/postgres/parser/sem/tree"
)

// nodeSetVar handles *tree.SetVar nodes.
func nodeSetVar(node *tree.SetVar) (vitess.Statement, error) {
	if node == nil {
		return nil, nil
	}
	if _, ok := pgCfgVars[node.Name]; !ok {
		return nil, fmt.Errorf(`ERROR: syntax error at or near "%s"'`, node.Name)
	}
	if node.IsLocal {
		// TODO: takes effect for only the current transaction rather than the current session.
		return nil, fmt.Errorf("SET LOCAL is not yet supported")
	}
	expr, err := nodeExpr(node.Values[0])
	if err != nil {
		return nil, err
	}
	setStmt := &vitess.Set{
		Exprs: vitess.SetVarExprs{&vitess.SetVarExpr{
			Scope: vitess.SetScope_Session, // TODO: always SESSION scope until we support LOCAL scope
			Name: &vitess.ColName{
				Name: vitess.NewColIdent(node.Name),
				Qualifier: vitess.TableName{
					Name:      vitess.NewTableIdent("postgres"),
					Qualifier: vitess.NewTableIdent(""),
				},
			},
			Expr: expr,
		}},
	}
	return setStmt, nil
}

// pgCfgVars is a list of configuration parameters that can be used in SET statement.
// All parameters are in lower-case.
var pgCfgVars = map[string]struct{}{
	"allow_in_place_tablespaces":                  {},
	"allow_system_table_mods":                     {},
	"application_name":                            {},
	"archive_cleanup_command":                     {},
	"archive_command":                             {},
	"archive_library":                             {},
	"archive_mode":                                {},
	"archive_timeout":                             {},
	"array_nulls":                                 {},
	"authentication_timeout":                      {},
	"autovacuum":                                  {},
	"autovacuum_analyze_scale_factor":             {},
	"autovacuum_analyze_threshold":                {},
	"autovacuum_freeze_max_age":                   {},
	"autovacuum_max_workers":                      {},
	"autovacuum_multixact_freeze_max_age":         {},
	"autovacuum_naptime":                          {},
	"autovacuum_vacuum_cost_delay":                {},
	"autovacuum_vacuum_cost_limit":                {},
	"autovacuum_vacuum_insert_scale_factor":       {},
	"autovacuum_vacuum_insert_threshold":          {},
	"autovacuum_vacuum_scale_factor":              {},
	"autovacuum_vacuum_threshold":                 {},
	"autovacuum_work_mem":                         {},
	"backend_flush_after":                         {},
	"backslash_quote":                             {},
	"backtrace_functions":                         {},
	"bgwriter_delay":                              {},
	"bgwriter_flush_after":                        {},
	"bgwriter_lru_maxpages":                       {},
	"bgwriter_lru_multiplier":                     {},
	"block_size":                                  {},
	"bonjour":                                     {},
	"bonjour_name":                                {},
	"bytea_output":                                {},
	"check_function_bodies":                       {},
	"checkpoint_completion_target":                {},
	"checkpoint_flush_after":                      {},
	"checkpoint_timeout":                          {},
	"checkpoint_warning":                          {},
	"client_connection_check_interval":            {},
	"client_encoding":                             {},
	"client_min_messages":                         {},
	"cluster_name":                                {},
	"commit_delay":                                {},
	"commit_siblings":                             {},
	"compute_query_id":                            {},
	"config_file":                                 {},
	"constraint_exclusion":                        {},
	"cpu_index_tuple_cost":                        {},
	"cpu_operator_cost":                           {},
	"cpu_tuple_cost":                              {},
	"createrole_self_grant":                       {},
	"cursor_tuple_fraction":                       {},
	"data_checksums":                              {},
	"data_directory":                              {},
	"data_directory_mode":                         {},
	"data_sync_retry":                             {},
	"datestyle":                                   {}, // DateStyle
	"db_user_namespace":                           {},
	"deadlock_timeout":                            {},
	"debug_assertions":                            {},
	"debug_discard_caches":                        {},
	"debug_io_direct":                             {},
	"debug_logical_replication_streaming":         {},
	"debug_parallel_query":                        {},
	"debug_pretty_print":                          {},
	"debug_print_parse":                           {},
	"debug_print_plan":                            {},
	"debug_print_rewritten":                       {},
	"default_statistics_target":                   {},
	"default_table_access_method":                 {},
	"default_tablespace":                          {},
	"default_text_search_config":                  {},
	"default_toast_compression":                   {},
	"default_transaction_deferrable":              {},
	"default_transaction_isolation":               {},
	"default_transaction_read_only":               {},
	"dynamic_library_path":                        {},
	"dynamic_shared_memory_type":                  {},
	"effective_cache_size":                        {},
	"effective_io_concurrency":                    {},
	"enable_async_append":                         {},
	"enable_bitmapscan":                           {},
	"enable_gathermerge":                          {},
	"enable_hashagg":                              {},
	"enable_hashjoin":                             {},
	"enable_incremental_sort":                     {},
	"enable_indexonlyscan":                        {},
	"enable_indexscan":                            {},
	"enable_material":                             {},
	"enable_memoize":                              {},
	"enable_mergejoin":                            {},
	"enable_nestloop":                             {},
	"enable_parallel_append":                      {},
	"enable_parallel_hash":                        {},
	"enable_partition_pruning":                    {},
	"enable_partitionwise_aggregate":              {},
	"enable_partitionwise_join":                   {},
	"enable_presorted_aggregate":                  {},
	"enable_seqscan":                              {},
	"enable_sort":                                 {},
	"enable_tidscan":                              {},
	"escape_string_warning":                       {},
	"event_source":                                {},
	"exit_on_error":                               {},
	"external_pid_file":                           {},
	"extra_float_digits":                          {},
	"from_collapse_limit":                         {},
	"fsync":                                       {},
	"full_page_writes":                            {},
	"geqo":                                        {},
	"geqo_effort":                                 {},
	"geqo_generations":                            {},
	"geqo_pool_size":                              {},
	"geqo_seed":                                   {},
	"geqo_selection_bias":                         {},
	"geqo_threshold":                              {},
	"gin_fuzzy_search_limit":                      {},
	"gin_pending_list_limit":                      {},
	"gss_accept_delegation":                       {},
	"hash_mem_multiplier":                         {},
	"hba_file":                                    {},
	"hot_standby":                                 {},
	"hot_standby_feedback":                        {},
	"huge_page_size":                              {},
	"huge_pages":                                  {},
	"icu_validation_level":                        {},
	"ident_file":                                  {},
	"idle_in_transaction_session_timeout":         {},
	"idle_session_timeout":                        {},
	"ignore_checksum_failure":                     {},
	"ignore_invalid_pages":                        {},
	"ignore_system_indexes":                       {},
	"in_hot_standby":                              {},
	"integer_datetimes":                           {},
	"intervalstyle":                               {}, // IntervalStyle
	"jit":                                         {},
	"jit_above_cost":                              {},
	"jit_debugging_support":                       {},
	"jit_dump_bitcode":                            {},
	"jit_expressions":                             {},
	"jit_inline_above_cost":                       {},
	"jit_optimize_above_cost":                     {},
	"jit_profiling_support":                       {},
	"jit_provider":                                {},
	"jit_tuple_deforming":                         {},
	"join_collapse_limit":                         {},
	"krb_caseins_users":                           {},
	"krb_server_keyfile":                          {},
	"lc_messages":                                 {},
	"lc_monetary":                                 {},
	"lc_numeric":                                  {},
	"lc_time":                                     {},
	"listen_addresses":                            {},
	"lo_compat_privileges":                        {},
	"local_preload_libraries":                     {},
	"lock_timeout":                                {},
	"log_autovacuum_min_duration":                 {},
	"log_checkpoints":                             {},
	"log_connections":                             {},
	"log_destination":                             {},
	"log_directory":                               {},
	"log_disconnections":                          {},
	"log_duration":                                {},
	"log_error_verbosity":                         {},
	"log_executor_stats":                          {},
	"log_file_mode":                               {},
	"log_filename":                                {},
	"log_hostname":                                {},
	"log_line_prefix":                             {},
	"log_lock_waits":                              {},
	"log_min_duration_sample":                     {},
	"log_min_duration_statement":                  {},
	"log_min_error_statement":                     {},
	"log_min_messages":                            {},
	"log_parameter_max_length":                    {},
	"log_parameter_max_length_on_error":           {},
	"log_parser_stats":                            {},
	"log_planner_stats":                           {},
	"log_recovery_conflict_waits":                 {},
	"log_replication_commands":                    {},
	"log_rotation_age":                            {},
	"log_rotation_size":                           {},
	"log_startup_progress_interval":               {},
	"log_statement":                               {},
	"log_statement_sample_rate":                   {},
	"log_statement_stats":                         {},
	"log_temp_files":                              {},
	"log_timezone":                                {},
	"log_transaction_sample_rate":                 {},
	"log_truncate_on_rotation":                    {},
	"logging_collector":                           {},
	"logical_decoding_work_mem":                   {},
	"maintenance_io_concurrency":                  {},
	"maintenance_work_mem":                        {},
	"max_connections":                             {},
	"max_files_per_process":                       {},
	"max_function_args":                           {},
	"max_identifier_length":                       {},
	"max_index_keys":                              {},
	"max_locks_per_transaction":                   {},
	"max_logical_replication_workers":             {},
	"max_parallel_apply_workers_per_subscription": {},
	"max_parallel_maintenance_workers":            {},
	"max_parallel_workers":                        {},
	"max_parallel_workers_per_gather":             {},
	"max_pred_locks_per_page":                     {},
	"max_pred_locks_per_relation":                 {},
	"max_pred_locks_per_transaction":              {},
	"max_prepared_transactions":                   {},
	"max_replication_slots":                       {},
	"max_slot_wal_keep_size":                      {},
	"max_stack_depth":                             {},
	"max_standby_archive_delay":                   {},
	"max_standby_streaming_delay":                 {},
	"max_sync_workers_per_subscription":           {},
	"max_wal_senders":                             {},
	"max_wal_size":                                {},
	"max_worker_processes":                        {},
	"min_dynamic_shared_memory":                   {},
	"min_parallel_index_scan_size":                {},
	"min_parallel_table_scan_size":                {},
	"min_wal_size":                                {},
	"old_snapshot_threshold":                      {},
	"parallel_leader_participation":               {},
	"parallel_setup_cost":                         {},
	"parallel_tuple_cost":                         {},
	"password_encryption":                         {},
	"plan_cache_mode":                             {},
	"port":                                        {},
	"post_auth_delay":                             {},
	"pre_auth_delay":                              {},
	"primary_conninfo":                            {},
	"primary_slot_name":                           {},
	"quote_all_identifiers":                       {},
	"random_page_cost":                            {},
	"recovery_end_command":                        {},
	"recovery_init_sync_method":                   {},
	"recovery_min_apply_delay":                    {},
	"recovery_prefetch":                           {},
	"recovery_target":                             {},
	"recovery_target_action":                      {},
	"recovery_target_inclusive":                   {},
	"recovery_target_lsn":                         {},
	"recovery_target_name":                        {},
	"recovery_target_time":                        {},
	"recovery_target_timeline":                    {},
	"recovery_target_xid":                         {},
	"recursive_worktable_factor":                  {},
	"remove_temp_files_after_crash":               {},
	"reserved_connections":                        {},
	"restart_after_crash":                         {},
	"restore_command":                             {},
	"row_security":                                {},
	"scram_iterations":                            {},
	"search_path":                                 {},
	"segment_size":                                {},
	"send_abort_for_crash":                        {},
	"send_abort_for_kill":                         {},
	"seq_page_cost":                               {},
	"server_encoding":                             {},
	"server_version":                              {},
	"server_version_num":                          {},
	"session_preload_libraries":                   {},
	"session_replication_role":                    {},
	"shared_buffers":                              {},
	"shared_memory_size":                          {},
	"shared_memory_size_in_huge_pages":            {},
	"shared_memory_type":                          {},
	"shared_preload_libraries":                    {},
	"ssl":                                         {},
	"ssl_ca_file":                                 {},
	"ssl_cert_file":                               {},
	"ssl_ciphers":                                 {},
	"ssl_crl_dir":                                 {},
	"ssl_crl_file":                                {},
	"ssl_dh_params_file":                          {},
	"ssl_ecdh_curve":                              {},
	"ssl_key_file":                                {},
	"ssl_library":                                 {},
	"ssl_max_protocol_version":                    {},
	"ssl_min_protocol_version":                    {},
	"ssl_passphrase_command":                      {},
	"ssl_passphrase_command_supports_reload":      {},
	"ssl_prefer_server_ciphers":                   {},
	"standard_conforming_strings":                 {},
	"statement_timeout":                           {},
	"stats_fetch_consistency":                     {},
	"superuser_reserved_connections":              {},
	"synchronize_seqscans":                        {},
	"synchronous_commit":                          {},
	"synchronous_standby_names":                   {},
	"syslog_facility":                             {},
	"syslog_ident":                                {},
	"syslog_sequence_numbers":                     {},
	"syslog_split_messages":                       {},
	"tcp_keepalives_count":                        {},
	"tcp_keepalives_idle":                         {},
	"tcp_keepalives_interval":                     {},
	"tcp_user_timeout":                            {},
	"temp_buffers":                                {},
	"temp_file_limit":                             {},
	"temp_tablespaces":                            {},
	"timezone":                                    {}, // TimeZone
	"timezone_abbreviations":                      {},
	"trace_notify":                                {},
	"trace_recovery_messages":                     {},
	"trace_sort":                                  {},
	"track_activities":                            {},
	"track_activity_query_size":                   {},
	"track_commit_timestamp":                      {},
	"track_counts":                                {},
	"track_functions":                             {},
	"track_io_timing":                             {},
	"track_wal_io_timing":                         {},
	"transaction_deferrable":                      {},
	"transaction_isolation":                       {},
	"transaction_read_only":                       {},
	"transform_null_equals":                       {},
	"unix_socket_directories":                     {},
	"unix_socket_group":                           {},
	"unix_socket_permissions":                     {},
	"update_process_title":                        {},
	"vacuum_buffer_usage_limit":                   {},
	"vacuum_cost_delay":                           {},
	"vacuum_cost_limit":                           {},
	"vacuum_cost_page_dirty":                      {},
	"vacuum_cost_page_hit":                        {},
	"vacuum_cost_page_miss":                       {},
	"vacuum_failsafe_age":                         {},
	"vacuum_freeze_min_age":                       {},
	"vacuum_freeze_table_age":                     {},
	"vacuum_multixact_failsafe_age":               {},
	"vacuum_multixact_freeze_min_age":             {},
	"vacuum_multixact_freeze_table_age":           {},
	"wal_block_size":                              {},
	"wal_buffers":                                 {},
	"wal_compression":                             {},
	"wal_consistency_checking":                    {},
	"wal_decode_buffer_size":                      {},
	"wal_init_zero":                               {},
	"wal_keep_size":                               {},
	"wal_level":                                   {},
	"wal_log_hints":                               {},
	"wal_receiver_create_temp_slot":               {},
	"wal_receiver_status_interval":                {},
	"wal_receiver_timeout":                        {},
	"wal_recycle":                                 {},
	"wal_retrieve_retry_interval":                 {},
	"wal_segment_size":                            {},
	"wal_sender_timeout":                          {},
	"wal_skip_threshold":                          {},
	"wal_sync_method":                             {},
	"wal_writer_delay":                            {},
	"wal_writer_flush_after":                      {},
	"work_mem":                                    {},
	"xmlbinary":                                   {},
	"xmloption":                                   {},
	"zero_damaged_pages":                          {},
}
