// Copyright 2024 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package id

import "github.com/lib/pq/oid"

// This adds all of the built-in type IDs to the cache.
func init() {
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_abstime"), uint32(oid.T__abstime))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_aclitem"), uint32(oid.T__aclitem))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_bit"), uint32(oid.T__bit))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_bool"), uint32(oid.T__bool))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_box"), uint32(oid.T__box))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_bpchar"), uint32(oid.T__bpchar))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_bytea"), uint32(oid.T__bytea))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_char"), uint32(oid.T__char))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_cid"), uint32(oid.T__cid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_cidr"), uint32(oid.T__cidr))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_circle"), uint32(oid.T__circle))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_cstring"), uint32(oid.T__cstring))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_date"), uint32(oid.T__date))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_daterange"), uint32(oid.T__daterange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_float4"), uint32(oid.T__float4))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_float8"), uint32(oid.T__float8))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_gtsvector"), uint32(oid.T__gtsvector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_inet"), uint32(oid.T__inet))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_int2"), uint32(oid.T__int2))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_int2vector"), uint32(oid.T__int2vector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_int4"), uint32(oid.T__int4))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_int4range"), uint32(oid.T__int4range))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_int8"), uint32(oid.T__int8))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_int8range"), uint32(oid.T__int8range))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_interval"), uint32(oid.T__interval))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_json"), uint32(oid.T__json))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_jsonb"), uint32(oid.T__jsonb))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_line"), uint32(oid.T__line))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_lseg"), uint32(oid.T__lseg))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_macaddr"), uint32(oid.T__macaddr))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_money"), uint32(oid.T__money))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_name"), uint32(oid.T__name))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_numeric"), uint32(oid.T__numeric))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_numrange"), uint32(oid.T__numrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_oid"), uint32(oid.T__oid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_oidvector"), uint32(oid.T__oidvector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_path"), uint32(oid.T__path))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_pg_lsn"), uint32(oid.T__pg_lsn))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_point"), uint32(oid.T__point))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_polygon"), uint32(oid.T__polygon))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_record"), uint32(oid.T__record))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_refcursor"), uint32(oid.T__refcursor))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regclass"), uint32(oid.T__regclass))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regconfig"), uint32(oid.T__regconfig))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regdictionary"), uint32(oid.T__regdictionary))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regnamespace"), uint32(oid.T__regnamespace))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regoper"), uint32(oid.T__regoper))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regoperator"), uint32(oid.T__regoperator))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regproc"), uint32(oid.T__regproc))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regprocedure"), uint32(oid.T__regprocedure))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regrole"), uint32(oid.T__regrole))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_regtype"), uint32(oid.T__regtype))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_reltime"), uint32(oid.T__reltime))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_text"), uint32(oid.T__text))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_tid"), uint32(oid.T__tid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_time"), uint32(oid.T__time))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_timestamp"), uint32(oid.T__timestamp))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_timestamptz"), uint32(oid.T__timestamptz))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_timetz"), uint32(oid.T__timetz))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_tinterval"), uint32(oid.T__tinterval))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_tsquery"), uint32(oid.T__tsquery))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_tsrange"), uint32(oid.T__tsrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_tstzrange"), uint32(oid.T__tstzrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_tsvector"), uint32(oid.T__tsvector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_txid_snapshot"), uint32(oid.T__txid_snapshot))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_uuid"), uint32(oid.T__uuid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_varbit"), uint32(oid.T__varbit))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_varchar"), uint32(oid.T__varchar))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_xid"), uint32(oid.T__xid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "_xml"), uint32(oid.T__xml))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "abstime"), uint32(oid.T_abstime))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "aclitem"), uint32(oid.T_aclitem))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "any"), uint32(oid.T_any))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "anyarray"), uint32(oid.T_anyarray))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "anyelement"), uint32(oid.T_anyelement))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "anyenum"), uint32(oid.T_anyenum))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "anynonarray"), uint32(oid.T_anynonarray))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "anyrange"), uint32(oid.T_anyrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "bit"), uint32(oid.T_bit))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "bool"), uint32(oid.T_bool))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "box"), uint32(oid.T_box))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "bpchar"), uint32(oid.T_bpchar))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "bytea"), uint32(oid.T_bytea))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "char"), uint32(oid.T_char))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "cid"), uint32(oid.T_cid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "cidr"), uint32(oid.T_cidr))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "circle"), uint32(oid.T_circle))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "cstring"), uint32(oid.T_cstring))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "date"), uint32(oid.T_date))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "daterange"), uint32(oid.T_daterange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "event_trigger"), uint32(oid.T_event_trigger))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "fdw_handler"), uint32(oid.T_fdw_handler))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "float4"), uint32(oid.T_float4))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "float8"), uint32(oid.T_float8))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "gtsvector"), uint32(oid.T_gtsvector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "index_am_handler"), uint32(oid.T_index_am_handler))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "inet"), uint32(oid.T_inet))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "int2"), uint32(oid.T_int2))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "int2vector"), uint32(oid.T_int2vector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "int4"), uint32(oid.T_int4))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "int4range"), uint32(oid.T_int4range))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "int8"), uint32(oid.T_int8))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "int8range"), uint32(oid.T_int8range))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "internal"), uint32(oid.T_internal))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "interval"), uint32(oid.T_interval))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "json"), uint32(oid.T_json))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "jsonb"), uint32(oid.T_jsonb))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "language_handler"), uint32(oid.T_language_handler))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "line"), uint32(oid.T_line))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "lseg"), uint32(oid.T_lseg))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "macaddr"), uint32(oid.T_macaddr))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "money"), uint32(oid.T_money))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "name"), uint32(oid.T_name))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "numeric"), uint32(oid.T_numeric))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "numrange"), uint32(oid.T_numrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "oid"), uint32(oid.T_oid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "oidvector"), uint32(oid.T_oidvector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "opaque"), uint32(oid.T_opaque))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "path"), uint32(oid.T_path))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_attribute"), uint32(oid.T_pg_attribute))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_auth_members"), uint32(oid.T_pg_auth_members))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_authid"), uint32(oid.T_pg_authid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_class"), uint32(oid.T_pg_class))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_database"), uint32(oid.T_pg_database))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_ddl_command"), uint32(oid.T_pg_ddl_command))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_lsn"), uint32(oid.T_pg_lsn))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_node_tree"), uint32(oid.T_pg_node_tree))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_proc"), uint32(oid.T_pg_proc))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_shseclabel"), uint32(oid.T_pg_shseclabel))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "pg_type"), uint32(oid.T_pg_type))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "point"), uint32(oid.T_point))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "polygon"), uint32(oid.T_polygon))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "record"), uint32(oid.T_record))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "refcursor"), uint32(oid.T_refcursor))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regclass"), uint32(oid.T_regclass))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regconfig"), uint32(oid.T_regconfig))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regdictionary"), uint32(oid.T_regdictionary))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regnamespace"), uint32(oid.T_regnamespace))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regoper"), uint32(oid.T_regoper))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regoperator"), uint32(oid.T_regoperator))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regproc"), uint32(oid.T_regproc))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regprocedure"), uint32(oid.T_regprocedure))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regrole"), uint32(oid.T_regrole))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "regtype"), uint32(oid.T_regtype))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "reltime"), uint32(oid.T_reltime))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "smgr"), uint32(oid.T_smgr))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "text"), uint32(oid.T_text))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tid"), uint32(oid.T_tid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "time"), uint32(oid.T_time))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "timestamp"), uint32(oid.T_timestamp))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "timestamptz"), uint32(oid.T_timestamptz))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "timetz"), uint32(oid.T_timetz))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tinterval"), uint32(oid.T_tinterval))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "trigger"), uint32(oid.T_trigger))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tsm_handler"), uint32(oid.T_tsm_handler))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tsquery"), uint32(oid.T_tsquery))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tsrange"), uint32(oid.T_tsrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tstzrange"), uint32(oid.T_tstzrange))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "tsvector"), uint32(oid.T_tsvector))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "txid_snapshot"), uint32(oid.T_txid_snapshot))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "unknown"), uint32(oid.T_unknown))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "uuid"), uint32(oid.T_uuid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "varbit"), uint32(oid.T_varbit))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "varchar"), uint32(oid.T_varchar))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "void"), uint32(oid.T_void))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "xid"), uint32(oid.T_xid))
	globalCache.setBuiltIn(NewInternal(Section_Type, "pg_catalog", "xml"), uint32(oid.T_xml))
}
