[package]
name = "prolly"
description = "Dolt's prolly trees: tree nodes, maps, address maps, and blobs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serial = { path = "../serial" }
store = { path = "../store" }

[lints]
workspace = true
