// Code generated by lex/all_keywords. DO NOT EDIT.

package lex

var KeywordsCategories = map[string]string{
	"abort":                        "U",
	"access":                       "U",
	"action":                       "U",
	"add":                          "U",
	"admin":                        "U",
	"after":                        "U",
	"aggregate":                    "U",
	"alignment":                    "U",
	"all":                          "R",
	"allow_connections":            "U",
	"alter":                        "U",
	"always":                       "U",
	"analyse":                      "R",
	"analyze":                      "R",
	"and":                          "R",
	"annotate_type":                "C",
	"any":                          "R",
	"array":                        "R",
	"as":                           "R",
	"asc":                          "R",
	"assignment":                   "U",
	"asymmetric":                   "R",
	"at":                           "U",
	"atomic":                       "U",
	"attach":                       "U",
	"attribute":                    "U",
	"authorization":                "T",
	"auto":                         "U",
	"automatic":                    "U",
	"backup":                       "U",
	"backups":                      "U",
	"basetype":                     "U",
	"before":                       "U",
	"begin":                        "U",
	"between":                      "C",
	"bigint":                       "C",
	"binary":                       "U",
	"bit":                          "C",
	"boolean":                      "C",
	"both":                         "R",
	"box2d":                        "C",
	"bpchar":                       "C",
	"bucket_count":                 "U",
	"buffer_usage_limit":           "U",
	"bundle":                       "U",
	"by":                           "U",
	"bypassrls":                    "U",
	"cache":                        "U",
	"call":                         "U",
	"called":                       "U",
	"cancel":                       "U",
	"cancelquery":                  "U",
	"canonical":                    "U",
	"cascade":                      "U",
	"cascaded":                     "U",
	"case":                         "R",
	"cast":                         "R",
	"category":                     "U",
	"chain":                        "U",
	"changefeed":                   "U",
	"char":                         "C",
	"character":                    "C",
	"characteristics":              "C",
	"check":                        "R",
	"check_option":                 "U",
	"class":                        "U",
	"close":                        "U",
	"cluster":                      "U",
	"coalesce":                     "C",
	"collatable":                   "U",
	"collate":                      "R",
	"collation":                    "T",
	"collation_version":            "U",
	"column":                       "R",
	"columns":                      "U",
	"combinefunc":                  "U",
	"comment":                      "U",
	"comments":                     "U",
	"commit":                       "U",
	"committed":                    "U",
	"compact":                      "U",
	"complete":                     "U",
	"compression":                  "U",
	"concurrently":                 "R",
	"configuration":                "U",
	"configurations":               "U",
	"configure":                    "U",
	"conflict":                     "U",
	"connect":                      "R",
	"connection":                   "U",
	"constraint":                   "R",
	"constraints":                  "U",
	"controlchangefeed":            "U",
	"controljob":                   "U",
	"conversion":                   "U",
	"convert":                      "U",
	"copy":                         "U",
	"cost":                         "U",
	"create":                       "R",
	"createdb":                     "U",
	"createlogin":                  "U",
	"createrole":                   "U",
	"cross":                        "T",
	"csv":                          "U",
	"cube":                         "U",
	"current":                      "U",
	"current_catalog":              "R",
	"current_date":                 "R",
	"current_role":                 "R",
	"current_schema":               "R",
	"current_time":                 "R",
	"current_timestamp":            "R",
	"current_user":                 "R",
	"cycle":                        "U",
	"data":                         "U",
	"database":                     "U",
	"databases":                    "U",
	"day":                          "U",
	"deallocate":                   "U",
	"dec":                          "C",
	"decimal":                      "C",
	"declare":                      "U",
	"default":                      "R",
	"defaults":                     "U",
	"deferrable":                   "R",
	"deferred":                     "U",
	"definer":                      "U",
	"delete":                       "U",
	"delimiter":                    "U",
	"depends":                      "U",
	"desc":                         "R",
	"describe":                     "R",
	"deserialfunc":                 "U",
	"destination":                  "U",
	"detach":                       "U",
	"detached":                     "U",
	"dictionary":                   "U",
	"disable":                      "U",
	"disable_page_skipping":        "U",
	"discard":                      "U",
	"distinct":                     "R",
	"do":                           "R",
	"domain":                       "U",
	"double":                       "U",
	"drop":                         "U",
	"each":                         "U",
	"element":                      "R",
	"else":                         "R",
	"enable":                       "U",
	"encoding":                     "U",
	"encrypted":                    "U",
	"encryption_passphrase":        "U",
	"end":                          "R",
	"enum":                         "U",
	"enums":                        "U",
	"escape":                       "U",
	"event":                        "U",
	"except":                       "R",
	"exclude":                      "U",
	"excluding":                    "U",
	"execute":                      "U",
	"execution":                    "U",
	"exists":                       "C",
	"experimental":                 "U",
	"experimental_audit":           "U",
	"experimental_fingerprints":    "U",
	"experimental_replica":         "U",
	"expiration":                   "U",
	"explain":                      "U",
	"export":                       "U",
	"expression":                   "U",
	"extended":                     "U",
	"extension":                    "U",
	"external":                     "U",
	"extract":                      "C",
	"extract_duration":             "C",
	"false":                        "R",
	"family":                       "U",
	"fetch":                        "R",
	"files":                        "U",
	"filter":                       "U",
	"finalfunc":                    "U",
	"finalfunc_extra":              "U",
	"finalfunc_modify":             "U",
	"finalize":                     "U",
	"first":                        "U",
	"float":                        "C",
	"following":                    "U",
	"for":                          "R",
	"force":                        "U",
	"force_index":                  "U",
	"foreign":                      "R",
	"format":                       "U",
	"freeze":                       "R",
	"from":                         "R",
	"full":                         "T",
	"function":                     "U",
	"functions":                    "U",
	"generated":                    "U",
	"geography":                    "C",
	"geometry":                     "C",
	"geometrycollection":           "U",
	"geometrycollectionm":          "U",
	"geometrycollectionz":          "U",
	"geometrycollectionzm":         "U",
	"geometrym":                    "U",
	"geometryz":                    "U",
	"geometryzm":                   "U",
	"global":                       "U",
	"grant":                        "R",
	"granted":                      "U",
	"grants":                       "U",
	"greatest":                     "C",
	"group":                        "R",
	"grouping":                     "C",
	"groups":                       "U",
	"handler":                      "U",
	"hash":                         "U",
	"having":                       "R",
	"header":                       "U",
	"high":                         "U",
	"hint":                         "C",
	"histogram":                    "U",
	"hour":                         "U",
	"hypothetical":                 "U",
	"icu_locale":                   "U",
	"icu_rules":                    "U",
	"identity":                     "U",
	"if":                           "C",
	"iferror":                      "C",
	"ifnull":                       "C",
	"ignore_foreign_keys":          "U",
	"ilike":                        "T",
	"immediate":                    "U",
	"immutable":                    "U",
	"implicit":                     "U",
	"import":                       "U",
	"in":                           "R",
	"include":                      "U",
	"including":                    "U",
	"increment":                    "U",
	"incremental":                  "U",
	"index":                        "C",
	"indexes":                      "U",
	"index_cleanup":                "U",
	"inherit":                      "U",
	"inherits":                     "U",
	"initcond":                     "U",
	"initially":                    "R",
	"inject":                       "U",
	"inline":                       "U",
	"inner":                        "T",
	"inout":                        "C",
	"input":                        "U",
	"insert":                       "U",
	"instead":                      "U",
	"int":                          "C",
	"integer":                      "C",
	"interleave":                   "U",
	"internallength":               "U",
	"intersect":                    "R",
	"interval":                     "C",
	"into":                         "R",
	"into_db":                      "U",
	"inverted":                     "U",
	"invoker":                      "U",
	"is":                           "T",
	"iserror":                      "C",
	"isnull":                       "T",
	"isolation":                    "U",
	"is_template":                  "U",
	"job":                          "U",
	"jobs":                         "U",
	"join":                         "T",
	"json":                         "U",
	"key":                          "U",
	"keys":                         "U",
	"kms":                          "U",
	"kv":                           "U",
	"language":                     "U",
	"large":                        "U",
	"last":                         "U",
	"lateral":                      "R",
	"latest":                       "U",
	"lc_collate":                   "U",
	"lc_ctype":                     "U",
	"leading":                      "R",
	"leakproof":                    "U",
	"lease":                        "U",
	"least":                        "C",
	"left":                         "T",
	"less":                         "U",
	"level":                        "U",
	"like":                         "T",
	"limit":                        "R",
	"linestring":                   "U",
	"list":                         "U",
	"local":                        "U",
	"locale":                       "U",
	"locale_provider":              "U",
	"localtime":                    "R",
	"localtimestamp":               "R",
	"locked":                       "U",
	"logged":                       "U",
	"login":                        "U",
	"lookup":                       "U",
	"low":                          "U",
	"main":                         "U",
	"match":                        "U",
	"materialized":                 "U",
	"maxvalue":                     "U",
	"merge":                        "U",
	"method":                       "U",
	"mfinalfunc":                   "U",
	"mfinalfunc_extra":             "U",
	"mfinalfunc_modify":            "U",
	"minitcond":                    "U",
	"minute":                       "U",
	"minvalue":                     "U",
	"minvfunc":                     "U",
	"modifyclustersetting":         "U",
	"modulus":                      "U",
	"month":                        "U",
	"msfunc":                       "U",
	"mspace":                       "U",
	"msspace":                      "U",
	"mstype":                       "U",
	"multilinestring":              "U",
	"multilinestringm":             "U",
	"multilinestringz":             "U",
	"multilinestringzm":            "U",
	"multipoint":                   "U",
	"multipointm":                  "U",
	"multipointz":                  "U",
	"multipointzm":                 "U",
	"multipolygon":                 "U",
	"multipolygonm":                "U",
	"multipolygonz":                "U",
	"multipolygonzm":               "U",
	"multirange_type_name":         "U",
	"name":                         "U",
	"names":                        "U",
	"nan":                          "U",
	"natural":                      "T",
	"never":                        "U",
	"new":                          "U",
	"next":                         "U",
	"no":                           "U",
	"nobypassrls":                  "U",
	"nocancelquery":                "U",
	"nocontrolchangefeed":          "U",
	"nocontroljob":                 "U",
	"nocreatedb":                   "U",
	"nocreatelogin":                "U",
	"nocreaterole":                 "U",
	"noinherit":                    "U",
	"nologin":                      "U",
	"nomodifyclustersetting":       "U",
	"none":                         "T",
	"noreplication":                "U",
	"normal":                       "U",
	"nosuperuser":                  "U",
	"not":                          "R",
	"nothing":                      "R",
	"notnull":                      "T",
	"noviewactivity":               "U",
	"nowait":                       "U",
	"no_index_join":                "U",
	"null":                         "R",
	"nullif":                       "C",
	"nulls":                        "U",
	"numeric":                      "C",
	"object":                       "U",
	"of":                           "U",
	"off":                          "U",
	"offset":                       "R",
	"oid":                          "U",
	"oids":                         "U",
	"old":                          "U",
	"on":                           "R",
	"only":                         "R",
	"only_database_stats":          "U",
	"operator":                     "U",
	"opt":                          "U",
	"option":                       "U",
	"options":                      "U",
	"or":                           "R",
	"order":                        "R",
	"ordinality":                   "U",
	"others":                       "U",
	"out":                          "C",
	"outer":                        "T",
	"output":                       "U",
	"over":                         "U",
	"overlaps":                     "T",
	"overlay":                      "C",
	"owned":                        "U",
	"owner":                        "U",
	"parallel":                     "U",
	"parameter":                    "U",
	"parent":                       "U",
	"parser":                       "U",
	"partial":                      "U",
	"partition":                    "U",
	"partitions":                   "U",
	"passedbyvalue":                "U",
	"password":                     "U",
	"pause":                        "U",
	"paused":                       "U",
	"physical":                     "U",
	"placing":                      "R",
	"plain":                        "U",
	"plan":                         "U",
	"plans":                        "U",
	"point":                        "C",
	"pointm":                       "U",
	"pointz":                       "U",
	"pointzm":                      "U",
	"policy":                       "U",
	"polygon":                      "C",
	"polygonm":                     "U",
	"polygonz":                     "U",
	"polygonzm":                    "U",
	"position":                     "C",
	"preceding":                    "U",
	"precision":                    "C",
	"preferred":                    "U",
	"prepare":                      "U",
	"preserve":                     "U",
	"primary":                      "R",
	"priority":                     "U",
	"privileges":                   "U",
	"procedural":                   "U",
	"procedure":                    "U",
	"procedures":                   "U",
	"process_main":                 "U",
	"process_toast":                "U",
	"public":                       "U",
	"publication":                  "U",
	"queries":                      "U",
	"query":                        "U",
	"range":                        "U",
	"ranges":                       "U",
	"read":                         "U",
	"read_only":                    "U",
	"read_write":                   "U",
	"real":                         "C",
	"receive":                      "U",
	"recurring":                    "U",
	"recursive":                    "U",
	"ref":                          "U",
	"references":                   "R",
	"referencing":                  "U",
	"refresh":                      "U",
	"reindex":                      "U",
	"release":                      "U",
	"remainder":                    "U",
	"rename":                       "U",
	"repeatable":                   "U",
	"replace":                      "U",
	"replica":                      "U",
	"replication":                  "U",
	"reset":                        "U",
	"restart":                      "U",
	"restore":                      "U",
	"restrict":                     "U",
	"restricted":                   "U",
	"resume":                       "U",
	"retry":                        "U",
	"return":                       "U",
	"returning":                    "R",
	"returns":                      "U",
	"revision_history":             "U",
	"revoke":                       "U",
	"right":                        "T",
	"role":                         "U",
	"roles":                        "U",
	"rollback":                     "U",
	"rollup":                       "U",
	"routine":                      "U",
	"routines":                     "U",
	"row":                          "C",
	"rows":                         "U",
	"rule":                         "U",
	"running":                      "U",
	"safe":                         "U",
	"savepoint":                    "U",
	"scatter":                      "U",
	"schedule":                     "U",
	"schedules":                    "U",
	"schema":                       "U",
	"schemas":                      "U",
	"scrub":                        "U",
	"search":                       "U",
	"second":                       "U",
	"security":                     "U",
	"security_barrier":             "U",
	"security_invoker":             "U",
	"seed":                         "U",
	"select":                       "R",
	"send":                         "U",
	"sequence":                     "U",
	"sequences":                    "U",
	"serialfunc":                   "U",
	"serializable":                 "U",
	"server":                       "U",
	"session":                      "U",
	"sessions":                     "U",
	"session_user":                 "R",
	"set":                          "U",
	"setof":                        "C",
	"setting":                      "U",
	"settings":                     "U",
	"sfunc":                        "U",
	"share":                        "U",
	"shareable":                    "U",
	"show":                         "U",
	"similar":                      "T",
	"simple":                       "U",
	"skip":                         "U",
	"skip_database_stats":          "U",
	"skip_locked":                  "U",
	"skip_missing_foreign_keys":    "U",
	"skip_missing_sequences":       "U",
	"skip_missing_sequence_owners": "U",
	"skip_missing_views":           "U",
	"smallint":                     "C",
	"snapshot":                     "U",
	"some":                         "R",
	"sortop":                       "U",
	"split":                        "U",
	"sql":                          "U",
	"sspace":                       "U",
	"stable":                       "U",
	"start":                        "U",
	"statement":                    "U",
	"statistics":                   "U",
	"status":                       "U",
	"stdin":                        "U",
	"storage":                      "U",
	"store":                        "U",
	"stored":                       "U",
	"strategy":                     "U",
	"strict":                       "U",
	"string":                       "C",
	"stype":                        "U",
	"subscript":                    "U",
	"subscription":                 "U",
	"substring":                    "C",
	"subtype":                      "U",
	"subtype_diff":                 "U",
	"subtype_opclass":              "U",
	"superuser":                    "U",
	"support":                      "U",
	"symmetric":                    "R",
	"syntax":                       "U",
	"sysid":                        "U",
	"system":                       "U",
	"table":                        "R",
	"tables":                       "U",
	"tablespace":                   "U",
	"temp":                         "U",
	"template":                     "U",
	"temporary":                    "U",
	"text":                         "U",
	"then":                         "R",
	"throttling":                   "U",
	"ties":                         "U",
	"time":                         "C",
	"timestamp":                    "C",
	"timestamptz":                  "C",
	"timetz":                       "C",
	"to":                           "R",
	"trace":                        "U",
	"trailing":                     "R",
	"transaction":                  "U",
	"transactions":                 "U",
	"transform":                    "U",
	"treat":                        "C",
	"trigger":                      "U",
	"trim":                         "C",
	"true":                         "R",
	"truncate":                     "U",
	"trusted":                      "U",
	"type":                         "U",
	"types":                        "U",
	"typmod_in":                    "U",
	"typmod_out":                   "U",
	"unbounded":                    "U",
	"uncommitted":                  "U",
	"union":                        "R",
	"unique":                       "R",
	"unknown":                      "U",
	"unlogged":                     "U",
	"unsafe":                       "U",
	"unsplit":                      "U",
	"until":                        "U",
	"update":                       "U",
	"upsert":                       "U",
	"usage":                        "U",
	"use":                          "U",
	"user":                         "R",
	"users":                        "U",
	"using":                        "R",
	"vacuum":                       "U",
	"valid":                        "U",
	"validate":                     "U",
	"validator":                    "U",
	"value":                        "U",
	"values":                       "C",
	"varbit":                       "C",
	"varchar":                      "C",
	"variable":                     "U",
	"variadic":                     "R",
	"varying":                      "U",
	"verbose":                      "R",
	"version":                      "U",
	"view":                         "U",
	"viewactivity":                 "U",
	"virtual":                      "C",
	"volatile":                     "C",
	"when":                         "R",
	"where":                        "R",
	"window":                       "R",
	"with":                         "R",
	"within":                       "U",
	"without":                      "U",
	"work":                         "C",
	"wrapper":                      "R",
	"write":                        "U",
	"xml":                          "U",
	"yaml":                         "U",
	"year":                         "U",
	"yes":                          "U",
	"zone":                         "U",
}

// KeywordNames contains all keywords sorted, so that pg_get_keywords returns
// deterministic results.
var KeywordNames = []string{
	"abort",
	"access",
	"action",
	"add",
	"admin",
	"after",
	"aggregate",
	"alignment",
	"all",
	"allow_connections",
	"alter",
	"always",
	"analyse",
	"analyze",
	"and",
	"annotate_type",
	"any",
	"array",
	"as",
	"asc",
	"assignment",
	"asymmetric",
	"at",
	"atomic",
	"attach",
	"attribute",
	"authorization",
	"auto",
	"automatic",
	"backup",
	"backups",
	"basetype",
	"before",
	"begin",
	"between",
	"bigint",
	"binary",
	"bit",
	"boolean",
	"both",
	"box2d",
	"bpchar",
	"bucket_count",
	"buffer_usage_limit",
	"bundle",
	"by",
	"bypassrls",
	"cache",
	"call",
	"called",
	"cancel",
	"cancelquery",
	"canonical",
	"cascade",
	"cascaded",
	"case",
	"cast",
	"category",
	"chain",
	"changefeed",
	"char",
	"character",
	"characteristics",
	"check",
	"check_option",
	"class",
	"close",
	"cluster",
	"coalesce",
	"collatable",
	"collate",
	"collation",
	"collation_version",
	"column",
	"columns",
	"combinefunc",
	"comment",
	"comments",
	"commit",
	"committed",
	"compact",
	"complete",
	"compression",
	"concurrently",
	"configuration",
	"configurations",
	"configure",
	"conflict",
	"connect",
	"connection",
	"constraint",
	"constraints",
	"controlchangefeed",
	"controljob",
	"conversion",
	"convert",
	"copy",
	"cost",
	"create",
	"createdb",
	"createlogin",
	"createrole",
	"cross",
	"csv",
	"cube",
	"current",
	"current_catalog",
	"current_date",
	"current_role",
	"current_schema",
	"current_time",
	"current_timestamp",
	"current_user",
	"cycle",
	"data",
	"database",
	"databases",
	"day",
	"deallocate",
	"dec",
	"decimal",
	"declare",
	"default",
	"defaults",
	"deferrable",
	"deferred",
	"definer",
	"delete",
	"delimiter",
	"depends",
	"desc",
	"describe",
	"deserialfunc",
	"destination",
	"detach",
	"detached",
	"dictionary",
	"disable",
	"disable_page_skipping",
	"discard",
	"distinct",
	"do",
	"domain",
	"double",
	"drop",
	"each",
	"element",
	"else",
	"enable",
	"encoding",
	"encrypted",
	"encryption_passphrase",
	"end",
	"enum",
	"enums",
	"escape",
	"event",
	"except",
	"exclude",
	"excluding",
	"execute",
	"execution",
	"exists",
	"experimental",
	"experimental_audit",
	"experimental_fingerprints",
	"experimental_replica",
	"expiration",
	"explain",
	"export",
	"expression",
	"extended",
	"extension",
	"external",
	"extract",
	"extract_duration",
	"false",
	"family",
	"fetch",
	"files",
	"filter",
	"finalfunc",
	"finalfunc_extra",
	"finalfunc_modify",
	"finalize",
	"first",
	"float",
	"following",
	"for",
	"force",
	"force_index",
	"foreign",
	"format",
	"freeze",
	"from",
	"full",
	"function",
	"functions",
	"generated",
	"geography",
	"geometry",
	"geometrycollection",
	"geometrycollectionm",
	"geometrycollectionz",
	"geometrycollectionzm",
	"geometrym",
	"geometryz",
	"geometryzm",
	"global",
	"grant",
	"granted",
	"grants",
	"greatest",
	"group",
	"grouping",
	"groups",
	"handler",
	"hash",
	"having",
	"header",
	"high",
	"hint",
	"histogram",
	"hour",
	"hypothetical",
	"icu_locale",
	"icu_rules",
	"identity",
	"if",
	"iferror",
	"ifnull",
	"ignore_foreign_keys",
	"ilike",
	"immediate",
	"immutable",
	"implicit",
	"import",
	"in",
	"include",
	"including",
	"increment",
	"incremental",
	"index",
	"indexes",
	"index_cleanup",
	"inherit",
	"inherits",
	"initcond",
	"initially",
	"inject",
	"inline",
	"inner",
	"inout",
	"input",
	"insert",
	"instead",
	"int",
	"integer",
	"interleave",
	"internallength",
	"intersect",
	"interval",
	"into",
	"into_db",
	"inverted",
	"invoker",
	"is",
	"iserror",
	"isnull",
	"isolation",
	"is_template",
	"job",
	"jobs",
	"join",
	"json",
	"key",
	"keys",
	"kms",
	"kv",
	"language",
	"large",
	"last",
	"lateral",
	"latest",
	"lc_collate",
	"lc_ctype",
	"leading",
	"leakproof",
	"lease",
	"least",
	"left",
	"less",
	"level",
	"like",
	"limit",
	"linestring",
	"list",
	"local",
	"locale",
	"locale_provider",
	"localtime",
	"localtimestamp",
	"locked",
	"logged",
	"login",
	"lookup",
	"low",
	"main",
	"match",
	"materialized",
	"maxvalue",
	"merge",
	"method",
	"mfinalfunc",
	"mfinalfunc_extra",
	"mfinalfunc_modify",
	"minitcond",
	"minute",
	"minvalue",
	"minvfunc",
	"modifyclustersetting",
	"modulus",
	"month",
	"msfunc",
	"mspace",
	"msspace",
	"mstype",
	"multilinestring",
	"multilinestringm",
	"multilinestringz",
	"multilinestringzm",
	"multipoint",
	"multipointm",
	"multipointz",
	"multipointzm",
	"multipolygon",
	"multipolygonm",
	"multipolygonz",
	"multipolygonzm",
	"multirange_type_name",
	"name",
	"names",
	"nan",
	"natural",
	"never",
	"new",
	"next",
	"no",
	"nobypassrls",
	"nocancelquery",
	"nocontrolchangefeed",
	"nocontroljob",
	"nocreatedb",
	"nocreatelogin",
	"nocreaterole",
	"noinherit",
	"nologin",
	"nomodifyclustersetting",
	"none",
	"noreplication",
	"normal",
	"nosuperuser",
	"not",
	"nothing",
	"notnull",
	"noviewactivity",
	"nowait",
	"no_index_join",
	"null",
	"nullif",
	"nulls",
	"numeric",
	"object",
	"of",
	"off",
	"offset",
	"oid",
	"oids",
	"old",
	"on",
	"only",
	"only_database_stats",
	"operator",
	"opt",
	"option",
	"options",
	"or",
	"order",
	"ordinality",
	"others",
	"out",
	"outer",
	"output",
	"over",
	"overlaps",
	"overlay",
	"owned",
	"owner",
	"parallel",
	"parameter",
	"parent",
	"parser",
	"partial",
	"partition",
	"partitions",
	"passedbyvalue",
	"password",
	"pause",
	"paused",
	"physical",
	"placing",
	"plain",
	"plan",
	"plans",
	"point",
	"pointm",
	"pointz",
	"pointzm",
	"policy",
	"polygon",
	"polygonm",
	"polygonz",
	"polygonzm",
	"position",
	"preceding",
	"precision",
	"preferred",
	"prepare",
	"preserve",
	"primary",
	"priority",
	"privileges",
	"procedural",
	"procedure",
	"procedures",
	"process_main",
	"process_toast",
	"public",
	"publication",
	"queries",
	"query",
	"range",
	"ranges",
	"read",
	"read_only",
	"read_write",
	"real",
	"receive",
	"recurring",
	"recursive",
	"ref",
	"references",
	"referencing",
	"refresh",
	"reindex",
	"release",
	"remainder",
	"rename",
	"repeatable",
	"replace",
	"replica",
	"replication",
	"reset",
	"restart",
	"restore",
	"restrict",
	"restricted",
	"resume",
	"retry",
	"return",
	"returning",
	"returns",
	"revision_history",
	"revoke",
	"right",
	"role",
	"roles",
	"rollback",
	"rollup",
	"routine",
	"routines",
	"row",
	"rows",
	"rule",
	"running",
	"safe",
	"savepoint",
	"scatter",
	"schedule",
	"schedules",
	"schema",
	"schemas",
	"scrub",
	"search",
	"second",
	"security",
	"security_barrier",
	"security_invoker",
	"seed",
	"select",
	"send",
	"sequence",
	"sequences",
	"serialfunc",
	"serializable",
	"server",
	"session",
	"sessions",
	"session_user",
	"set",
	"setof",
	"setting",
	"settings",
	"sfunc",
	"share",
	"shareable",
	"show",
	"similar",
	"simple",
	"skip",
	"skip_database_stats",
	"skip_locked",
	"skip_missing_foreign_keys",
	"skip_missing_sequences",
	"skip_missing_sequence_owners",
	"skip_missing_views",
	"smallint",
	"snapshot",
	"some",
	"sortop",
	"split",
	"sql",
	"sspace",
	"stable",
	"start",
	"statement",
	"statistics",
	"status",
	"stdin",
	"storage",
	"store",
	"stored",
	"strategy",
	"strict",
	"string",
	"stype",
	"subscript",
	"subscription",
	"substring",
	"subtype",
	"subtype_diff",
	"subtype_opclass",
	"superuser",
	"support",
	"symmetric",
	"syntax",
	"sysid",
	"system",
	"table",
	"tables",
	"tablespace",
	"temp",
	"template",
	"temporary",
	"text",
	"then",
	"throttling",
	"ties",
	"time",
	"timestamp",
	"timestamptz",
	"timetz",
	"to",
	"trace",
	"trailing",
	"transaction",
	"transactions",
	"transform",
	"treat",
	"trigger",
	"trim",
	"true",
	"truncate",
	"trusted",
	"type",
	"types",
	"typmod_in",
	"typmod_out",
	"unbounded",
	"uncommitted",
	"union",
	"unique",
	"unknown",
	"unlogged",
	"unsafe",
	"unsplit",
	"until",
	"update",
	"upsert",
	"usage",
	"use",
	"user",
	"users",
	"using",
	"vacuum",
	"valid",
	"validate",
	"validator",
	"value",
	"values",
	"varbit",
	"varchar",
	"variable",
	"variadic",
	"varying",
	"verbose",
	"version",
	"view",
	"viewactivity",
	"virtual",
	"volatile",
	"when",
	"where",
	"window",
	"with",
	"within",
	"without",
	"work",
	"wrapper",
	"write",
	"xml",
	"yaml",
	"year",
	"yes",
	"zone",
}

// GetKeywordID returns the lex id of the SQL keyword k or IDENT if k is
// not a keyword.
func GetKeywordID(k string) int32 {
	// The previous implementation generated a map that did a string ->
	// id lookup. Various ideas were benchmarked and the implementation below
	// was the fastest of those, between 3% and 10% faster (at parsing, so the
	// scanning speedup is even more) than the map implementation.
	switch k {
	case "abort":
		return ABORT
	case "access":
		return ACCESS
	case "action":
		return ACTION
	case "add":
		return ADD
	case "admin":
		return ADMIN
	case "after":
		return AFTER
	case "aggregate":
		return AGGREGATE
	case "alignment":
		return ALIGNMENT
	case "all":
		return ALL
	case "allow_connections":
		return ALLOW_CONNECTIONS
	case "alter":
		return ALTER
	case "always":
		return ALWAYS
	case "analyse":
		return ANALYSE
	case "analyze":
		return ANALYZE
	case "and":
		return AND
	case "annotate_type":
		return ANNOTATE_TYPE
	case "any":
		return ANY
	case "array":
		return ARRAY
	case "as":
		return AS
	case "asc":
		return ASC
	case "assignment":
		return ASSIGNMENT
	case "asymmetric":
		return ASYMMETRIC
	case "at":
		return AT
	case "atomic":
		return ATOMIC
	case "attach":
		return ATTACH
	case "attribute":
		return ATTRIBUTE
	case "authorization":
		return AUTHORIZATION
	case "auto":
		return AUTO
	case "automatic":
		return AUTOMATIC
	case "backup":
		return BACKUP
	case "backups":
		return BACKUPS
	case "basetype":
		return BASETYPE
	case "before":
		return BEFORE
	case "begin":
		return BEGIN
	case "between":
		return BETWEEN
	case "bigint":
		return BIGINT
	case "binary":
		return BINARY
	case "bit":
		return BIT
	case "boolean":
		return BOOLEAN
	case "both":
		return BOTH
	case "box2d":
		return BOX2D
	case "bpchar":
		return BPCHAR
	case "bucket_count":
		return BUCKET_COUNT
	case "buffer_usage_limit":
		return BUFFER_USAGE_LIMIT
	case "bundle":
		return BUNDLE
	case "by":
		return BY
	case "bypassrls":
		return BYPASSRLS
	case "cache":
		return CACHE
	case "call":
		return CALL
	case "called":
		return CALLED
	case "cancel":
		return CANCEL
	case "cancelquery":
		return CANCELQUERY
	case "canonical":
		return CANONICAL
	case "cascade":
		return CASCADE
	case "cascaded":
		return CASCADED
	case "case":
		return CASE
	case "cast":
		return CAST
	case "category":
		return CATEGORY
	case "chain":
		return CHAIN
	case "changefeed":
		return CHANGEFEED
	case "char":
		return CHAR
	case "character":
		return CHARACTER
	case "characteristics":
		return CHARACTERISTICS
	case "check":
		return CHECK
	case "check_option":
		return CHECK_OPTION
	case "class":
		return CLASS
	case "close":
		return CLOSE
	case "cluster":
		return CLUSTER
	case "coalesce":
		return COALESCE
	case "collatable":
		return COLLATABLE
	case "collate":
		return COLLATE
	case "collation":
		return COLLATION
	case "collation_version":
		return COLLATION_VERSION
	case "column":
		return COLUMN
	case "columns":
		return COLUMNS
	case "combinefunc":
		return COMBINEFUNC
	case "comment":
		return COMMENT
	case "comments":
		return COMMENTS
	case "commit":
		return COMMIT
	case "committed":
		return COMMITTED
	case "compact":
		return COMPACT
	case "complete":
		return COMPLETE
	case "compression":
		return COMPRESSION
	case "concurrently":
		return CONCURRENTLY
	case "configuration":
		return CONFIGURATION
	case "configurations":
		return CONFIGURATIONS
	case "configure":
		return CONFIGURE
	case "conflict":
		return CONFLICT
	case "connect":
		return CONNECT
	case "connection":
		return CONNECTION
	case "constraint":
		return CONSTRAINT
	case "constraints":
		return CONSTRAINTS
	case "controlchangefeed":
		return CONTROLCHANGEFEED
	case "controljob":
		return CONTROLJOB
	case "conversion":
		return CONVERSION
	case "convert":
		return CONVERT
	case "copy":
		return COPY
	case "cost":
		return COST
	case "create":
		return CREATE
	case "createdb":
		return CREATEDB
	case "createlogin":
		return CREATELOGIN
	case "createrole":
		return CREATEROLE
	case "cross":
		return CROSS
	case "csv":
		return CSV
	case "cube":
		return CUBE
	case "current":
		return CURRENT
	case "current_catalog":
		return CURRENT_CATALOG
	case "current_date":
		return CURRENT_DATE
	case "current_role":
		return CURRENT_ROLE
	case "current_schema":
		return CURRENT_SCHEMA
	case "current_time":
		return CURRENT_TIME
	case "current_timestamp":
		return CURRENT_TIMESTAMP
	case "current_user":
		return CURRENT_USER
	case "cycle":
		return CYCLE
	case "data":
		return DATA
	case "database":
		return DATABASE
	case "databases":
		return DATABASES
	case "day":
		return DAY
	case "deallocate":
		return DEALLOCATE
	case "dec":
		return DEC
	case "decimal":
		return DECIMAL
	case "declare":
		return DECLARE
	case "default":
		return DEFAULT
	case "defaults":
		return DEFAULTS
	case "deferrable":
		return DEFERRABLE
	case "deferred":
		return DEFERRED
	case "definer":
		return DEFINER
	case "delete":
		return DELETE
	case "delimiter":
		return DELIMITER
	case "depends":
		return DEPENDS
	case "desc":
		return DESC
	case "describe":
		return DESCRIBE
	case "deserialfunc":
		return DESERIALFUNC
	case "destination":
		return DESTINATION
	case "detach":
		return DETACH
	case "detached":
		return DETACHED
	case "dictionary":
		return DICTIONARY
	case "disable":
		return DISABLE
	case "disable_page_skipping":
		return DISABLE_PAGE_SKIPPING
	case "discard":
		return DISCARD
	case "distinct":
		return DISTINCT
	case "do":
		return DO
	case "domain":
		return DOMAIN
	case "double":
		return DOUBLE
	case "drop":
		return DROP
	case "each":
		return EACH
	case "element":
		return ELEMENT
	case "else":
		return ELSE
	case "enable":
		return ENABLE
	case "encoding":
		return ENCODING
	case "encrypted":
		return ENCRYPTED
	case "encryption_passphrase":
		return ENCRYPTION_PASSPHRASE
	case "end":
		return END
	case "enum":
		return ENUM
	case "enums":
		return ENUMS
	case "escape":
		return ESCAPE
	case "event":
		return EVENT
	case "except":
		return EXCEPT
	case "exclude":
		return EXCLUDE
	case "excluding":
		return EXCLUDING
	case "execute":
		return EXECUTE
	case "execution":
		return EXECUTION
	case "exists":
		return EXISTS
	case "experimental":
		return EXPERIMENTAL
	case "experimental_audit":
		return EXPERIMENTAL_AUDIT
	case "experimental_fingerprints":
		return EXPERIMENTAL_FINGERPRINTS
	case "experimental_replica":
		return EXPERIMENTAL_REPLICA
	case "expiration":
		return EXPIRATION
	case "explain":
		return EXPLAIN
	case "export":
		return EXPORT
	case "expression":
		return EXPRESSION
	case "extended":
		return EXTENDED
	case "extension":
		return EXTENSION
	case "external":
		return EXTERNAL
	case "extract":
		return EXTRACT
	case "extract_duration":
		return EXTRACT_DURATION
	case "false":
		return FALSE
	case "family":
		return FAMILY
	case "fetch":
		return FETCH
	case "files":
		return FILES
	case "filter":
		return FILTER
	case "finalfunc":
		return FINALFUNC
	case "finalfunc_extra":
		return FINALFUNC_EXTRA
	case "finalfunc_modify":
		return FINALFUNC_MODIFY
	case "finalize":
		return FINALIZE
	case "first":
		return FIRST
	case "float":
		return FLOAT
	case "following":
		return FOLLOWING
	case "for":
		return FOR
	case "force":
		return FORCE
	case "force_index":
		return FORCE_INDEX
	case "foreign":
		return FOREIGN
	case "format":
		return FORMAT
	case "freeze":
		return FREEZE
	case "from":
		return FROM
	case "full":
		return FULL
	case "function":
		return FUNCTION
	case "functions":
		return FUNCTIONS
	case "generated":
		return GENERATED
	case "geography":
		return GEOGRAPHY
	case "geometry":
		return GEOMETRY
	case "geometrycollection":
		return GEOMETRYCOLLECTION
	case "geometrycollectionm":
		return GEOMETRYCOLLECTIONM
	case "geometrycollectionz":
		return GEOMETRYCOLLECTIONZ
	case "geometrycollectionzm":
		return GEOMETRYCOLLECTIONZM
	case "geometrym":
		return GEOMETRYM
	case "geometryz":
		return GEOMETRYZ
	case "geometryzm":
		return GEOMETRYZM
	case "global":
		return GLOBAL
	case "grant":
		return GRANT
	case "granted":
		return GRANTED
	case "grants":
		return GRANTS
	case "greatest":
		return GREATEST
	case "group":
		return GROUP
	case "grouping":
		return GROUPING
	case "groups":
		return GROUPS
	case "handler":
		return HANDLER
	case "hash":
		return HASH
	case "having":
		return HAVING
	case "header":
		return HEADER
	case "high":
		return HIGH
	case "hint":
		return HINT
	case "histogram":
		return HISTOGRAM
	case "hour":
		return HOUR
	case "hypothetical":
		return HYPOTHETICAL
	case "icu_locale":
		return ICU_LOCALE
	case "icu_rules":
		return ICU_RULES
	case "identity":
		return IDENTITY
	case "if":
		return IF
	case "iferror":
		return IFERROR
	case "ifnull":
		return IFNULL
	case "ignore_foreign_keys":
		return IGNORE_FOREIGN_KEYS
	case "ilike":
		return ILIKE
	case "immediate":
		return IMMEDIATE
	case "immutable":
		return IMMUTABLE
	case "implicit":
		return IMPLICIT
	case "import":
		return IMPORT
	case "in":
		return IN
	case "include":
		return INCLUDE
	case "including":
		return INCLUDING
	case "increment":
		return INCREMENT
	case "incremental":
		return INCREMENTAL
	case "index":
		return INDEX
	case "indexes":
		return INDEXES
	case "index_cleanup":
		return INDEX_CLEANUP
	case "inherit":
		return INHERIT
	case "inherits":
		return INHERITS
	case "initcond":
		return INITCOND
	case "initially":
		return INITIALLY
	case "inject":
		return INJECT
	case "inline":
		return INLINE
	case "inner":
		return INNER
	case "inout":
		return INOUT
	case "input":
		return INPUT
	case "insert":
		return INSERT
	case "instead":
		return INSTEAD
	case "int":
		return INT
	case "integer":
		return INTEGER
	case "interleave":
		return INTERLEAVE
	case "internallength":
		return INTERNALLENGTH
	case "intersect":
		return INTERSECT
	case "interval":
		return INTERVAL
	case "into":
		return INTO
	case "into_db":
		return INTO_DB
	case "inverted":
		return INVERTED
	case "invoker":
		return INVOKER
	case "is":
		return IS
	case "iserror":
		return ISERROR
	case "isnull":
		return ISNULL
	case "isolation":
		return ISOLATION
	case "is_template":
		return IS_TEMPLATE
	case "job":
		return JOB
	case "jobs":
		return JOBS
	case "join":
		return JOIN
	case "json":
		return JSON
	case "key":
		return KEY
	case "keys":
		return KEYS
	case "kms":
		return KMS
	case "kv":
		return KV
	case "language":
		return LANGUAGE
	case "large":
		return LARGE
	case "last":
		return LAST
	case "lateral":
		return LATERAL
	case "latest":
		return LATEST
	case "lc_collate":
		return LC_COLLATE
	case "lc_ctype":
		return LC_CTYPE
	case "leading":
		return LEADING
	case "leakproof":
		return LEAKPROOF
	case "lease":
		return LEASE
	case "least":
		return LEAST
	case "left":
		return LEFT
	case "less":
		return LESS
	case "level":
		return LEVEL
	case "like":
		return LIKE
	case "limit":
		return LIMIT
	case "linestring":
		return LINESTRING
	case "list":
		return LIST
	case "local":
		return LOCAL
	case "locale":
		return LOCALE
	case "locale_provider":
		return LOCALE_PROVIDER
	case "localtime":
		return LOCALTIME
	case "localtimestamp":
		return LOCALTIMESTAMP
	case "locked":
		return LOCKED
	case "logged":
		return LOGGED
	case "login":
		return LOGIN
	case "lookup":
		return LOOKUP
	case "low":
		return LOW
	case "main":
		return MAIN
	case "match":
		return MATCH
	case "materialized":
		return MATERIALIZED
	case "maxvalue":
		return MAXVALUE
	case "merge":
		return MERGE
	case "method":
		return METHOD
	case "mfinalfunc":
		return MFINALFUNC
	case "mfinalfunc_extra":
		return MFINALFUNC_EXTRA
	case "mfinalfunc_modify":
		return MFINALFUNC_MODIFY
	case "minitcond":
		return MINITCOND
	case "minute":
		return MINUTE
	case "minvalue":
		return MINVALUE
	case "minvfunc":
		return MINVFUNC
	case "modifyclustersetting":
		return MODIFYCLUSTERSETTING
	case "modulus":
		return MODULUS
	case "month":
		return MONTH
	case "msfunc":
		return MSFUNC
	case "mspace":
		return MSPACE
	case "msspace":
		return MSSPACE
	case "mstype":
		return MSTYPE
	case "multilinestring":
		return MULTILINESTRING
	case "multilinestringm":
		return MULTILINESTRINGM
	case "multilinestringz":
		return MULTILINESTRINGZ
	case "multilinestringzm":
		return MULTILINESTRINGZM
	case "multipoint":
		return MULTIPOINT
	case "multipointm":
		return MULTIPOINTM
	case "multipointz":
		return MULTIPOINTZ
	case "multipointzm":
		return MULTIPOINTZM
	case "multipolygon":
		return MULTIPOLYGON
	case "multipolygonm":
		return MULTIPOLYGONM
	case "multipolygonz":
		return MULTIPOLYGONZ
	case "multipolygonzm":
		return MULTIPOLYGONZM
	case "multirange_type_name":
		return MULTIRANGE_TYPE_NAME
	case "name":
		return NAME
	case "names":
		return NAMES
	case "nan":
		return NAN
	case "natural":
		return NATURAL
	case "never":
		return NEVER
	case "new":
		return NEW
	case "next":
		return NEXT
	case "no":
		return NO
	case "nobypassrls":
		return NOBYPASSRLS
	case "nocancelquery":
		return NOCANCELQUERY
	case "nocontrolchangefeed":
		return NOCONTROLCHANGEFEED
	case "nocontroljob":
		return NOCONTROLJOB
	case "nocreatedb":
		return NOCREATEDB
	case "nocreatelogin":
		return NOCREATELOGIN
	case "nocreaterole":
		return NOCREATEROLE
	case "noinherit":
		return NOINHERIT
	case "nologin":
		return NOLOGIN
	case "nomodifyclustersetting":
		return NOMODIFYCLUSTERSETTING
	case "none":
		return NONE
	case "noreplication":
		return NOREPLICATION
	case "normal":
		return NORMAL
	case "nosuperuser":
		return NOSUPERUSER
	case "not":
		return NOT
	case "nothing":
		return NOTHING
	case "notnull":
		return NOTNULL
	case "noviewactivity":
		return NOVIEWACTIVITY
	case "nowait":
		return NOWAIT
	case "no_index_join":
		return NO_INDEX_JOIN
	case "null":
		return NULL
	case "nullif":
		return NULLIF
	case "nulls":
		return NULLS
	case "numeric":
		return NUMERIC
	case "object":
		return OBJECT
	case "of":
		return OF
	case "off":
		return OFF
	case "offset":
		return OFFSET
	case "oid":
		return OID
	case "oids":
		return OIDS
	case "old":
		return OLD
	case "on":
		return ON
	case "only":
		return ONLY
	case "only_database_stats":
		return ONLY_DATABASE_STATS
	case "operator":
		return OPERATOR
	case "opt":
		return OPT
	case "option":
		return OPTION
	case "options":
		return OPTIONS
	case "or":
		return OR
	case "order":
		return ORDER
	case "ordinality":
		return ORDINALITY
	case "others":
		return OTHERS
	case "out":
		return OUT
	case "outer":
		return OUTER
	case "output":
		return OUTPUT
	case "over":
		return OVER
	case "overlaps":
		return OVERLAPS
	case "overlay":
		return OVERLAY
	case "owned":
		return OWNED
	case "owner":
		return OWNER
	case "parallel":
		return PARALLEL
	case "parameter":
		return PARAMETER
	case "parent":
		return PARENT
	case "parser":
		return PARSER
	case "partial":
		return PARTIAL
	case "partition":
		return PARTITION
	case "partitions":
		return PARTITIONS
	case "passedbyvalue":
		return PASSEDBYVALUE
	case "password":
		return PASSWORD
	case "pause":
		return PAUSE
	case "paused":
		return PAUSED
	case "physical":
		return PHYSICAL
	case "placing":
		return PLACING
	case "plain":
		return PLAIN
	case "plan":
		return PLAN
	case "plans":
		return PLANS
	case "point":
		return POINT
	case "pointm":
		return POINTM
	case "pointz":
		return POINTZ
	case "pointzm":
		return POINTZM
	case "policy":
		return POLICY
	case "polygon":
		return POLYGON
	case "polygonm":
		return POLYGONM
	case "polygonz":
		return POLYGONZ
	case "polygonzm":
		return POLYGONZM
	case "position":
		return POSITION
	case "preceding":
		return PRECEDING
	case "precision":
		return PRECISION
	case "preferred":
		return PREFERRED
	case "prepare":
		return PREPARE
	case "preserve":
		return PRESERVE
	case "primary":
		return PRIMARY
	case "priority":
		return PRIORITY
	case "privileges":
		return PRIVILEGES
	case "procedural":
		return PROCEDURAL
	case "procedure":
		return PROCEDURE
	case "procedures":
		return PROCEDURES
	case "process_main":
		return PROCESS_MAIN
	case "process_toast":
		return PROCESS_TOAST
	case "public":
		return PUBLIC
	case "publication":
		return PUBLICATION
	case "queries":
		return QUERIES
	case "query":
		return QUERY
	case "range":
		return RANGE
	case "ranges":
		return RANGES
	case "read":
		return READ
	case "read_only":
		return READ_ONLY
	case "read_write":
		return READ_WRITE
	case "real":
		return REAL
	case "receive":
		return RECEIVE
	case "recurring":
		return RECURRING
	case "recursive":
		return RECURSIVE
	case "ref":
		return REF
	case "references":
		return REFERENCES
	case "referencing":
		return REFERENCING
	case "refresh":
		return REFRESH
	case "reindex":
		return REINDEX
	case "release":
		return RELEASE
	case "remainder":
		return REMAINDER
	case "rename":
		return RENAME
	case "repeatable":
		return REPEATABLE
	case "replace":
		return REPLACE
	case "replica":
		return REPLICA
	case "replication":
		return REPLICATION
	case "reset":
		return RESET
	case "restart":
		return RESTART
	case "restore":
		return RESTORE
	case "restrict":
		return RESTRICT
	case "restricted":
		return RESTRICTED
	case "resume":
		return RESUME
	case "retry":
		return RETRY
	case "return":
		return RETURN
	case "returning":
		return RETURNING
	case "returns":
		return RETURNS
	case "revision_history":
		return REVISION_HISTORY
	case "revoke":
		return REVOKE
	case "right":
		return RIGHT
	case "role":
		return ROLE
	case "roles":
		return ROLES
	case "rollback":
		return ROLLBACK
	case "rollup":
		return ROLLUP
	case "routine":
		return ROUTINE
	case "routines":
		return ROUTINES
	case "row":
		return ROW
	case "rows":
		return ROWS
	case "rule":
		return RULE
	case "running":
		return RUNNING
	case "safe":
		return SAFE
	case "savepoint":
		return SAVEPOINT
	case "scatter":
		return SCATTER
	case "schedule":
		return SCHEDULE
	case "schedules":
		return SCHEDULES
	case "schema":
		return SCHEMA
	case "schemas":
		return SCHEMAS
	case "scrub":
		return SCRUB
	case "search":
		return SEARCH
	case "second":
		return SECOND
	case "security":
		return SECURITY
	case "security_barrier":
		return SECURITY_BARRIER
	case "security_invoker":
		return SECURITY_INVOKER
	case "seed":
		return SEED
	case "select":
		return SELECT
	case "send":
		return SEND
	case "sequence":
		return SEQUENCE
	case "sequences":
		return SEQUENCES
	case "serialfunc":
		return SERIALFUNC
	case "serializable":
		return SERIALIZABLE
	case "server":
		return SERVER
	case "session":
		return SESSION
	case "sessions":
		return SESSIONS
	case "session_user":
		return SESSION_USER
	case "set":
		return SET
	case "setof":
		return SETOF
	case "setting":
		return SETTING
	case "settings":
		return SETTINGS
	case "sfunc":
		return SFUNC
	case "share":
		return SHARE
	case "shareable":
		return SHAREABLE
	case "show":
		return SHOW
	case "similar":
		return SIMILAR
	case "simple":
		return SIMPLE
	case "skip":
		return SKIP
	case "skip_database_stats":
		return SKIP_DATABASE_STATS
	case "skip_locked":
		return SKIP_LOCKED
	case "skip_missing_foreign_keys":
		return SKIP_MISSING_FOREIGN_KEYS
	case "skip_missing_sequences":
		return SKIP_MISSING_SEQUENCES
	case "skip_missing_sequence_owners":
		return SKIP_MISSING_SEQUENCE_OWNERS
	case "skip_missing_views":
		return SKIP_MISSING_VIEWS
	case "smallint":
		return SMALLINT
	case "snapshot":
		return SNAPSHOT
	case "some":
		return SOME
	case "sortop":
		return SORTOP
	case "split":
		return SPLIT
	case "sql":
		return SQL
	case "sspace":
		return SSPACE
	case "stable":
		return STABLE
	case "start":
		return START
	case "statement":
		return STATEMENT
	case "statistics":
		return STATISTICS
	case "status":
		return STATUS
	case "stdin":
		return STDIN
	case "storage":
		return STORAGE
	case "store":
		return STORE
	case "stored":
		return STORED
	case "strategy":
		return STRATEGY
	case "strict":
		return STRICT
	case "string":
		return STRING
	case "stype":
		return STYPE
	case "subscript":
		return SUBSCRIPT
	case "subscription":
		return SUBSCRIPTION
	case "substring":
		return SUBSTRING
	case "subtype":
		return SUBTYPE
	case "subtype_diff":
		return SUBTYPE_DIFF
	case "subtype_opclass":
		return SUBTYPE_OPCLASS
	case "superuser":
		return SUPERUSER
	case "support":
		return SUPPORT
	case "symmetric":
		return SYMMETRIC
	case "syntax":
		return SYNTAX
	case "sysid":
		return SYSID
	case "system":
		return SYSTEM
	case "table":
		return TABLE
	case "tables":
		return TABLES
	case "tablespace":
		return TABLESPACE
	case "temp":
		return TEMP
	case "template":
		return TEMPLATE
	case "temporary":
		return TEMPORARY
	case "text":
		return TEXT
	case "then":
		return THEN
	case "throttling":
		return THROTTLING
	case "ties":
		return TIES
	case "time":
		return TIME
	case "timestamp":
		return TIMESTAMP
	case "timestamptz":
		return TIMESTAMPTZ
	case "timetz":
		return TIMETZ
	case "to":
		return TO
	case "trace":
		return TRACE
	case "trailing":
		return TRAILING
	case "transaction":
		return TRANSACTION
	case "transactions":
		return TRANSACTIONS
	case "transform":
		return TRANSFORM
	case "treat":
		return TREAT
	case "trigger":
		return TRIGGER
	case "trim":
		return TRIM
	case "true":
		return TRUE
	case "truncate":
		return TRUNCATE
	case "trusted":
		return TRUSTED
	case "type":
		return TYPE
	case "types":
		return TYPES
	case "typmod_in":
		return TYPMOD_IN
	case "typmod_out":
		return TYPMOD_OUT
	case "unbounded":
		return UNBOUNDED
	case "uncommitted":
		return UNCOMMITTED
	case "union":
		return UNION
	case "unique":
		return UNIQUE
	case "unknown":
		return UNKNOWN
	case "unlogged":
		return UNLOGGED
	case "unsafe":
		return UNSAFE
	case "unsplit":
		return UNSPLIT
	case "until":
		return UNTIL
	case "update":
		return UPDATE
	case "upsert":
		return UPSERT
	case "usage":
		return USAGE
	case "use":
		return USE
	case "user":
		return USER
	case "users":
		return USERS
	case "using":
		return USING
	case "vacuum":
		return VACUUM
	case "valid":
		return VALID
	case "validate":
		return VALIDATE
	case "validator":
		return VALIDATOR
	case "value":
		return VALUE
	case "values":
		return VALUES
	case "varbit":
		return VARBIT
	case "varchar":
		return VARCHAR
	case "variable":
		return VARIABLE
	case "variadic":
		return VARIADIC
	case "varying":
		return VARYING
	case "verbose":
		return VERBOSE
	case "version":
		return VERSION
	case "view":
		return VIEW
	case "viewactivity":
		return VIEWACTIVITY
	case "virtual":
		return VIRTUAL
	case "volatile":
		return VOLATILE
	case "when":
		return WHEN
	case "where":
		return WHERE
	case "window":
		return WINDOW
	case "with":
		return WITH
	case "within":
		return WITHIN
	case "without":
		return WITHOUT
	case "work":
		return WORK
	case "wrapper":
		return WRAPPER
	case "write":
		return WRITE
	case "xml":
		return XML
	case "yaml":
		return YAML
	case "year":
		return YEAR
	case "yes":
		return YES
	case "zone":
		return ZONE
	default:
		return IDENT
	}
}
