export const countFields = [
  {
    name: "count",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltAddFields = [
  {
    name: "dolt_add",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1009,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltResetFields = [
  {
    name: "dolt_reset",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1009,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltBranchFields = [
  {
    name: "dolt_branch",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1009,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltCheckoutFields = [
  {
    name: "dolt_checkout",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1009,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltCleanFields = [
  {
    name: "dolt_clean",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1009,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltCommitFields = [
  {
    name: "dolt_commit",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1009,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltStatusFields = [
  {
    name: "table_name",
    tableID: 0,
    columnID: 0,
    dataTypeID: 25,
    dataTypeSize: -4,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "staged",
    tableID: 0,
    columnID: 0,
    dataTypeID: 21,
    dataTypeSize: 4,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "status",
    tableID: 0,
    columnID: 0,
    dataTypeID: 25,
    dataTypeSize: -4,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const infoSchemaKeyColumnUsageFields = [
  {
    name: "CONSTRAINT_CATALOG",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "CONSTRAINT_SCHEMA",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "CONSTRAINT_NAME",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "TABLE_CATALOG",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "TABLE_SCHEMA",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "TABLE_NAME",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "COLUMN_NAME",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "ORDINAL_POSITION",
    tableID: 0,
    columnID: 0,
    dataTypeID: 26,
    dataTypeSize: 10,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "POSITION_IN_UNIQUE_CONSTRAINT",
    tableID: 0,
    columnID: 0,
    dataTypeID: 26,
    dataTypeSize: 10,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "REFERENCED_TABLE_SCHEMA",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "REFERENCED_TABLE_NAME",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "REFERENCED_COLUMN_NAME",
    tableID: 0,
    columnID: 0,
    dataTypeID: 1043,
    dataTypeSize: 192,
    dataTypeModifier: -1,
    format: "text",
  },
];

export const doltDiffStatFields = [
  {
    name: "table_name",
    tableID: 0,
    columnID: 0,
    dataTypeID: 25,
    dataTypeSize: -1,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "rows_unmodified",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "rows_added",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "rows_deleted",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "rows_modified",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "cells_added",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "cells_deleted",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "cells_modified",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "old_row_count",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "new_row_count",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "old_cell_count",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
  {
    name: "new_cell_count",
    tableID: 0,
    columnID: 0,
    dataTypeID: 20,
    dataTypeSize: 20,
    dataTypeModifier: -1,
    format: "text",
  },
];
