[package]
name = "doltdb"
description = "A Doltgres database's version-controlled data: refs, commits, working sets, root values, and tables"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
objects = { path = "../objects" }
prolly = { path = "../prolly" }
serial = { path = "../serial" }
sha2 = "0.10"
store = { path = "../store" }

[lints]
workspace = true
