// Code generated by "stringer -type=CreateTypeVariety"; DO NOT EDIT.

package tree

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Composite-1]
	_ = x[Enum-2]
	_ = x[Range-3]
	_ = x[Base-4]
	_ = x[Shell-5]
	_ = x[Domain-6]
}

const _CreateTypeVariety_name = "CompositeEnumRangeBaseShellDomain"

var _CreateTypeVariety_index = [...]uint8{0, 9, 13, 18, 22, 27, 33}

func (i CreateTypeVariety) String() string {
	i -= 1
	if i < 0 || i >= CreateTypeVariety(len(_CreateTypeVariety_index)-1) {
		return "CreateTypeVariety(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CreateTypeVariety_name[_CreateTypeVariety_index[i]:_CreateTypeVariety_index[i+1]]
}
