// Code generated by "stringer -type=StatementType"; DO NOT EDIT.

package tree

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ack-0]
	_ = x[DDL-1]
	_ = x[RowsAffected-2]
	_ = x[Rows-3]
	_ = x[CopyIn-4]
	_ = x[CopyOut-5]
	_ = x[Unknown-6]
}

const _StatementType_name = "AckDDLRowsAffectedRowsCopyInCopyOutUnknown"

var _StatementType_index = [...]uint8{0, 3, 6, 18, 22, 28, 35, 42}

func (i StatementType) String() string {
	if i < 0 || i >= StatementType(len(_StatementType_index)-1) {
		return "StatementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatementType_name[_StatementType_index[i]:_StatementType_index[i+1]]
}
