// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 1660
	`ALTER`: {
		//line sql.y: 1661
		Category: hGroup,
		//line sql.y: 1662
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE
`,
	},
	//line sql.y: 1687
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 1688
		Category: hDDL,
		//line sql.y: 1689
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SET SCHEMA <newschemaname>

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

`,
		//line sql.y: 1711
		SeeAlso: `WEBDOCS/alter-table.html
`,
	},
	//line sql.y: 1722
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 1723
		Category: hDDL,
		//line sql.y: 1724
		Text: `
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> RENAME TO <newname>
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
		//line sql.y: 1727
		SeeAlso: `WEBDOCS/alter-view.html
`,
	},
	//line sql.y: 1771
	`ALTER SEQUENCE`: {
		ShortDescription: `change the definition of a sequence`,
		//line sql.y: 1772
		Category: hDDL,
		//line sql.y: 1773
		Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START <start>]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
ALTER SEQUENCE [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
	},
	//line sql.y: 1815
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 1816
		Category: hDDL,
		//line sql.y: 1817
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
ALTER DATABASE <name> OWNER TO <newowner>
`,
		//line sql.y: 1820
		SeeAlso: `WEBDOCS/alter-database.html
`,
	},
	//line sql.y: 1991
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 1992
		Category: hDDL,
		//line sql.y: 1993
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>

`,
		//line sql.y: 1999
		SeeAlso: `WEBDOCS/alter-index.html
`,
	},
	//line sql.y: 2719
	`ALTER TYPE`: {
		ShortDescription: `change the definition of a type.`,
		//line sql.y: 2720
		Category: hDDL,
		//line sql.y: 2721
		Text: `ALTER TYPE <typename> <command>

Commands:
  ALTER TYPE ... ADD VALUE [IF NOT EXISTS] <value> [ { BEFORE | AFTER } <value> ]
  ALTER TYPE ... RENAME VALUE <oldname> TO <newname>
  ALTER TYPE ... RENAME TO <newname>
  ALTER TYPE ... SET SCHEMA <newschemaname>
  ALTER TYPE ... OWNER TO {<newowner> | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
  ALTER TYPE ... RENAME ATTRIBUTE <oldname> TO <newname> [ CASCADE | RESTRICT ]
  ALTER TYPE ... <attributeaction> [, ... ]

Attribute action:
  ADD ATTRIBUTE <name> <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]
  DROP ATTRIBUTE [IF EXISTS] <name> [ CASCADE | RESTRICT ]
  ALTER ATTRIBUTE <name> [ SET DATA ] TYPE <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]

`,
		//line sql.y: 2737
		SeeAlso: `WEBDOCS/alter-type.html
`,
	},
	//line sql.y: 3107
	`REFRESH`: {
		ShortDescription: `recalculate a materialized view`,
		//line sql.y: 3108
		Category: hMisc,
		//line sql.y: 3109
		Text: `
REFRESH MATERIALIZED VIEW [CONCURRENTLY] view_name [WITH [NO] DATA]
`,
	},
	//line sql.y: 3136
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 3137
		Category: hCCL,
		//line sql.y: 3138
		Text: `
BACKUP <targets...> TO <location...>
       [ AS OF SYSTEM TIME <expr> ]
       [ INCREMENTAL FROM <location...> ]
       [ WITH <option> [= <value>] [, ...] ]

Targets:
   Empty targets list: backup full cluster.
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Location:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   revision_history: enable revision history
   encryption_passphrase="secret": encrypt backups
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : encrypt backups using KMS
   detached: execute backup job asynchronously, without waiting for its completion

`,
		//line sql.y: 3158
		SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
	},
	//line sql.y: 3262
	`CREATE SCHEDULE FOR BACKUP`: {
		ShortDescription: `backup data periodically`,
		//line sql.y: 3263
		Category: hCCL,
		//line sql.y: 3264
		Text: `
CREATE SCHEDULE [<description>]
FOR BACKUP [<targets>] TO <location...>
[WITH <backup_option>[=<value>] [, ...]]
RECURRING [crontab|NEVER] [FULL BACKUP <crontab|ALWAYS>]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]

All backups run in UTC timezone.

Description:
  Optional description (or name) for this schedule

Targets:
  empty targets: Backup entire cluster
  DATABASE <pattern> [, ...]: comma separated list of databases to backup.
  TABLE <pattern> [, ...]: comma separated list of tables to backup.

Location:
  "[scheme]://[host]/[path prefix to backup]?[parameters]"
  Backup schedule will create subdirectories under this location to store
  full and periodic backups.

WITH <options>:
  Options specific to BACKUP: See BACKUP options

RECURRING <crontab>:
  The RECURRING expression specifies when we backup.  By default these are incremental
  backups that capture changes since the last backup, writing to the "current" backup.

  Schedule specified as a string in crontab format.
  All times in UTC.
    "5 0 * * *": run schedule 5 minutes past midnight.
    "@daily": run daily, at midnight
  See https://en.wikipedia.org/wiki/Cron

FULL BACKUP <crontab|ALWAYS>:
  The optional FULL BACKUP '<cron expr>' clause specifies when we'll start a new full backup,
  which becomes the "current" backup when complete.
  If FULL BACKUP ALWAYS is specified, then the backups triggered by the RECURRING clause will
  always be full backups. For free users, this is the only accepted value of FULL BACKUP.

  If the FULL BACKUP clause is omitted, we will select a reasonable default:
     * RECURRING <= 1 hour: we default to FULL BACKUP '@daily';
     * RECURRING <= 1 day:  we default to FULL BACKUP '@weekly';
     * Otherwise: we default to FULL BACKUP ALWAYS.

 SCHEDULE OPTIONS:
  The schedule can be modified by specifying the following options (which are considered
  to be experimental at this time):
  * first_run=TIMESTAMPTZ:
    execute the schedule at the specified time. If not specified, the default is to execute
    the scheduled based on it's next RECURRING time.
  * on_execution_failure='[retry|reschedule|pause]':
    If an error occurs during the execution, handle the error based as:
    * retry: retry execution right away
    * reschedule: retry execution by rescheduling it based on its RECURRING expression.
      This is the default.
    * pause: pause this schedule.  Requires manual intervention to unpause.
  * on_previous_running='[start|skip|wait]':
    If the previous backup started by this schedule still running, handle this as:
    * start: start this execution anyway, even if the previous one still running.
    * skip: skip this execution, reschedule it based on RECURRING (or change_capture_period)
      expression.
    * wait: wait for the previous execution to complete.  This is the default.
  * ignore_existing_backups
    If backups were already created in the destination in which a new schedule references,
    this flag must be passed in to acknowledge that the new schedule may be backing up different
    objects.

`,
		//line sql.y: 3333
		SeeAlso: `BACKUP
`,
	},
	//line sql.y: 3411
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 3412
		Category: hCCL,
		//line sql.y: 3413
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   into_db: specify target database
   skip_missing_foreign_keys: remove foreign key constraints before restoring
   skip_missing_sequences: ignore sequence dependencies
   skip_missing_views: skip restoring views because of dependencies that cannot be restored
   skip_missing_sequence_owners: remove sequence-table ownership dependencies before restoring
   encryption_passphrase=passphrase: decrypt BACKUP with specified passphrase
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : decrypt backups using KMS
   detached: execute restore job asynchronously, without waiting for its completion
`,
		//line sql.y: 3434
		SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
	},
	//line sql.y: 3555
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 3556
		Category: hCCL,
		//line sql.y: 3557
		Text: `
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

-- Import using specific schema, use only table data from external file:
IMPORT TABLE <tablename>
       { ( <elements> ) | CREATE USING <schemafile> }
       <format>
       DATA ( <datafile> [, ...] )
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   CSV
   DELIMITED
   MYSQLDUMP
   PGCOPY
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'
   delimiter = '...'      [CSV, PGCOPY-specific]
   nullif = '...'         [CSV, PGCOPY-specific]
   comment = '...'        [CSV-specific]

`,
		//line sql.y: 3585
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 3629
	`EXPORT`: {
		ShortDescription: `export data to file in a distributed manner`,
		//line sql.y: 3630
		Category: hCCL,
		//line sql.y: 3631
		Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV

Options:
   delimiter = '...'   [CSV-specific]

`,
		//line sql.y: 3640
		SeeAlso: `SELECT
`,
	},
	//line sql.y: 3722
	`CALL`: {
		ShortDescription: `invoke a procedure`,
		//line sql.y: 3723
		Category: hMisc,
		//line sql.y: 3724
		Text: `CALL <name> ( [ <expr> [, ...] ] )
`,
		//line sql.y: 3725
		SeeAlso: `CREATE PROCEDURE
`,
	},
	//line sql.y: 3959
	`CANCEL`: {
		//line sql.y: 3960
		Category: hGroup,
		//line sql.y: 3961
		Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
	},
	//line sql.y: 3968
	`CANCEL JOBS`: {
		ShortDescription: `cancel background jobs`,
		//line sql.y: 3969
		Category: hMisc,
		//line sql.y: 3970
		Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
		//line sql.y: 3973
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 3995
	`CANCEL QUERIES`: {
		ShortDescription: `cancel running queries`,
		//line sql.y: 3996
		Category: hMisc,
		//line sql.y: 3997
		Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
		//line sql.y: 4000
		SeeAlso: `SHOW QUERIES
`,
	},
	//line sql.y: 4031
	`CANCEL SESSIONS`: {
		ShortDescription: `cancel open sessions`,
		//line sql.y: 4032
		Category: hMisc,
		//line sql.y: 4033
		Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
		//line sql.y: 4036
		SeeAlso: `SHOW SESSIONS
`,
	},
	//line sql.y: 4284
	`CREATE`: {
		//line sql.y: 4285
		Category: hGroup,
		//line sql.y: 4286
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE, CREATE TYPE, CREATE CAST
`,
	},
	//line sql.y: 4433
	`CREATE OPERATOR`: {
		ShortDescription: `define a new operator`,
		//line sql.y: 4434
		Category: hDDL,
		//line sql.y: 4435
		Text: `CREATE OPERATOR name (
         {FUNCTION|PROCEDURE} = function_name
         [, LEFTARG = left_type ] [, RIGHTARG = right_type ]
         [, COMMUTATOR = com_op ] [, NEGATOR = neg_op ]
         [, RESTRICT = res_proc ] [, JOIN = join_proc ]
         [, HASHES ] [, MERGES ]
       )
`,
		//line sql.y: 4442
		SeeAlso: `WEBDOCS/sql-createoperator.html
`,
	},
	//line sql.y: 4476
	`CREATE CAST`: {
		ShortDescription: `define a new cast`,
		//line sql.y: 4477
		Category: hDDL,
		//line sql.y: 4478
		Text: `CREATE CAST (source_type AS target_type) WITH FUNCTION function_name [ (argument_type [, ...]) ] [ AS ASSIGNMENT | AS IMPLICIT ]
       CREATE CAST (source_type AS target_type) WITHOUT FUNCTION [ AS ASSIGNMENT | AS IMPLICIT ]
       CREATE CAST (source_type AS target_type) WITH INOUT [ AS ASSIGNMENT | AS IMPLICIT ]
`,
		//line sql.y: 4481
		SeeAlso: `WEBDOCS/sql-createcast.html
`,
	},
	//line sql.y: 5056
	`DROP OPERATOR`: {
		ShortDescription: `remove an operator`,
		//line sql.y: 5057
		Category: hDDL,
		//line sql.y: 5058
		Text: `DROP OPERATOR [ IF EXISTS ] name ( { left_type | NONE } , right_type ) [, ...] [ CASCADE | RESTRICT ]
`,
		//line sql.y: 5059
		SeeAlso: `WEBDOCS/sql-dropoperator.html
`,
	},
	//line sql.y: 5166
	`CREATE STATISTICS`: {
		ShortDescription: `create a new table statistic`,
		//line sql.y: 5167
		Category: hMisc,
		//line sql.y: 5168
		Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
	},
	//line sql.y: 5311
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 5312
		Category: hDML,
		//line sql.y: 5313
		Text: `DELETE FROM <tablename> [WHERE <expr>]
              [ORDER BY <exprs...>]
              [LIMIT <expr>]
              [RETURNING <exprs...>]
`,
		//line sql.y: 5317
		SeeAlso: `WEBDOCS/delete.html
`,
	},
	//line sql.y: 5336
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 5337
		Category: hCfg,
		//line sql.y: 5338
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 5350
	`DROP`: {
		//line sql.y: 5351
		Category: hGroup,
		//line sql.y: 5352
		Text: `
DROP CAST, DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE, DROP TYPE
`,
	},
	//line sql.y: 5380
	`DROP CAST`: {
		ShortDescription: `remove a cast`,
		//line sql.y: 5381
		Category: hDDL,
		//line sql.y: 5382
		Text: `DROP CAST [ IF EXISTS ] (source_type AS target_type) [ CASCADE | RESTRICT ]
`,
		//line sql.y: 5383
		SeeAlso: `WEBDOCS/sql-dropcast.html
`,
	},
	//line sql.y: 5397
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 5398
		Category: hDDL,
		//line sql.y: 5399
		Text: `DROP [MATERIALIZED] VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5400
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 5430
	`DROP SEQUENCE`: {
		ShortDescription: `remove a sequence`,
		//line sql.y: 5431
		Category: hDDL,
		//line sql.y: 5432
		Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5433
		SeeAlso: `DROP
`,
	},
	//line sql.y: 5445
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 5446
		Category: hDDL,
		//line sql.y: 5447
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5448
		SeeAlso: `WEBDOCS/drop-table.html
`,
	},
	//line sql.y: 5470
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 5471
		Category: hDDL,
		//line sql.y: 5472
		Text: `DROP INDEX [CONCURRENTLY] [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5473
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 5495
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 5496
		Category: hDDL,
		//line sql.y: 5497
		Text: `DROP DATABASE [IF EXISTS] <databasename> [ [ WITH ] ( option [, ...] ) ]
`,
		//line sql.y: 5498
		SeeAlso: `WEBDOCS/drop-database.html
`,
	},
	//line sql.y: 5532
	`DROP TYPE`: {
		ShortDescription: `remove a type`,
		//line sql.y: 5533
		Category: hDDL,
		//line sql.y: 5534
		Text: `DROP TYPE [IF EXISTS] <type_name> [, ...] [CASCADE | RESTRICT]
`,
	},
	//line sql.y: 5564
	`DROP SCHEMA`: {
		ShortDescription: `remove a schema`,
		//line sql.y: 5565
		Category: hDDL,
		//line sql.y: 5566
		Text: `DROP SCHEMA [IF EXISTS] <schema_name> [, ...] [CASCADE | RESTRICT]
`,
	},
	//line sql.y: 5596
	`DROP ROLE`: {
		ShortDescription: `remove a user`,
		//line sql.y: 5597
		Category: hPriv,
		//line sql.y: 5598
		Text: `DROP ROLE [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 5599
		SeeAlso: `CREATE ROLE, SHOW ROLE
`,
	},
	//line sql.y: 5623
	`ANALYZE`: {
		ShortDescription: `collect table statistics`,
		//line sql.y: 5624
		Category: hMisc,
		//line sql.y: 5625
		Text: `
ANALYZE [<tablename>]

`,
		//line sql.y: 5628
		SeeAlso: `CREATE STATISTICS
`,
	},
	//line sql.y: 5660
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 5661
		Category: hMisc,
		//line sql.y: 5662
		Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN [ANALYZE] (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
		//line sql.y: 5675
		SeeAlso: `WEBDOCS/explain.html
`,
	},
	//line sql.y: 5805
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 5806
		Category: hMisc,
		//line sql.y: 5807
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 5808
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 5839
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 5840
		Category: hMisc,
		//line sql.y: 5841
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 5842
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 5872
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 5873
		Category: hMisc,
		//line sql.y: 5874
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 5875
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 5895
	`GRANT`: {
		ShortDescription: `define access privileges and role memberships`,
		//line sql.y: 5896
		Category: hPriv,
		//line sql.y: 5897
		Text: `
Grant privileges:
  GRANT {ALL | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership:
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA <schemaname> [, <schemaname>]...

`,
		//line sql.y: 5912
		SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
	},
	//line sql.y: 6121
	`REVOKE`: {
		ShortDescription: `remove access privileges and role memberships`,
		//line sql.y: 6122
		Category: hPriv,
		//line sql.y: 6123
		Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership:
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA <schemaname> [, <schemaname]...

`,
		//line sql.y: 6138
		SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
	},
	//line sql.y: 6246
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 6247
		Category: hCfg,
		//line sql.y: 6248
		Text: `RESET [SESSION] <var>
`,
	},
	//line sql.y: 6279
	`USE`: {
		ShortDescription: `set the current database`,
		//line sql.y: 6280
		Category: hCfg,
		//line sql.y: 6281
		Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
		//line sql.y: 6284
		SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 6315
	`SCRUB`: {
		ShortDescription: `run checks against databases or tables`,
		//line sql.y: 6316
		Category: hExperimental,
		//line sql.y: 6317
		Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that ca be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 6325
		SeeAlso: `SCRUB TABLE, SCRUB DATABASE
`,
	},
	//line sql.y: 6331
	`SCRUB DATABASE`: {
		ShortDescription: `run scrub checks on a database`,
		//line sql.y: 6332
		Category: hExperimental,
		//line sql.y: 6333
		Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 6341
		SeeAlso: `SCRUB TABLE, SCRUB
`,
	},
	//line sql.y: 6349
	`SCRUB TABLE`: {
		ShortDescription: `run scrub checks on a table`,
		//line sql.y: 6350
		Category: hExperimental,
		//line sql.y: 6351
		Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
		//line sql.y: 6362
		SeeAlso: `SCRUB DATABASE, SRUB
`,
	},
	//line sql.y: 6429
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 6430
		Category: hTxn,
		//line sql.y: 6431
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }
   AS OF SYSTEM TIME <expr>
   [NOT] DEFERRABLE
`,
	},
	//line sql.y: 6453
	`SET CONSTRAINTS`: {
		ShortDescription: `configure the constraints settings`,
		//line sql.y: 6454
		Category: hCfg,
		//line sql.y: 6455
		Text: `
SET CONSTRAINTS { ALL | name [, ...] } { DEFERRED | IMMEDIATE }
`,
	},
	//line sql.y: 6475
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 6476
		Category: hCfg,
		//line sql.y: 6477
		Text: `
SET [ SESSION | LOCAL ] <var> { TO | = } <values...>
SET [ SESSION | LOCAL ] TIME ZONE <tz>
SET [ SESSION | LOCAL ] ROLE role_name
SET [ SESSION | LOCAL ] ROLE NONE

`,
		//line sql.y: 6483
		SeeAlso: `SET TRANSACTION
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 6697
	`SHOW`: {
		//line sql.y: 6698
		Category: hGroup,
		//line sql.y: 6699
		Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW RANGE, SHOW RANGES,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE, SHOW TRANSACTION,
SHOW TRANSACTIONS, SHOW TYPES, SHOW USERS, SHOW LAST QUERY STATISTICS, SHOW SCHEDULES
`,
	},
	//line sql.y: 6738
	`CLOSE`: {
		ShortDescription: `close a cursor`,
		//line sql.y: 6739
		Category: hMisc,
		//line sql.y: 6740
		Text: `CLOSE { <name> | ALL }
`,
		//line sql.y: 6741
		SeeAlso: `DECLARE, FETCH, MOVE
`,
	},
	//line sql.y: 6753
	`DECLARE`: {
		ShortDescription: `define a cursor`,
		//line sql.y: 6754
		Category: hMisc,
		//line sql.y: 6755
		Text: `
DECLARE <name> [ BINARY ] [ ASENSITIVE | INSENSITIVE ] [ [ NO ] SCROLL ]
    CURSOR [ { WITH | WITHOUT } HOLD ] FOR <selectclause>
`,
		//line sql.y: 6758
		SeeAlso: `CLOSE, FETCH, MOVE
`,
	},
	//line sql.y: 6806
	`FETCH`: {
		ShortDescription: `retrieve rows from a query using a cursor`,
		//line sql.y: 6807
		Category: hMisc,
		//line sql.y: 6808
		Text: `
FETCH [ <direction> ] [ FROM | IN ] <name>

Direction:
   NEXT | PRIOR | FIRST | LAST | ABSOLUTE <count> | RELATIVE <count> | <count> | ALL
   | FORWARD [ <count> | ALL ] | BACKWARD [ <count> | ALL ]
`,
		//line sql.y: 6814
		SeeAlso: `CLOSE, DECLARE, MOVE
`,
	},
	//line sql.y: 6822
	`MOVE`: {
		ShortDescription: `position a cursor`,
		//line sql.y: 6823
		Category: hMisc,
		//line sql.y: 6824
		Text: `
MOVE [ <direction> ] [ FROM | IN ] <name>

Direction:
   NEXT | PRIOR | FIRST | LAST | ABSOLUTE <count> | RELATIVE <count> | <count> | ALL
   | FORWARD [ <count> | ALL ] | BACKWARD [ <count> | ALL ]
`,
		//line sql.y: 6830
		SeeAlso: `CLOSE, DECLARE, FETCH
`,
	},
	//line sql.y: 7167
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 7168
		Category: hCfg,
		//line sql.y: 7169
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 7170
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 7198
	`SHOW STATISTICS`: {
		ShortDescription: `display table statistics (experimental)`,
		//line sql.y: 7199
		Category: hExperimental,
		//line sql.y: 7200
		Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name>

Returns the available statistics for a table.
The statistics can include a histogram ID, which can
be used with SHOW HISTOGRAM.
If USING JSON is specified, the statistics and histograms
are encoded in JSON format.
`,
		//line sql.y: 7207
		SeeAlso: `SHOW HISTOGRAM
`,
	},
	//line sql.y: 7220
	`SHOW HISTOGRAM`: {
		ShortDescription: `display histogram (experimental)`,
		//line sql.y: 7221
		Category: hExperimental,
		//line sql.y: 7222
		Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
		//line sql.y: 7226
		SeeAlso: `SHOW STATISTICS
`,
	},
	//line sql.y: 7239
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 7240
		Category: hCCL,
		//line sql.y: 7241
		Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
		//line sql.y: 7242
		SeeAlso: `WEBDOCS/show-backup.html
`,
	},
	//line sql.y: 7296
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 7297
		Category: hDDL,
		//line sql.y: 7298
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 7299
		SeeAlso: `WEBDOCS/show-columns.html
`,
	},
	//line sql.y: 7307
	`SHOW PARTITIONS`: {
		ShortDescription: `list partition information`,
		//line sql.y: 7308
		Category: hDDL,
		//line sql.y: 7309
		Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
		//line sql.y: 7310
		SeeAlso: `WEBDOCS/show-partitions.html
`,
	},
	//line sql.y: 7330
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 7331
		Category: hDDL,
		//line sql.y: 7332
		Text: `SHOW DATABASES
`,
		//line sql.y: 7333
		SeeAlso: `WEBDOCS/show-databases.html
`,
	},
	//line sql.y: 7341
	`SHOW ENUMS`: {
		ShortDescription: `list enums`,
		//line sql.y: 7342
		Category: hMisc,
		//line sql.y: 7343
		Text: `SHOW ENUMS
`,
	},
	//line sql.y: 7351
	`SHOW TYPES`: {
		ShortDescription: `list user defined types`,
		//line sql.y: 7352
		Category: hMisc,
		//line sql.y: 7353
		Text: `SHOW TYPES
`,
	},
	//line sql.y: 7361
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 7362
		Category: hPriv,
		//line sql.y: 7363
		Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
		//line sql.y: 7369
		SeeAlso: `WEBDOCS/show-grants.html
`,
	},
	//line sql.y: 7382
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 7383
		Category: hDDL,
		//line sql.y: 7384
		Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> } [WITH COMMENT]
`,
		//line sql.y: 7385
		SeeAlso: `WEBDOCS/show-index.html
`,
	},
	//line sql.y: 7415
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 7416
		Category: hDDL,
		//line sql.y: 7417
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 7418
		SeeAlso: `WEBDOCS/show-constraints.html
`,
	},
	//line sql.y: 7431
	`SHOW QUERIES`: {
		ShortDescription: `list running queries`,
		//line sql.y: 7432
		Category: hMisc,
		//line sql.y: 7433
		Text: `SHOW [ALL] [CLUSTER | LOCAL] QUERIES
`,
		//line sql.y: 7434
		SeeAlso: `CANCEL QUERIES
`,
	},
	//line sql.y: 7455
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 7456
		Category: hMisc,
		//line sql.y: 7457
		Text: `
SHOW [AUTOMATIC] JOBS [select clause]
SHOW JOBS FOR SCHEDULES [select clause]
SHOW JOB <jobid>
`,
		//line sql.y: 7461
		SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 7505
	`SHOW SCHEDULES`: {
		ShortDescription: `list periodic schedules`,
		//line sql.y: 7506
		Category: hMisc,
		//line sql.y: 7507
		Text: `
SHOW [RUNNING | PAUSED] SCHEDULES [FOR BACKUP]
SHOW SCHEDULE <schedule_id>
`,
		//line sql.y: 7510
		SeeAlso: `PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES
`,
	},
	//line sql.y: 7557
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 7558
		Category: hMisc,
		//line sql.y: 7559
		Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
		//line sql.y: 7561
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 7584
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 7585
		Category: hMisc,
		//line sql.y: 7586
		Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
		//line sql.y: 7587
		SeeAlso: `CANCEL SESSIONS
`,
	},
	//line sql.y: 7600
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 7601
		Category: hDDL,
		//line sql.y: 7602
		Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
		//line sql.y: 7603
		SeeAlso: `WEBDOCS/show-tables.html
`,
	},
	//line sql.y: 7631
	`SHOW TRANSACTIONS`: {
		ShortDescription: `list open client transactions across the cluster`,
		//line sql.y: 7632
		Category: hMisc,
		//line sql.y: 7633
		Text: `SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
`,
	},
	//line sql.y: 7650
	`SHOW SCHEMAS`: {
		ShortDescription: `list schemas`,
		//line sql.y: 7651
		Category: hDDL,
		//line sql.y: 7652
		Text: `SHOW SCHEMAS [FROM <databasename> ]
`,
	},
	//line sql.y: 7664
	`SHOW SEQUENCES`: {
		ShortDescription: `list sequences`,
		//line sql.y: 7665
		Category: hDDL,
		//line sql.y: 7666
		Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
	},
	//line sql.y: 7678
	`SHOW SYNTAX`: {
		ShortDescription: `analyze SQL syntax`,
		//line sql.y: 7679
		Category: hMisc,
		//line sql.y: 7680
		Text: `SHOW SYNTAX <string>
`,
	},
	//line sql.y: 7689
	`SHOW LAST QUERY STATISTICS`: {
		ShortDescription: `display statistics for the last query issued`,
		//line sql.y: 7690
		Category: hMisc,
		//line sql.y: 7691
		Text: `SHOW LAST QUERY STATISTICS
`,
	},
	//line sql.y: 7699
	`SHOW SAVEPOINT`: {
		ShortDescription: `display current savepoint properties`,
		//line sql.y: 7700
		Category: hCfg,
		//line sql.y: 7701
		Text: `SHOW SAVEPOINT STATUS
`,
	},
	//line sql.y: 7709
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 7710
		Category: hCfg,
		//line sql.y: 7711
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 7712
		SeeAlso: `WEBDOCS/show-transaction.html
`,
	},
	//line sql.y: 7731
	`SHOW CREATE`: {
		ShortDescription: `display the CREATE statement for a table, sequence or view`,
		//line sql.y: 7732
		Category: hDDL,
		//line sql.y: 7733
		Text: `SHOW CREATE [ TABLE | SEQUENCE | VIEW ] <tablename>
`,
		//line sql.y: 7734
		SeeAlso: `WEBDOCS/show-create-table.html
`,
	},
	//line sql.y: 7752
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 7753
		Category: hPriv,
		//line sql.y: 7754
		Text: `SHOW USERS
`,
		//line sql.y: 7755
		SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
	},
	//line sql.y: 7763
	`SHOW ROLES`: {
		ShortDescription: `list defined roles`,
		//line sql.y: 7764
		Category: hPriv,
		//line sql.y: 7765
		Text: `SHOW ROLES
`,
		//line sql.y: 7766
		SeeAlso: `CREATE ROLE, ALTER ROLE, DROP ROLE
`,
	},
	//line sql.y: 7988
	`PAUSE`: {
		//line sql.y: 7989
		Category: hMisc,
		//line sql.y: 7990
		Text: `

Pause various background tasks and activities.

PAUSE JOBS, PAUSE SCHEDULES
`,
	},
	//line sql.y: 8000
	`RESUME`: {
		//line sql.y: 8001
		Category: hMisc,
		//line sql.y: 8002
		Text: `

Resume various background tasks and activities.

RESUME JOBS, RESUME SCHEDULES
`,
	},
	//line sql.y: 8012
	`PAUSE JOBS`: {
		ShortDescription: `pause background jobs`,
		//line sql.y: 8013
		Category: hMisc,
		//line sql.y: 8014
		Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
		//line sql.y: 8017
		SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
	},
	//line sql.y: 8052
	`PAUSE SCHEDULES`: {
		ShortDescription: `pause scheduled jobs`,
		//line sql.y: 8053
		Category: hMisc,
		//line sql.y: 8054
		Text: `
PAUSE SCHEDULES <selectclause>
  select clause: select statement returning schedule id to pause.
PAUSE SCHEDULE <scheduleID>
`,
		//line sql.y: 8058
		SeeAlso: `RESUME SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 8079
	`CREATE SCHEMA`: {
		ShortDescription: `create a new schema`,
		//line sql.y: 8080
		Category: hDDL,
		//line sql.y: 8081
		Text: `
CREATE SCHEMA [IF NOT EXISTS] { <schemaname> | [<schemaname>] AUTHORIZATION <rolename> }
`,
	},
	//line sql.y: 8140
	`ALTER SCHEMA`: {
		ShortDescription: `alter an existing schema`,
		//line sql.y: 8141
		Category: hDDL,
		//line sql.y: 8142
		Text: `

Commands:
  ALTER SCHEMA ... RENAME TO <newschemaname>
  ALTER SCHEMA ... OWNER TO {<newowner> | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
`,
	},
	//line sql.y: 8168
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 8169
		Category: hDDL,
		//line sql.y: 8170
		Text: `
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<interleave>] [<on_commit>]
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source> [<interleave>] [<on commit>]

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [USING HASH WITH BUCKET_COUNT = <shard_buckets>] [{STORING | INCLUDE | COVERING} ( <colnames...> )] [<interleave>]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> ) [USING HASH WITH BUCKET_COUNT = <shard_buckets>]
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames... ) [{STORING | INCLUDE | COVERING} ( <colnames...> )] [<interleave>]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) STORED

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

On commit clause:
   ON COMMIT {PRESERVE ROWS | DROP | DELETE ROWS}

`,
		//line sql.y: 8200
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
	},
	//line sql.y: 9075
	`CREATE SEQUENCE`: {
		ShortDescription: `create a new sequence`,
		//line sql.y: 9076
		Category: hDDL,
		//line sql.y: 9077
		Text: `
CREATE [ { TEMPORARY | TEMP } | UNLOGGED ] SEQUENCE [ IF NOT EXISTS ] name
   [ AS data_type ]
   [ INCREMENT [ BY ] increment ]
   [ MINVALUE minvalue | NO MINVALUE ] [ MAXVALUE maxvalue | NO MAXVALUE ]
   [ START [ WITH ] start ] [ CACHE cache ] [ [ NO ] CYCLE ]
   [ OWNED BY { table_name.column_name | NONE } ]

`,
		//line sql.y: 9085
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 9270
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 9271
		Category: hDML,
		//line sql.y: 9272
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 9273
		SeeAlso: `WEBDOCS/truncate.html
`,
	},
	//line sql.y: 9541
	`CREATE ROLE`: {
		ShortDescription: `define a new role`,
		//line sql.y: 9542
		Category: hPriv,
		//line sql.y: 9543
		Text: `CREATE ROLE [IF NOT EXISTS] <name> [ [WITH] <OPTIONS...> ]
`,
		//line sql.y: 9544
		SeeAlso: `ALTER ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 9556
	`ALTER ROLE`: {
		ShortDescription: `alter a role`,
		//line sql.y: 9557
		Category: hPriv,
		//line sql.y: 9558
		Text: `ALTER ROLE <name> [WITH] <options...>
`,
		//line sql.y: 9559
		SeeAlso: `CREATE ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 9628
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 9629
		Category: hDDL,
		//line sql.y: 9630
		Text: `CREATE [ OR REPLACE ] [ TEMP | TEMPORARY ] [ RECURSIVE ] VIEW name [ ( column_name [, ...] ) ]
   	  [ WITH ( view_option_name [= view_option_value] [, ... ] ) ]
   	  AS <source>
   	  [ WITH [ CASCADED | LOCAL ] CHECK OPTION ]
`,
		//line sql.y: 9634
		SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
	},
	//line sql.y: 9865
	`CREATE TYPE`: {
		ShortDescription: `- create a type`,
		//line sql.y: 9866
		Category: hDDL,
		//line sql.y: 9867
		Text: `CREATE TYPE <type_name> AS ENUM (...)
`,
	},
	//line sql.y: 10053
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 10054
		Category: hDDL,
		//line sql.y: 10055
		Text: `
CREATE [UNIQUE] INDEX [CONCURRENTLY] [IF NOT EXISTS] [<idxname>]
       ON [ONLY] <tablename> [USING <method>]
       ( { column_name | ( expression ) } [ COLLATE collation ] [ opclass [ ( opclass_parameter = value [, ... ] ) ] ] [ ASC | DESC ] [ NULLS { FIRST | LAST } ] [, ...] )
       [INCLUDE ( column_name, [,...] )]
       [NULLS [ NOT ] DISTINCT]
       [WITH <storage_parameter_list>]
       [TABLESPACE tablespace_name]
       [WHERE <where_conds...>]
`,
	},
	//line sql.y: 10415
	`RELEASE`: {
		ShortDescription: `complete a sub-transaction`,
		//line sql.y: 10416
		Category: hTxn,
		//line sql.y: 10417
		Text: `RELEASE [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 10418
		SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 10426
	`RESUME JOBS`: {
		ShortDescription: `resume background jobs`,
		//line sql.y: 10427
		Category: hMisc,
		//line sql.y: 10428
		Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
		//line sql.y: 10431
		SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
	},
	//line sql.y: 10453
	`RESUME SCHEDULES`: {
		ShortDescription: `resume executing scheduled jobs`,
		//line sql.y: 10454
		Category: hMisc,
		//line sql.y: 10455
		Text: `
RESUME SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

RESUME SCHEDULES <jobid>

`,
		//line sql.y: 10461
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, RESUME JOBS
`,
	},
	//line sql.y: 10482
	`DROP SCHEDULES`: {
		ShortDescription: `destroy specified schedules`,
		//line sql.y: 10483
		Category: hMisc,
		//line sql.y: 10484
		Text: `
DROP SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

DROP SCHEDULES <jobid>

`,
		//line sql.y: 10490
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 10511
	`SAVEPOINT`: {
		ShortDescription: `start a sub-transaction`,
		//line sql.y: 10512
		Category: hTxn,
		//line sql.y: 10513
		Text: `SAVEPOINT <savepoint name>
`,
		//line sql.y: 10514
		SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 10529
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 10530
		Category: hTxn,
		//line sql.y: 10531
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 10539
		SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
	},
	//line sql.y: 10552
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 10553
		Category: hTxn,
		//line sql.y: 10554
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 10557
		SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
	},
	//line sql.y: 10584
	`ROLLBACK`: {
		ShortDescription: `abort the current (sub-)transaction`,
		//line sql.y: 10585
		Category: hTxn,
		//line sql.y: 10586
		Text: `
ROLLBACK [TRANSACTION]
ROLLBACK [TRANSACTION] TO [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 10589
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
	},
	//line sql.y: 10705
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 10706
		Category: hDDL,
		//line sql.y: 10707
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 10708
		SeeAlso: `WEBDOCS/create-database.html
`,
	},
	//line sql.y: 10922
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 10923
		Category: hDML,
		//line sql.y: 10924
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT {
         [( <colnames...> )] [WHERE <arbiter_predicate>] DO NOTHING |
         ( <colnames...> ) [WHERE <index_predicate>] DO UPDATE SET ... [WHERE <expr>]
       }
       [RETURNING <exprs...>]
`,
		//line sql.y: 10932
		SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
	},
	//line sql.y: 10951
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 10952
		Category: hDML,
		//line sql.y: 10953
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 10957
		SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
	},
	//line sql.y: 11073
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 11074
		Category: hDML,
		//line sql.y: 11075
		Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
		//line sql.y: 11082
		SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
	},
	//line sql.y: 11311
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 11312
		Category: hDML,
		//line sql.y: 11313
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 11348
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 11349
		Category: hDML,
		//line sql.y: 11350
		Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 11362
		SeeAlso: `WEBDOCS/select-clause.html
`,
	},
	//line sql.y: 11448
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 11449
		Category: hDML,
		//line sql.y: 11450
		Text: `TABLE <tablename>
`,
		//line sql.y: 11451
		SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 11797
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 11798
		Category: hDML,
		//line sql.y: 11799
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 11800
		SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 11909
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 11910
		Category: hDML,
		//line sql.y: 11911
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP } ]

`,
		//line sql.y: 11933
		SeeAlso: `WEBDOCS/table-expressions.html
`,
	},
}
