// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 1556
	`ALTER`: {
		//line sql.y: 1557
		Category: hGroup,
		//line sql.y: 1558
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE
`,
	},
	//line sql.y: 1583
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 1584
		Category: hDDL,
		//line sql.y: 1585
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SET SCHEMA <newschemaname>

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

`,
		//line sql.y: 1607
		SeeAlso: `WEBDOCS/alter-table.html
`,
	},
	//line sql.y: 1618
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 1619
		Category: hDDL,
		//line sql.y: 1620
		Text: `
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> RENAME TO <newname>
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
		//line sql.y: 1623
		SeeAlso: `WEBDOCS/alter-view.html
`,
	},
	//line sql.y: 1667
	`ALTER SEQUENCE`: {
		ShortDescription: `change the definition of a sequence`,
		//line sql.y: 1668
		Category: hDDL,
		//line sql.y: 1669
		Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START <start>]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
ALTER SEQUENCE [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
	},
	//line sql.y: 1711
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 1712
		Category: hDDL,
		//line sql.y: 1713
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
ALTER DATABASE <name> OWNER TO <newowner>
`,
		//line sql.y: 1716
		SeeAlso: `WEBDOCS/alter-database.html
`,
	},
	//line sql.y: 1887
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 1888
		Category: hDDL,
		//line sql.y: 1889
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>

`,
		//line sql.y: 1895
		SeeAlso: `WEBDOCS/alter-index.html
`,
	},
	//line sql.y: 2615
	`ALTER TYPE`: {
		ShortDescription: `change the definition of a type.`,
		//line sql.y: 2616
		Category: hDDL,
		//line sql.y: 2617
		Text: `ALTER TYPE <typename> <command>

Commands:
  ALTER TYPE ... ADD VALUE [IF NOT EXISTS] <value> [ { BEFORE | AFTER } <value> ]
  ALTER TYPE ... RENAME VALUE <oldname> TO <newname>
  ALTER TYPE ... RENAME TO <newname>
  ALTER TYPE ... SET SCHEMA <newschemaname>
  ALTER TYPE ... OWNER TO {<newowner> | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
  ALTER TYPE ... RENAME ATTRIBUTE <oldname> TO <newname> [ CASCADE | RESTRICT ]
  ALTER TYPE ... <attributeaction> [, ... ]

Attribute action:
  ADD ATTRIBUTE <name> <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]
  DROP ATTRIBUTE [IF EXISTS] <name> [ CASCADE | RESTRICT ]
  ALTER ATTRIBUTE <name> [ SET DATA ] TYPE <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]

`,
		//line sql.y: 2633
		SeeAlso: `WEBDOCS/alter-type.html
`,
	},
	//line sql.y: 3003
	`REFRESH`: {
		ShortDescription: `recalculate a materialized view`,
		//line sql.y: 3004
		Category: hMisc,
		//line sql.y: 3005
		Text: `
REFRESH MATERIALIZED VIEW [CONCURRENTLY] view_name [WITH [NO] DATA]
`,
	},
	//line sql.y: 3032
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 3033
		Category: hCCL,
		//line sql.y: 3034
		Text: `
BACKUP <targets...> TO <location...>
       [ AS OF SYSTEM TIME <expr> ]
       [ INCREMENTAL FROM <location...> ]
       [ WITH <option> [= <value>] [, ...] ]

Targets:
   Empty targets list: backup full cluster.
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Location:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   revision_history: enable revision history
   encryption_passphrase="secret": encrypt backups
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : encrypt backups using KMS
   detached: execute backup job asynchronously, without waiting for its completion

`,
		//line sql.y: 3054
		SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
	},
	//line sql.y: 3158
	`CREATE SCHEDULE FOR BACKUP`: {
		ShortDescription: `backup data periodically`,
		//line sql.y: 3159
		Category: hCCL,
		//line sql.y: 3160
		Text: `
CREATE SCHEDULE [<description>]
FOR BACKUP [<targets>] TO <location...>
[WITH <backup_option>[=<value>] [, ...]]
RECURRING [crontab|NEVER] [FULL BACKUP <crontab|ALWAYS>]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]

All backups run in UTC timezone.

Description:
  Optional description (or name) for this schedule

Targets:
  empty targets: Backup entire cluster
  DATABASE <pattern> [, ...]: comma separated list of databases to backup.
  TABLE <pattern> [, ...]: comma separated list of tables to backup.

Location:
  "[scheme]://[host]/[path prefix to backup]?[parameters]"
  Backup schedule will create subdirectories under this location to store
  full and periodic backups.

WITH <options>:
  Options specific to BACKUP: See BACKUP options

RECURRING <crontab>:
  The RECURRING expression specifies when we backup.  By default these are incremental
  backups that capture changes since the last backup, writing to the "current" backup.

  Schedule specified as a string in crontab format.
  All times in UTC.
    "5 0 * * *": run schedule 5 minutes past midnight.
    "@daily": run daily, at midnight
  See https://en.wikipedia.org/wiki/Cron

FULL BACKUP <crontab|ALWAYS>:
  The optional FULL BACKUP '<cron expr>' clause specifies when we'll start a new full backup,
  which becomes the "current" backup when complete.
  If FULL BACKUP ALWAYS is specified, then the backups triggered by the RECURRING clause will
  always be full backups. For free users, this is the only accepted value of FULL BACKUP.

  If the FULL BACKUP clause is omitted, we will select a reasonable default:
     * RECURRING <= 1 hour: we default to FULL BACKUP '@daily';
     * RECURRING <= 1 day:  we default to FULL BACKUP '@weekly';
     * Otherwise: we default to FULL BACKUP ALWAYS.

 SCHEDULE OPTIONS:
  The schedule can be modified by specifying the following options (which are considered
  to be experimental at this time):
  * first_run=TIMESTAMPTZ:
    execute the schedule at the specified time. If not specified, the default is to execute
    the scheduled based on it's next RECURRING time.
  * on_execution_failure='[retry|reschedule|pause]':
    If an error occurs during the execution, handle the error based as:
    * retry: retry execution right away
    * reschedule: retry execution by rescheduling it based on its RECURRING expression.
      This is the default.
    * pause: pause this schedule.  Requires manual intervention to unpause.
  * on_previous_running='[start|skip|wait]':
    If the previous backup started by this schedule still running, handle this as:
    * start: start this execution anyway, even if the previous one still running.
    * skip: skip this execution, reschedule it based on RECURRING (or change_capture_period)
      expression.
    * wait: wait for the previous execution to complete.  This is the default.
  * ignore_existing_backups
    If backups were already created in the destination in which a new schedule references,
    this flag must be passed in to acknowledge that the new schedule may be backing up different
    objects.

`,
		//line sql.y: 3229
		SeeAlso: `BACKUP
`,
	},
	//line sql.y: 3307
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 3308
		Category: hCCL,
		//line sql.y: 3309
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   into_db: specify target database
   skip_missing_foreign_keys: remove foreign key constraints before restoring
   skip_missing_sequences: ignore sequence dependencies
   skip_missing_views: skip restoring views because of dependencies that cannot be restored
   skip_missing_sequence_owners: remove sequence-table ownership dependencies before restoring
   encryption_passphrase=passphrase: decrypt BACKUP with specified passphrase
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : decrypt backups using KMS
   detached: execute restore job asynchronously, without waiting for its completion
`,
		//line sql.y: 3330
		SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
	},
	//line sql.y: 3451
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 3452
		Category: hCCL,
		//line sql.y: 3453
		Text: `
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

-- Import using specific schema, use only table data from external file:
IMPORT TABLE <tablename>
       { ( <elements> ) | CREATE USING <schemafile> }
       <format>
       DATA ( <datafile> [, ...] )
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   CSV
   DELIMITED
   MYSQLDUMP
   PGCOPY
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'
   delimiter = '...'      [CSV, PGCOPY-specific]
   nullif = '...'         [CSV, PGCOPY-specific]
   comment = '...'        [CSV-specific]

`,
		//line sql.y: 3481
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 3525
	`EXPORT`: {
		ShortDescription: `export data to file in a distributed manner`,
		//line sql.y: 3526
		Category: hCCL,
		//line sql.y: 3527
		Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV

Options:
   delimiter = '...'   [CSV-specific]

`,
		//line sql.y: 3536
		SeeAlso: `SELECT
`,
	},
	//line sql.y: 3618
	`CALL`: {
		ShortDescription: `invoke a procedure`,
		//line sql.y: 3619
		Category: hMisc,
		//line sql.y: 3620
		Text: `CALL <name> ( [ <expr> [, ...] ] )
`,
		//line sql.y: 3621
		SeeAlso: `CREATE PROCEDURE
`,
	},
	//line sql.y: 3855
	`CANCEL`: {
		//line sql.y: 3856
		Category: hGroup,
		//line sql.y: 3857
		Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
	},
	//line sql.y: 3864
	`CANCEL JOBS`: {
		ShortDescription: `cancel background jobs`,
		//line sql.y: 3865
		Category: hMisc,
		//line sql.y: 3866
		Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
		//line sql.y: 3869
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 3891
	`CANCEL QUERIES`: {
		ShortDescription: `cancel running queries`,
		//line sql.y: 3892
		Category: hMisc,
		//line sql.y: 3893
		Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
		//line sql.y: 3896
		SeeAlso: `SHOW QUERIES
`,
	},
	//line sql.y: 3927
	`CANCEL SESSIONS`: {
		ShortDescription: `cancel open sessions`,
		//line sql.y: 3928
		Category: hMisc,
		//line sql.y: 3929
		Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
		//line sql.y: 3932
		SeeAlso: `SHOW SESSIONS
`,
	},
	//line sql.y: 4180
	`CREATE`: {
		//line sql.y: 4181
		Category: hGroup,
		//line sql.y: 4182
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE, CREATE TYPE, CREATE CAST
`,
	},
	//line sql.y: 4329
	`CREATE OPERATOR`: {
		ShortDescription: `define a new operator`,
		//line sql.y: 4330
		Category: hDDL,
		//line sql.y: 4331
		Text: `CREATE OPERATOR name (
         {FUNCTION|PROCEDURE} = function_name
         [, LEFTARG = left_type ] [, RIGHTARG = right_type ]
         [, COMMUTATOR = com_op ] [, NEGATOR = neg_op ]
         [, RESTRICT = res_proc ] [, JOIN = join_proc ]
         [, HASHES ] [, MERGES ]
       )
`,
		//line sql.y: 4338
		SeeAlso: `WEBDOCS/sql-createoperator.html
`,
	},
	//line sql.y: 4372
	`CREATE CAST`: {
		ShortDescription: `define a new cast`,
		//line sql.y: 4373
		Category: hDDL,
		//line sql.y: 4374
		Text: `CREATE CAST (source_type AS target_type) WITH FUNCTION function_name [ (argument_type [, ...]) ] [ AS ASSIGNMENT | AS IMPLICIT ]
       CREATE CAST (source_type AS target_type) WITHOUT FUNCTION [ AS ASSIGNMENT | AS IMPLICIT ]
       CREATE CAST (source_type AS target_type) WITH INOUT [ AS ASSIGNMENT | AS IMPLICIT ]
`,
		//line sql.y: 4377
		SeeAlso: `WEBDOCS/sql-createcast.html
`,
	},
	//line sql.y: 4952
	`DROP OPERATOR`: {
		ShortDescription: `remove an operator`,
		//line sql.y: 4953
		Category: hDDL,
		//line sql.y: 4954
		Text: `DROP OPERATOR [ IF EXISTS ] name ( { left_type | NONE } , right_type ) [, ...] [ CASCADE | RESTRICT ]
`,
		//line sql.y: 4955
		SeeAlso: `WEBDOCS/sql-dropoperator.html
`,
	},
	//line sql.y: 5062
	`CREATE STATISTICS`: {
		ShortDescription: `create a new table statistic`,
		//line sql.y: 5063
		Category: hMisc,
		//line sql.y: 5064
		Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
	},
	//line sql.y: 5207
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 5208
		Category: hDML,
		//line sql.y: 5209
		Text: `DELETE FROM <tablename> [WHERE <expr>]
              [ORDER BY <exprs...>]
              [LIMIT <expr>]
              [RETURNING <exprs...>]
`,
		//line sql.y: 5213
		SeeAlso: `WEBDOCS/delete.html
`,
	},
	//line sql.y: 5232
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 5233
		Category: hCfg,
		//line sql.y: 5234
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 5246
	`DROP`: {
		//line sql.y: 5247
		Category: hGroup,
		//line sql.y: 5248
		Text: `
DROP CAST, DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE, DROP TYPE
`,
	},
	//line sql.y: 5276
	`DROP CAST`: {
		ShortDescription: `remove a cast`,
		//line sql.y: 5277
		Category: hDDL,
		//line sql.y: 5278
		Text: `DROP CAST [ IF EXISTS ] (source_type AS target_type) [ CASCADE | RESTRICT ]
`,
		//line sql.y: 5279
		SeeAlso: `WEBDOCS/sql-dropcast.html
`,
	},
	//line sql.y: 5293
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 5294
		Category: hDDL,
		//line sql.y: 5295
		Text: `DROP [MATERIALIZED] VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5296
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 5326
	`DROP SEQUENCE`: {
		ShortDescription: `remove a sequence`,
		//line sql.y: 5327
		Category: hDDL,
		//line sql.y: 5328
		Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5329
		SeeAlso: `DROP
`,
	},
	//line sql.y: 5341
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 5342
		Category: hDDL,
		//line sql.y: 5343
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5344
		SeeAlso: `WEBDOCS/drop-table.html
`,
	},
	//line sql.y: 5366
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 5367
		Category: hDDL,
		//line sql.y: 5368
		Text: `DROP INDEX [CONCURRENTLY] [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5369
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 5391
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 5392
		Category: hDDL,
		//line sql.y: 5393
		Text: `DROP DATABASE [IF EXISTS] <databasename> [ [ WITH ] ( option [, ...] ) ]
`,
		//line sql.y: 5394
		SeeAlso: `WEBDOCS/drop-database.html
`,
	},
	//line sql.y: 5428
	`DROP TYPE`: {
		ShortDescription: `remove a type`,
		//line sql.y: 5429
		Category: hDDL,
		//line sql.y: 5430
		Text: `DROP TYPE [IF EXISTS] <type_name> [, ...] [CASCADE | RESTRICT]
`,
	},
	//line sql.y: 5460
	`DROP SCHEMA`: {
		ShortDescription: `remove a schema`,
		//line sql.y: 5461
		Category: hDDL,
		//line sql.y: 5462
		Text: `DROP SCHEMA [IF EXISTS] <schema_name> [, ...] [CASCADE | RESTRICT]
`,
	},
	//line sql.y: 5492
	`DROP ROLE`: {
		ShortDescription: `remove a user`,
		//line sql.y: 5493
		Category: hPriv,
		//line sql.y: 5494
		Text: `DROP ROLE [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 5495
		SeeAlso: `CREATE ROLE, SHOW ROLE
`,
	},
	//line sql.y: 5519
	`ANALYZE`: {
		ShortDescription: `collect table statistics`,
		//line sql.y: 5520
		Category: hMisc,
		//line sql.y: 5521
		Text: `
ANALYZE [<tablename>]

`,
		//line sql.y: 5524
		SeeAlso: `CREATE STATISTICS
`,
	},
	//line sql.y: 5556
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 5557
		Category: hMisc,
		//line sql.y: 5558
		Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN [ANALYZE] (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
		//line sql.y: 5571
		SeeAlso: `WEBDOCS/explain.html
`,
	},
	//line sql.y: 5701
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 5702
		Category: hMisc,
		//line sql.y: 5703
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 5704
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 5735
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 5736
		Category: hMisc,
		//line sql.y: 5737
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 5738
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 5768
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 5769
		Category: hMisc,
		//line sql.y: 5770
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 5771
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 5791
	`GRANT`: {
		ShortDescription: `define access privileges and role memberships`,
		//line sql.y: 5792
		Category: hPriv,
		//line sql.y: 5793
		Text: `
Grant privileges:
  GRANT {ALL | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership:
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA <schemaname> [, <schemaname>]...

`,
		//line sql.y: 5808
		SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
	},
	//line sql.y: 6017
	`REVOKE`: {
		ShortDescription: `remove access privileges and role memberships`,
		//line sql.y: 6018
		Category: hPriv,
		//line sql.y: 6019
		Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership:
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA <schemaname> [, <schemaname]...

`,
		//line sql.y: 6034
		SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
	},
	//line sql.y: 6142
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 6143
		Category: hCfg,
		//line sql.y: 6144
		Text: `RESET [SESSION] <var>
`,
	},
	//line sql.y: 6171
	`USE`: {
		ShortDescription: `set the current database`,
		//line sql.y: 6172
		Category: hCfg,
		//line sql.y: 6173
		Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
		//line sql.y: 6176
		SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 6207
	`SCRUB`: {
		ShortDescription: `run checks against databases or tables`,
		//line sql.y: 6208
		Category: hExperimental,
		//line sql.y: 6209
		Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that ca be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 6217
		SeeAlso: `SCRUB TABLE, SCRUB DATABASE
`,
	},
	//line sql.y: 6223
	`SCRUB DATABASE`: {
		ShortDescription: `run scrub checks on a database`,
		//line sql.y: 6224
		Category: hExperimental,
		//line sql.y: 6225
		Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 6233
		SeeAlso: `SCRUB TABLE, SCRUB
`,
	},
	//line sql.y: 6241
	`SCRUB TABLE`: {
		ShortDescription: `run scrub checks on a table`,
		//line sql.y: 6242
		Category: hExperimental,
		//line sql.y: 6243
		Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
		//line sql.y: 6254
		SeeAlso: `SCRUB DATABASE, SRUB
`,
	},
	//line sql.y: 6321
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 6322
		Category: hTxn,
		//line sql.y: 6323
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }
   AS OF SYSTEM TIME <expr>
   [NOT] DEFERRABLE
`,
	},
	//line sql.y: 6345
	`SET CONSTRAINTS`: {
		ShortDescription: `configure the constraints settings`,
		//line sql.y: 6346
		Category: hCfg,
		//line sql.y: 6347
		Text: `
SET CONSTRAINTS { ALL | name [, ...] } { DEFERRED | IMMEDIATE }
`,
	},
	//line sql.y: 6367
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 6368
		Category: hCfg,
		//line sql.y: 6369
		Text: `
SET [ SESSION | LOCAL ] <var> { TO | = } <values...>
SET [ SESSION | LOCAL ] TIME ZONE <tz>
SET [ SESSION | LOCAL ] ROLE role_name
SET [ SESSION | LOCAL ] ROLE NONE

`,
		//line sql.y: 6375
		SeeAlso: `SET TRANSACTION
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 6571
	`SHOW`: {
		//line sql.y: 6572
		Category: hGroup,
		//line sql.y: 6573
		Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW RANGE, SHOW RANGES,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE, SHOW TRANSACTION,
SHOW TRANSACTIONS, SHOW TYPES, SHOW USERS, SHOW LAST QUERY STATISTICS, SHOW SCHEDULES
`,
	},
	//line sql.y: 6874
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 6875
		Category: hCfg,
		//line sql.y: 6876
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 6877
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 6901
	`SHOW STATISTICS`: {
		ShortDescription: `display table statistics (experimental)`,
		//line sql.y: 6902
		Category: hExperimental,
		//line sql.y: 6903
		Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name>

Returns the available statistics for a table.
The statistics can include a histogram ID, which can
be used with SHOW HISTOGRAM.
If USING JSON is specified, the statistics and histograms
are encoded in JSON format.
`,
		//line sql.y: 6910
		SeeAlso: `SHOW HISTOGRAM
`,
	},
	//line sql.y: 6923
	`SHOW HISTOGRAM`: {
		ShortDescription: `display histogram (experimental)`,
		//line sql.y: 6924
		Category: hExperimental,
		//line sql.y: 6925
		Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
		//line sql.y: 6929
		SeeAlso: `SHOW STATISTICS
`,
	},
	//line sql.y: 6942
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 6943
		Category: hCCL,
		//line sql.y: 6944
		Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
		//line sql.y: 6945
		SeeAlso: `WEBDOCS/show-backup.html
`,
	},
	//line sql.y: 6999
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 7000
		Category: hDDL,
		//line sql.y: 7001
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 7002
		SeeAlso: `WEBDOCS/show-columns.html
`,
	},
	//line sql.y: 7010
	`SHOW PARTITIONS`: {
		ShortDescription: `list partition information`,
		//line sql.y: 7011
		Category: hDDL,
		//line sql.y: 7012
		Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
		//line sql.y: 7013
		SeeAlso: `WEBDOCS/show-partitions.html
`,
	},
	//line sql.y: 7033
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 7034
		Category: hDDL,
		//line sql.y: 7035
		Text: `SHOW DATABASES
`,
		//line sql.y: 7036
		SeeAlso: `WEBDOCS/show-databases.html
`,
	},
	//line sql.y: 7044
	`SHOW ENUMS`: {
		ShortDescription: `list enums`,
		//line sql.y: 7045
		Category: hMisc,
		//line sql.y: 7046
		Text: `SHOW ENUMS
`,
	},
	//line sql.y: 7054
	`SHOW TYPES`: {
		ShortDescription: `list user defined types`,
		//line sql.y: 7055
		Category: hMisc,
		//line sql.y: 7056
		Text: `SHOW TYPES
`,
	},
	//line sql.y: 7064
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 7065
		Category: hPriv,
		//line sql.y: 7066
		Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
		//line sql.y: 7072
		SeeAlso: `WEBDOCS/show-grants.html
`,
	},
	//line sql.y: 7085
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 7086
		Category: hDDL,
		//line sql.y: 7087
		Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> } [WITH COMMENT]
`,
		//line sql.y: 7088
		SeeAlso: `WEBDOCS/show-index.html
`,
	},
	//line sql.y: 7118
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 7119
		Category: hDDL,
		//line sql.y: 7120
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 7121
		SeeAlso: `WEBDOCS/show-constraints.html
`,
	},
	//line sql.y: 7134
	`SHOW QUERIES`: {
		ShortDescription: `list running queries`,
		//line sql.y: 7135
		Category: hMisc,
		//line sql.y: 7136
		Text: `SHOW [ALL] [CLUSTER | LOCAL] QUERIES
`,
		//line sql.y: 7137
		SeeAlso: `CANCEL QUERIES
`,
	},
	//line sql.y: 7158
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 7159
		Category: hMisc,
		//line sql.y: 7160
		Text: `
SHOW [AUTOMATIC] JOBS [select clause]
SHOW JOBS FOR SCHEDULES [select clause]
SHOW JOB <jobid>
`,
		//line sql.y: 7164
		SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 7208
	`SHOW SCHEDULES`: {
		ShortDescription: `list periodic schedules`,
		//line sql.y: 7209
		Category: hMisc,
		//line sql.y: 7210
		Text: `
SHOW [RUNNING | PAUSED] SCHEDULES [FOR BACKUP]
SHOW SCHEDULE <schedule_id>
`,
		//line sql.y: 7213
		SeeAlso: `PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES
`,
	},
	//line sql.y: 7260
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 7261
		Category: hMisc,
		//line sql.y: 7262
		Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
		//line sql.y: 7264
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 7287
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 7288
		Category: hMisc,
		//line sql.y: 7289
		Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
		//line sql.y: 7290
		SeeAlso: `CANCEL SESSIONS
`,
	},
	//line sql.y: 7303
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 7304
		Category: hDDL,
		//line sql.y: 7305
		Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
		//line sql.y: 7306
		SeeAlso: `WEBDOCS/show-tables.html
`,
	},
	//line sql.y: 7334
	`SHOW TRANSACTIONS`: {
		ShortDescription: `list open client transactions across the cluster`,
		//line sql.y: 7335
		Category: hMisc,
		//line sql.y: 7336
		Text: `SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
`,
	},
	//line sql.y: 7353
	`SHOW SCHEMAS`: {
		ShortDescription: `list schemas`,
		//line sql.y: 7354
		Category: hDDL,
		//line sql.y: 7355
		Text: `SHOW SCHEMAS [FROM <databasename> ]
`,
	},
	//line sql.y: 7367
	`SHOW SEQUENCES`: {
		ShortDescription: `list sequences`,
		//line sql.y: 7368
		Category: hDDL,
		//line sql.y: 7369
		Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
	},
	//line sql.y: 7381
	`SHOW SYNTAX`: {
		ShortDescription: `analyze SQL syntax`,
		//line sql.y: 7382
		Category: hMisc,
		//line sql.y: 7383
		Text: `SHOW SYNTAX <string>
`,
	},
	//line sql.y: 7392
	`SHOW LAST QUERY STATISTICS`: {
		ShortDescription: `display statistics for the last query issued`,
		//line sql.y: 7393
		Category: hMisc,
		//line sql.y: 7394
		Text: `SHOW LAST QUERY STATISTICS
`,
	},
	//line sql.y: 7402
	`SHOW SAVEPOINT`: {
		ShortDescription: `display current savepoint properties`,
		//line sql.y: 7403
		Category: hCfg,
		//line sql.y: 7404
		Text: `SHOW SAVEPOINT STATUS
`,
	},
	//line sql.y: 7412
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 7413
		Category: hCfg,
		//line sql.y: 7414
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 7415
		SeeAlso: `WEBDOCS/show-transaction.html
`,
	},
	//line sql.y: 7434
	`SHOW CREATE`: {
		ShortDescription: `display the CREATE statement for a table, sequence or view`,
		//line sql.y: 7435
		Category: hDDL,
		//line sql.y: 7436
		Text: `SHOW CREATE [ TABLE | SEQUENCE | VIEW ] <tablename>
`,
		//line sql.y: 7437
		SeeAlso: `WEBDOCS/show-create-table.html
`,
	},
	//line sql.y: 7455
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 7456
		Category: hPriv,
		//line sql.y: 7457
		Text: `SHOW USERS
`,
		//line sql.y: 7458
		SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
	},
	//line sql.y: 7466
	`SHOW ROLES`: {
		ShortDescription: `list defined roles`,
		//line sql.y: 7467
		Category: hPriv,
		//line sql.y: 7468
		Text: `SHOW ROLES
`,
		//line sql.y: 7469
		SeeAlso: `CREATE ROLE, ALTER ROLE, DROP ROLE
`,
	},
	//line sql.y: 7691
	`PAUSE`: {
		//line sql.y: 7692
		Category: hMisc,
		//line sql.y: 7693
		Text: `

Pause various background tasks and activities.

PAUSE JOBS, PAUSE SCHEDULES
`,
	},
	//line sql.y: 7703
	`RESUME`: {
		//line sql.y: 7704
		Category: hMisc,
		//line sql.y: 7705
		Text: `

Resume various background tasks and activities.

RESUME JOBS, RESUME SCHEDULES
`,
	},
	//line sql.y: 7715
	`PAUSE JOBS`: {
		ShortDescription: `pause background jobs`,
		//line sql.y: 7716
		Category: hMisc,
		//line sql.y: 7717
		Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
		//line sql.y: 7720
		SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
	},
	//line sql.y: 7755
	`PAUSE SCHEDULES`: {
		ShortDescription: `pause scheduled jobs`,
		//line sql.y: 7756
		Category: hMisc,
		//line sql.y: 7757
		Text: `
PAUSE SCHEDULES <selectclause>
  select clause: select statement returning schedule id to pause.
PAUSE SCHEDULE <scheduleID>
`,
		//line sql.y: 7761
		SeeAlso: `RESUME SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 7782
	`CREATE SCHEMA`: {
		ShortDescription: `create a new schema`,
		//line sql.y: 7783
		Category: hDDL,
		//line sql.y: 7784
		Text: `
CREATE SCHEMA [IF NOT EXISTS] { <schemaname> | [<schemaname>] AUTHORIZATION <rolename> }
`,
	},
	//line sql.y: 7843
	`ALTER SCHEMA`: {
		ShortDescription: `alter an existing schema`,
		//line sql.y: 7844
		Category: hDDL,
		//line sql.y: 7845
		Text: `

Commands:
  ALTER SCHEMA ... RENAME TO <newschemaname>
  ALTER SCHEMA ... OWNER TO {<newowner> | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
`,
	},
	//line sql.y: 7871
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 7872
		Category: hDDL,
		//line sql.y: 7873
		Text: `
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<interleave>] [<on_commit>]
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source> [<interleave>] [<on commit>]

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [USING HASH WITH BUCKET_COUNT = <shard_buckets>] [{STORING | INCLUDE | COVERING} ( <colnames...> )] [<interleave>]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> ) [USING HASH WITH BUCKET_COUNT = <shard_buckets>]
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames... ) [{STORING | INCLUDE | COVERING} ( <colnames...> )] [<interleave>]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) STORED

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

On commit clause:
   ON COMMIT {PRESERVE ROWS | DROP | DELETE ROWS}

`,
		//line sql.y: 7903
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
	},
	//line sql.y: 8770
	`CREATE SEQUENCE`: {
		ShortDescription: `create a new sequence`,
		//line sql.y: 8771
		Category: hDDL,
		//line sql.y: 8772
		Text: `
CREATE [ { TEMPORARY | TEMP } | UNLOGGED ] SEQUENCE [ IF NOT EXISTS ] name
   [ AS data_type ]
   [ INCREMENT [ BY ] increment ]
   [ MINVALUE minvalue | NO MINVALUE ] [ MAXVALUE maxvalue | NO MAXVALUE ]
   [ START [ WITH ] start ] [ CACHE cache ] [ [ NO ] CYCLE ]
   [ OWNED BY { table_name.column_name | NONE } ]

`,
		//line sql.y: 8780
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 8965
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 8966
		Category: hDML,
		//line sql.y: 8967
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 8968
		SeeAlso: `WEBDOCS/truncate.html
`,
	},
	//line sql.y: 9236
	`CREATE ROLE`: {
		ShortDescription: `define a new role`,
		//line sql.y: 9237
		Category: hPriv,
		//line sql.y: 9238
		Text: `CREATE ROLE [IF NOT EXISTS] <name> [ [WITH] <OPTIONS...> ]
`,
		//line sql.y: 9239
		SeeAlso: `ALTER ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 9251
	`ALTER ROLE`: {
		ShortDescription: `alter a role`,
		//line sql.y: 9252
		Category: hPriv,
		//line sql.y: 9253
		Text: `ALTER ROLE <name> [WITH] <options...>
`,
		//line sql.y: 9254
		SeeAlso: `CREATE ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 9289
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 9290
		Category: hDDL,
		//line sql.y: 9291
		Text: `CREATE [ OR REPLACE ] [ TEMP | TEMPORARY ] [ RECURSIVE ] VIEW name [ ( column_name [, ...] ) ]
   	  [ WITH ( view_option_name [= view_option_value] [, ... ] ) ]
   	  AS <source>
   	  [ WITH [ CASCADED | LOCAL ] CHECK OPTION ]
`,
		//line sql.y: 9295
		SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
	},
	//line sql.y: 9526
	`CREATE TYPE`: {
		ShortDescription: `- create a type`,
		//line sql.y: 9527
		Category: hDDL,
		//line sql.y: 9528
		Text: `CREATE TYPE <type_name> AS ENUM (...)
`,
	},
	//line sql.y: 9714
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 9715
		Category: hDDL,
		//line sql.y: 9716
		Text: `
CREATE [UNIQUE] INDEX [CONCURRENTLY] [IF NOT EXISTS] [<idxname>]
       ON [ONLY] <tablename> [USING <method>]
       ( { column_name | ( expression ) } [ COLLATE collation ] [ opclass [ ( opclass_parameter = value [, ... ] ) ] ] [ ASC | DESC ] [ NULLS { FIRST | LAST } ] [, ...] )
       [INCLUDE ( column_name, [,...] )]
       [NULLS [ NOT ] DISTINCT]
       [WITH <storage_parameter_list>]
       [TABLESPACE tablespace_name]
       [WHERE <where_conds...>]
`,
	},
	//line sql.y: 10072
	`RELEASE`: {
		ShortDescription: `complete a sub-transaction`,
		//line sql.y: 10073
		Category: hTxn,
		//line sql.y: 10074
		Text: `RELEASE [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 10075
		SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 10083
	`RESUME JOBS`: {
		ShortDescription: `resume background jobs`,
		//line sql.y: 10084
		Category: hMisc,
		//line sql.y: 10085
		Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
		//line sql.y: 10088
		SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
	},
	//line sql.y: 10110
	`RESUME SCHEDULES`: {
		ShortDescription: `resume executing scheduled jobs`,
		//line sql.y: 10111
		Category: hMisc,
		//line sql.y: 10112
		Text: `
RESUME SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

RESUME SCHEDULES <jobid>

`,
		//line sql.y: 10118
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, RESUME JOBS
`,
	},
	//line sql.y: 10139
	`DROP SCHEDULES`: {
		ShortDescription: `destroy specified schedules`,
		//line sql.y: 10140
		Category: hMisc,
		//line sql.y: 10141
		Text: `
DROP SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

DROP SCHEDULES <jobid>

`,
		//line sql.y: 10147
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 10168
	`SAVEPOINT`: {
		ShortDescription: `start a sub-transaction`,
		//line sql.y: 10169
		Category: hTxn,
		//line sql.y: 10170
		Text: `SAVEPOINT <savepoint name>
`,
		//line sql.y: 10171
		SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 10186
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 10187
		Category: hTxn,
		//line sql.y: 10188
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 10196
		SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
	},
	//line sql.y: 10209
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 10210
		Category: hTxn,
		//line sql.y: 10211
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 10214
		SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
	},
	//line sql.y: 10241
	`ROLLBACK`: {
		ShortDescription: `abort the current (sub-)transaction`,
		//line sql.y: 10242
		Category: hTxn,
		//line sql.y: 10243
		Text: `
ROLLBACK [TRANSACTION]
ROLLBACK [TRANSACTION] TO [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 10246
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
	},
	//line sql.y: 10362
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 10363
		Category: hDDL,
		//line sql.y: 10364
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 10365
		SeeAlso: `WEBDOCS/create-database.html
`,
	},
	//line sql.y: 10579
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 10580
		Category: hDML,
		//line sql.y: 10581
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT {
         [( <colnames...> )] [WHERE <arbiter_predicate>] DO NOTHING |
         ( <colnames...> ) [WHERE <index_predicate>] DO UPDATE SET ... [WHERE <expr>]
       }
       [RETURNING <exprs...>]
`,
		//line sql.y: 10589
		SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
	},
	//line sql.y: 10608
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 10609
		Category: hDML,
		//line sql.y: 10610
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 10614
		SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
	},
	//line sql.y: 10730
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 10731
		Category: hDML,
		//line sql.y: 10732
		Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
		//line sql.y: 10739
		SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
	},
	//line sql.y: 10964
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 10965
		Category: hDML,
		//line sql.y: 10966
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 11001
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 11002
		Category: hDML,
		//line sql.y: 11003
		Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 11015
		SeeAlso: `WEBDOCS/select-clause.html
`,
	},
	//line sql.y: 11101
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 11102
		Category: hDML,
		//line sql.y: 11103
		Text: `TABLE <tablename>
`,
		//line sql.y: 11104
		SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 11459
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 11460
		Category: hDML,
		//line sql.y: 11461
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 11462
		SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 11571
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 11572
		Category: hDML,
		//line sql.y: 11573
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP } ]

`,
		//line sql.y: 11595
		SeeAlso: `WEBDOCS/table-expressions.html
`,
	},
}
