[package]
name = "server"
description = "The Doltgres server: configuration, connections, authentication, and the Postgres wire protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "doltgres"
path = "src/main.rs"

[dependencies]
base64 = "0.22"
doltdb = { path = "../doltdb" }
harness = { path = "../harness" }
hmac = "0.12"
mimalloc = "0.1"
pbkdf2 = "0.12"
pgproto.workspace = true
rand = "0.8"
remotes = { path = "../remotes" }
rustls = "0.23"
sha2 = "0.10"
signal-hook = "0.3"
sql = { path = "../sql" }
yaml-rust2 = "0.13"

[lints]
workspace = true
