// Copyright 2024 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package functions

// Init initializes all functions in this package.
func Init() {
	initAbs()
	initAcos()
	initAcosd()
	initAcosh()
	initArrayAppend()
	initArrayToString()
	initAscii()
	initAsin()
	initAsind()
	initAsinh()
	initAtan()
	initAtan2()
	initAtan2d()
	initAtand()
	initAtanh()
	initBitLength()
	initBtrim()
	initCbrt()
	initCeil()
	initCharLength()
	initChr()
	initColDescription()
	initCos()
	initCosd()
	initCosh()
	initCot()
	initCotd()
	initCurrentDatabase()
	initCurrentSchema()
	initCurrentSchemas()
	initDegrees()
	initDiv()
	initExp()
	initFactorial()
	initFloor()
	initFormatType()
	initGcd()
	initInitcap()
	initLcm()
	initLeft()
	initLength()
	initLn()
	initLog()
	initLog10()
	initLower()
	initLpad()
	initLtrim()
	initMd5()
	initMinScale()
	initMod()
	initNextVal()
	initObjDescription()
	initOctetLength()
	initPgEncodingToChar()
	initPgFunctionIsVisible()
	initPgGetFunctionDef()
	initPgGetTriggerDef()
	initPgGetUserbyid()
	initPgGetViewDef()
	initPgTableIsVisible()
	initPi()
	initPower()
	initRadians()
	initRandom()
	initRepeat()
	initReplace()
	initReverse()
	initRight()
	initRound()
	initRpad()
	initRtrim()
	initScale()
	initSetVal()
	initShobjDescription()
	initSign()
	initSin()
	initSind()
	initSinh()
	initSplitPart()
	initSqrt()
	initStrpos()
	initSubstr()
	initTan()
	initTand()
	initTanh()
	initToHex()
	initToRegclass()
	initToRegproc()
	initToRegtype()
	initTrimScale()
	initTrunc()
	initUpper()
	initVersion()
	initWidthBucket()
}
