name: Test Go SQL Server Driver

on: [pull_request]

concurrency:
  group: ci-go-sql-server-driver-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go SQL Server Driver tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-latest ]
    steps:
      - uses: actions/checkout@v6
      - name: Create CI Bin
        run: |
          mkdir -p ./.ci_bin
          echo "$(pwd)/.ci_bin" >> $GITHUB_PATH
      - name: Set up Rust
        run: rustup toolchain install
      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2
      - name: Build DoltgreSQL
        run: |
          cargo build --release -p server
          cp target/release/doltgres .ci_bin/doltgres
          echo "DOLTGRES_BIN_PATH=$(pwd)/.ci_bin/doltgres" >> $GITHUB_ENV
      - name: Test SQL Server Driver
        run: cargo test --profile quick -p driver --no-fail-fast
