name: Test Import Regressions
on: [pull_request]

concurrency:
  group: test-import-dumps-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-import-dumps:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GITHUB_ACTION_IMPORT_DUMPS: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up Rust
      run: rustup toolchain install
    - name: Cache Rust builds
      uses: Swatinem/rust-cache@v2
    - name: Build server
      shell: bash
      run: cargo build --release -p server
    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@v3
      with:
        postgresql-version: 15
    - name: Test
      shell: bash
      run: |
        bin="$(pwd)/target/release/doltgres"
        if [ -f "$bin.exe" ]; then bin="$(cygpath -w "$bin.exe")"; fi
        DOLTGRES_TEST_TARGET="doltgres:$bin" cargo test --profile quick -p doltgres-tests --test dumps
