// Copyright 2026 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// FILES lists the recorded files in replay order, which matters since later files use objects from earlier ones.
pub const FILES: [&str; 205] = [
    "test_setup",
    "tablespace",
    "boolean",
    "char",
    "name",
    "varchar",
    "text",
    "int2",
    "int4",
    "int8",
    "oid",
    "float4",
    "float8",
    "bit",
    "numeric",
    "txid",
    "uuid",
    "enum",
    "money",
    "rangetypes",
    "pg_lsn",
    "regproc",
    "strings",
    "numerology",
    "point",
    "lseg",
    "line",
    "box",
    "path",
    "polygon",
    "circle",
    "date",
    "time",
    "timetz",
    "timestamp",
    "timestamptz",
    "interval",
    "inet",
    "macaddr",
    "macaddr8",
    "multirangetypes",
    "geometry",
    "horology",
    "tstypes",
    "regex",
    "type_sanity",
    "opr_sanity",
    "misc_sanity",
    "comments",
    "expressions",
    "unicode",
    "xid",
    "mvcc",
    "copy",
    "copyselect",
    "copydml",
    "insert",
    "insert_conflict",
    "create_misc",
    "create_operator",
    "create_procedure",
    "create_table",
    "create_type",
    "create_schema",
    "create_index",
    "create_index_spgist",
    "create_view",
    "index_including",
    "index_including_gist",
    "create_aggregate",
    "create_function_sql",
    "create_cast",
    "constraints",
    "triggers",
    "select",
    "inherit",
    "typed_table",
    "vacuum",
    "drop_if_exists",
    "updatable_views",
    "roleattributes",
    "create_am",
    "hash_func",
    "errors",
    "infinite_recurse",
    "sanity_check",
    "select_into",
    "select_distinct",
    "select_distinct_on",
    "select_implicit",
    "select_having",
    "subselect",
    "union",
    "case",
    "join",
    "aggregates",
    "transactions",
    "random",
    "portals",
    "arrays",
    "btree_index",
    "hash_index",
    "update",
    "delete",
    "namespace",
    "brin",
    "gin",
    "gist",
    "spgist",
    "init_privs",
    "security_label",
    "collate",
    "matview",
    "lock",
    "replica_identity",
    "rowsecurity",
    "object_address",
    "tablesample",
    "groupingsets",
    "drop_operator",
    "password",
    "identity",
    "generated",
    "join_hash",
    "brin_bloom",
    "brin_multi",
    "create_table_like",
    "alter_generic",
    "alter_operator",
    "misc",
    "async",
    "dbsize",
    "merge",
    "misc_functions",
    "sysviews",
    "tsrf",
    "tid",
    "tidscan",
    "tidrangescan",
    "collate.icu.utf8",
    "incremental_sort",
    "create_role",
    "rules",
    "psql",
    "psql_crosstab",
    "amutils",
    "stats_ext",
    "select_parallel",
    "write_parallel",
    "vacuum_parallel",
    "publication",
    "subscription",
    "select_views",
    "portals_p2",
    "foreign_key",
    "cluster",
    "dependency",
    "guc",
    "bitmapops",
    "combocid",
    "tsearch",
    "tsdicts",
    "window",
    "xmlmap",
    "functional_deps",
    "advisory_lock",
    "indirect_toast",
    "equivclass",
    "json",
    "jsonb",
    "json_encoding",
    "jsonpath",
    "jsonpath_encoding",
    "jsonb_jsonpath",
    "plancache",
    "limit",
    "plpgsql",
    "copy2",
    "domain",
    "rangefuncs",
    "prepare",
    "conversion",
    "truncate",
    "alter_table",
    "sequence",
    "polymorphism",
    "rowtypes",
    "returning",
    "largeobject",
    "with",
    "xml",
    "partition_join",
    "partition_prune",
    "reloptions",
    "hash_part",
    "indexing",
    "partition_aggregate",
    "partition_info",
    "tuplesort",
    "explain",
    "compression",
    "memoize",
    "event_trigger",
    "oidjoins",
    "fast_default",
];

/// QUERIES_TO_SKIP lists text that fails any query containing it.
pub const QUERIES_TO_SKIP: [&str; 17] = [
    "CREATE VIEW lock_view7 AS SELECT * from lock_view2;",
    "create index testtable_apple_index on testtable_apple(logdate);",
    "create index testtable_orange_index on testtable_orange(logdate);",
    "create table child_0_10 partition of parent_tab\n  for values from (0) to (10);",
    "create table child_10_20 partition of parent_tab\n  for values from (10) to (20);",
    "create table child_20_30 partition of parent_tab\n  for values from (20) to (30);",
    "create table child_30_35 partition of child_30_40\n  for values from (30) to (35);",
    "create table child_35_40 partition of child_30_40\n   for values from (35) to (40);",
    "select count(*)\nfrom\n  (select t3.tenthous as x1, coalesce(t1.stringu1, t2.stringu1) as x2\n   from tenk1 t1\n   left join tenk1 t2 on t1.unique1 = t2.unique1\n   join tenk1 t3 on t1.unique2 = t3.unique2) ss,\n  tenk1 t4,\n  tenk1 t5\nwhere t4.thousand = t5.unique1 and ss.x1 = t4.tenthous and ss.x2 = t5.stringu1;",
    "select count(*) from\n  (select * from tenk1 x order by x.thousand, x.twothousand, x.fivethous) x\n  left join\n  (select * from tenk1 y order by y.unique2) y\n  on x.thousand = y.unique2 and x.twothousand = y.hundred and x.fivethous = y.unique2;",
    "select count(*) from tenk1 a, tenk1 b\n  where a.hundred = b.thousand and (b.fivethous % 10) < 10;",
    "select a.unique2, a.ten, b.tenthous, b.unique2, b.hundred\nfrom tenk1 a left join tenk1 b on a.unique2 = b.tenthous\nwhere a.unique1 = 42 and\n      ((b.unique2 is null and a.ten = 2) or b.hundred = 3);",
    "select\n  (select max((select i.unique2 from tenk1 i where i.unique1 = o.unique1)))\nfrom tenk1 o;",
    "SELECT pg_class.relname FROM pg_index, pg_class, pg_class AS pg_class_2\nWHERE pg_class.oid=indexrelid\n\tAND indrelid=pg_class_2.oid\n\tAND pg_class_2.relname = 'clstr_tst'\n\tAND indisclustered;",
    "SELECT 1 FROM pg_catalog.pg_constraint WHERE conrelid = i.indrelid AND conindid = i.indexrelid",
    "SELECT generate_series(1, generate_series(1, 3))",
    "SELECT generate_series(generate_series(1,3), generate_series(2, 4));",
];
